/* Generated by tools/research/gen_gpu_tables.py - do not edit by hand.
 * Source: Haiku 7be0fef07df0ecbe6f40a4cf2a7687775f1f28a0, per-family PCI binding tables and the
 * accelerant hook tables next to them.  Rows a line comment or an `#if 0`
 * block excludes are absent,
 * macro-valued rows are resolved, and rebranded vendors keep their own list.
 * Regenerate with:
 *   python3 tools/research/gen_gpu_tables.py --haiku DIR \
 *       --out kernel/drivers/gpu/gpu_ids.h
 * and verify with `--check`.  A row here is a matching rule, not a claim that
 * SCos drives that chip: see gpu_drivers.c for what is actually ported.
 */
#ifndef SCOS_GPU_IDS_H
#define SCOS_GPU_IDS_H

/* radeon: 144 device IDs bound by src/add-ons/kernel/drivers/graphics/radeon/detect.c; no class test upstream (vendor + device only). */
static const struct gpu_pci_id gpu_ids_radeon[] = {
    {0x1002, 0x5144, "Radeon 7200 / Radeon / ALL-IN-WONDER Radeon"}, /* detect.c:254 */
    {0x1002, 0x5145, "Radeon QE"}, /* detect.c:255 */
    {0x1002, 0x5146, "Radeon QF"}, /* detect.c:256 */
    {0x1002, 0x5147, "Radeon QG"}, /* detect.c:257 */
    {0x1002, 0x5159, "Radeon 7000 / Radeon VE"}, /* detect.c:260 */
    {0x1002, 0x515a, "Radeon QZ VE"}, /* detect.c:261 */
    {0x1002, 0x515e, "ES1000 515E (PCI)"}, /* detect.c:263 */
    {0x1002, 0x5969, "ES1000 5969 (PCI)"}, /* detect.c:264 */
    {0x1002, 0x4c59, "Radeon Mobility"}, /* detect.c:267 */
    {0x1002, 0x4c5a, "Radeon Mobility M6 LZ"}, /* detect.c:268 */
    {0x1002, 0x5157, "Radeon 7500 / ALL-IN-WONDER Radeon 7500"}, /* detect.c:271 */
    {0x1002, 0x5158, "Radeon 7500 QX"}, /* detect.c:272 */
    {0x1002, 0x4c57, "Radeon Mobility 7500"}, /* detect.c:275 */
    {0x1002, 0x4c58, "Radeon Mobility 7500 GL"}, /* detect.c:276 */
    {0x1002, 0x5148, "Fire GL E1"}, /* detect.c:279 */
    {0x1002, 0x5149, "Radeon 8500 QI"}, /* detect.c:280 */
    {0x1002, 0x514a, "Radeon 8500 QJ"}, /* detect.c:281 */
    {0x1002, 0x514b, "Radeon 8500 QK"}, /* detect.c:282 */
    {0x1002, 0x514c, "Radeon 8500 / 8500LE / ALL-IN-WONDER Radeon 8500"}, /* detect.c:283 */
    {0x1002, 0x514d, "Radeon 9100"}, /* detect.c:284 */
    {0x1002, 0x5168, "Radeon 8500 Qh"}, /* detect.c:286 */
    {0x1002, 0x5169, "Radeon 8500 Qi"}, /* detect.c:287 */
    {0x1002, 0x516a, "Radeon 8500 Qj"}, /* detect.c:288 */
    {0x1002, 0x516b, "Radeon 8500 Qk"}, /* detect.c:289 */
    {0x1002, 0x4242, "ALL-IN-Wonder Radeon 8500 DV (BB)"}, /* detect.c:291 */
    {0x1002, 0x4243, "ALL-IN-Wonder Radeon 8500 DV (BC)"}, /* detect.c:292 */
    {0x1002, 0x4966, "Radeon 9000"}, /* detect.c:295 */
    {0x1002, 0x4967, "Radeon 9000 Ig"}, /* detect.c:296 */
    {0x1002, 0x4c64, "Radeon Mobility 9000 Ld"}, /* detect.c:299 */
    {0x1002, 0x4c65, "Radeon Mobility 9000 Le"}, /* detect.c:300 */
    {0x1002, 0x4c66, "Radeon Mobility 9000 Lf"}, /* detect.c:301 */
    {0x1002, 0x4c67, "Radeon Mobility 9000 Lg"}, /* detect.c:302 */
    {0x1002, 0x5960, "Radeon 9200 Pro"}, /* detect.c:305 */
    {0x1002, 0x5961, "Radeon 9200"}, /* detect.c:306 */
    {0x1002, 0x5962, "Radeon 9200"}, /* detect.c:307 */
    {0x1002, 0x5964, "Radeon 9200 SE"}, /* detect.c:308 */
    {0x1002, 0x5965, "Ati FireMV 2200"}, /* detect.c:309 */
    {0x1002, 0x5c61, "Radeon Mobility 9200"}, /* detect.c:312 */
    {0x1002, 0x5c63, "Radeon Mobility 9200"}, /* detect.c:313 */
    {0x1002, 0x4e44, "Radeon 9700 ND"}, /* detect.c:316 */
    {0x1002, 0x4e45, "Radeon 9700 NE"}, /* detect.c:317 */
    {0x1002, 0x4e46, "Radeon 9600 XT"}, /* detect.c:318 */
    {0x1002, 0x4e47, "Radeon 9700 NG"}, /* detect.c:319 */
    {0x1002, 0x4144, "Radeon 9700 AD"}, /* detect.c:322 */
    {0x1002, 0x4145, "Radeon 9700 AE"}, /* detect.c:323 */
    {0x1002, 0x4146, "Radeon 9700 AF"}, /* detect.c:324 */
    {0x1002, 0x4147, "Radeon 9700 AG"}, /* detect.c:325 */
    {0x1002, 0x4150, "Radeon 9600 AP"}, /* detect.c:328 */
    {0x1002, 0x4151, "Radeon 9600SE AQ"}, /* detect.c:329 */
    {0x1002, 0x4152, "Radeon 9600XT AR"}, /* detect.c:330 */
    {0x1002, 0x4153, "Radeon 9550 AS"}, /* detect.c:331 */
    {0x1002, 0x4154, "FireGL T2 AT"}, /* detect.c:332 */
    {0x1002, 0x4155, "Radeon 9650 4155"}, /* detect.c:333 */
    {0x1002, 0x4156, "Radeon 9600 AQ"}, /* detect.c:334 */
    {0x1002, 0x4e50, "Radeon Mobility 9600/9700 (M10/M11) NP"}, /* detect.c:337 */
    {0x1002, 0x4e51, "Radeon Mobility 9600 (M10) NQ"}, /* detect.c:338 */
    {0x1002, 0x4e52, "Radeon Mobility 9600 (M11) NR"}, /* detect.c:339 */
    {0x1002, 0x4e53, "Radeon Mobility 9600 (M10) NS"}, /* detect.c:340 */
    {0x1002, 0x4e54, "ATI FireGL Mobility T2 (M10) NT"}, /* detect.c:341 */
    {0x1002, 0x4e56, "ATI FireGL Mobility T2e (M11) NV"}, /* detect.c:342 */
    {0x1002, 0x4148, "Radeon 9800SE AH"}, /* detect.c:345 */
    {0x1002, 0x4149, "Radeon 9800 AI"}, /* detect.c:346 */
    {0x1002, 0x414a, "Radeon 9800 AJ"}, /* detect.c:347 */
    {0x1002, 0x414b, "FireGL X2 AK"}, /* detect.c:348 */
    {0x1002, 0x4e48, "Radeon 9800 Pro NH"}, /* detect.c:349 */
    {0x1002, 0x4e49, "Radeon 9800 NI"}, /* detect.c:350 */
    {0x1002, 0x4e4b, "FireGL X2 NK"}, /* detect.c:351 */
    {0x1002, 0x4e4a, "Radeon 9800 XT"}, /* detect.c:352 */
    {0x1002, 0x5b60, "Radeon X300 (RV370) 5B60"}, /* detect.c:355 */
    {0x1002, 0x5b62, "Radeon X600 (RV370) 5B62"}, /* detect.c:356 */
    {0x1002, 0x5b63, "Radeon X1050 (RV370) 5B63"}, /* detect.c:357 */
    {0x1002, 0x5b64, "FireGL V3100 (RV370) 5B64"}, /* detect.c:358 */
    {0x1002, 0x5b65, "FireGL D1100 (RV370) 5B65"}, /* detect.c:359 */
    {0x1002, 0x5460, "Radeon Mobility M300 (M22) 5460"}, /* detect.c:360 */
    {0x1002, 0x5464, "FireGL M22 GL 5464"}, /* detect.c:361 */
    {0x1002, 0x3e50, "Radeon X600 (RV380) 3E50"}, /* detect.c:364 */
    {0x1002, 0x3e54, "FireGL V3200 (RV380) 3E54"}, /* detect.c:365 */
    {0x1002, 0x3150, "Radeon Mobility X600 (M24) 3150"}, /* detect.c:366 */
    {0x1002, 0x3154, "FireGL M24 GL 3154"}, /* detect.c:367 */
    {0x1002, 0x5462, "Radeon X600SE (RV3?0) 5462"}, /* detect.c:368 */
    {0x1002, 0x5e48, "FireGL V5000 (RV410)"}, /* detect.c:374 */
    {0x1002, 0x564a, "Mobility FireGL V5000 (M26)"}, /* detect.c:375 */
    {0x1002, 0x564b, "Mobility FireGL V5000 (M26)"}, /* detect.c:376 */
    {0x1002, 0x564f, "Mobility Radeon X700 XL (M26)"}, /* detect.c:377 */
    {0x1002, 0x5652, "Mobility Radeon X700 (M26)"}, /* detect.c:378 */
    {0x1002, 0x5653, "Mobility Radeon X700 (M26)"}, /* detect.c:379 */
    {0x1002, 0x5e4b, "Radeon X700 PRO (RV410)"}, /* detect.c:380 */
    {0x1002, 0x5e4a, "Radeon X700 XT (RV410)"}, /* detect.c:381 */
    {0x1002, 0x5e4d, "Radeon X700 (RV410)"}, /* detect.c:382 */
    {0x1002, 0x5e4c, "Radeon X700 SE (RV410)"}, /* detect.c:383 */
    {0x1002, 0x5e4f, "Radeon X700 SE (RV410)"}, /* detect.c:384 */
    {0x1002, 0x4a48, "Radeon X800 (R420) JH"}, /* detect.c:387 */
    {0x1002, 0x4a49, "Radeon X800PRO (R420) JI"}, /* detect.c:388 */
    {0x1002, 0x4a4a, "Radeon X800SE (R420) JJ"}, /* detect.c:389 */
    {0x1002, 0x4a4b, "Radeon X800 (R420) JK"}, /* detect.c:390 */
    {0x1002, 0x4a4c, "Radeon X800 (R420) JL"}, /* detect.c:391 */
    {0x1002, 0x4a4d, "FireGL X3 (R420) JM"}, /* detect.c:392 */
    {0x1002, 0x4a4e, "Radeon Mobility 9800 (M18) JN"}, /* detect.c:393 */
    {0x1002, 0x4a50, "Radeon X800XT (R420) JP"}, /* detect.c:394 */
    {0x1002, 0x4a4f, "Radeon X800 SE (R420)"}, /* detect.c:395 */
    {0x1002, 0x5548, "Radeon X800 (R423) UH"}, /* detect.c:398 */
    {0x1002, 0x5549, "Radeon X800PRO (R423) UI"}, /* detect.c:399 */
    {0x1002, 0x554a, "Radeon X800LE (R423) UJ"}, /* detect.c:400 */
    {0x1002, 0x554b, "Radeon X800SE (R423) UK"}, /* detect.c:401 */
    {0x1002, 0x5551, "FireGL V7200 (R423) UQ"}, /* detect.c:402 */
    {0x1002, 0x5552, "FireGL V5100 (R423) UR"}, /* detect.c:403 */
    {0x1002, 0x5554, "FireGL V7100 (R423) UT"}, /* detect.c:404 */
    {0x1002, 0x554f, "Radeon X800 UO"}, /* detect.c:406 */
    {0x1002, 0x554d, "Radeon X800 UM"}, /* detect.c:407 */
    {0x1002, 0x5d57, "Radeon X800 XT"}, /* detect.c:409 */
    {0x1002, 0x5550, "FireGL V7100 (R423)"}, /* detect.c:410 */
    {0x1002, 0x5d49, "Mobility FireGL V5100 (M28)"}, /* detect.c:413 */
    {0x1002, 0x5d4a, "Mobility Radeon X800 (M28)"}, /* detect.c:414 */
    {0x1002, 0x5d48, "Mobility Radeon X800 XT (M28)"}, /* detect.c:415 */
    {0x1002, 0x554e, "Radeon X800 SE (R430)"}, /* detect.c:418 */
    {0x1002, 0x554c, "Radeon X800 XTP (R430)"}, /* detect.c:419 */
    {0x1002, 0x5d4c, "Radeon X850 5D4C"}, /* detect.c:422 */
    {0x1002, 0x5d50, "Radeon FireGL (R480) GL 5D50"}, /* detect.c:423 */
    {0x1002, 0x5d4e, "Radeon X850 SE (R480)"}, /* detect.c:424 */
    {0x1002, 0x5d4f, "Radeon X850 PRO (R480)"}, /* detect.c:425 */
    {0x1002, 0x5d52, "Radeon X850 XT (R480)"}, /* detect.c:426 */
    {0x1002, 0x5d4d, "Radeon X850 XT PE (R480)"}, /* detect.c:427 */
    {0x1002, 0x4b4a, "Radeon X850 PRO (R480)"}, /* detect.c:430 */
    {0x1002, 0x4b4b, "Radeon X850 SE (R480)"}, /* detect.c:431 */
    {0x1002, 0x4b4c, "Radeon X850 XT (R480)"}, /* detect.c:432 */
    {0x1002, 0x4b49, "Radeon X850 XT PE (R480)"}, /* detect.c:433 */
    {0x1002, 0x4136, "Radeon IGP320 (A3) 4136"}, /* detect.c:436 */
    {0x1002, 0x4336, "Radeon IGP320M (U1) 4336"}, /* detect.c:437 */
    {0x1002, 0x4137, "Radeon IGP330/340/350 (A4) 4137"}, /* detect.c:440 */
    {0x1002, 0x4337, "Radeon IGP330M/340M/350M (U2) 4337"}, /* detect.c:441 */
    {0x1002, 0x4237, "IGP330M/340M/350M (U2) 4337"}, /* detect.c:444 */
    {0x1002, 0x4437, "Radeon Mobility 7000 IGP 4437"}, /* detect.c:445 */
    {0x1002, 0x5834, "Radeon 9100 IGP (A5) 5834"}, /* detect.c:448 */
    {0x1002, 0x5835, "Radeon Mobility 9100 IGP (U3) 5835"}, /* detect.c:449 */
    {0x1002, 0x7834, "Radeon 9100 PRO IGP 7834"}, /* detect.c:452 */
    {0x1002, 0x7835, "Radeon Mobility 9200 IGP 7835"}, /* detect.c:453 */
    {0x1002, 0x5a41, "Radeon XPRESS 200 5A41"}, /* detect.c:456 */
    {0x1002, 0x5a42, "Radeon XPRESS 200M 5A42"}, /* detect.c:457 */
    {0x1002, 0x5a61, "Radeon XPRESS 200 5A61"}, /* detect.c:460 */
    {0x1002, 0x5a62, "Radeon XPRESS 200M 5A62"}, /* detect.c:461 */
    {0x1002, 0x5954, "Radeon XPRESS 200 5954"}, /* detect.c:464 */
    {0x1002, 0x5955, "Radeon XPRESS 200M 5955"}, /* detect.c:465 */
    {0x1002, 0x5974, "Radeon XPRESS 200 5974"}, /* detect.c:466 */
    {0x1002, 0x5975, "Radeon XPRESS 200M 5975"}, /* detect.c:467 */
};

/* nvidia: 249 device IDs bound by src/add-ons/kernel/drivers/graphics/nvidia/driver.c; no class test upstream (vendor + device only). */
static const struct gpu_pci_id gpu_ids_nvidia[] = {
    {0x10de, 0x20, "Nvidia TNT1"}, /* driver.c:99 */
    {0x10de, 0x28, "Nvidia TNT2 (pro)"}, /* driver.c:100 */
    {0x10de, 0x29, "Nvidia TNT2 Ultra"}, /* driver.c:101 */
    {0x10de, 0x2a, "Nvidia TNT2"}, /* driver.c:102 */
    {0x10de, 0x2b, "Nvidia TNT2"}, /* driver.c:103 */
    {0x10de, 0x2c, "Nvidia Vanta (Lt)"}, /* driver.c:104 */
    {0x10de, 0x2d, "Nvidia TNT2-M64 (Pro)"}, /* driver.c:105 */
    {0x10de, 0x2e, "Nvidia NV06 Vanta"}, /* driver.c:106 */
    {0x10de, 0x2f, "Nvidia NV06 Vanta"}, /* driver.c:107 */
    {0x10de, 0x40, "Nvidia Geforce FX 6800 Ultra"}, /* driver.c:108 */
    {0x10de, 0x41, "Nvidia Geforce FX 6800"}, /* driver.c:109 */
    {0x10de, 0x42, "Nvidia Geforce FX 6800LE"}, /* driver.c:110 */
    {0x10de, 0x43, "Nvidia Geforce 6800 XE"}, /* driver.c:111 */
    {0x10de, 0x45, "Nvidia Geforce FX 6800 GT"}, /* driver.c:112 */
    {0x10de, 0x46, "Nvidia Geforce FX 6800 GT"}, /* driver.c:113 */
    {0x10de, 0x47, "Nvidia Geforce 6800 GS"}, /* driver.c:114 */
    {0x10de, 0x48, "Nvidia Geforce FX 6800 XT"}, /* driver.c:115 */
    {0x10de, 0x49, "Nvidia unknown FX"}, /* driver.c:116 */
    {0x10de, 0x4d, "Nvidia Quadro FX 4400"}, /* driver.c:117 */
    {0x10de, 0x4e, "Nvidia Quadro FX 4000"}, /* driver.c:118 */
    {0x10de, 0x91, "Nvidia Geforce 7800 GTX PCIe"}, /* driver.c:119 */
    {0x10de, 0x92, "Nvidia Geforce 7800 GT PCIe"}, /* driver.c:120 */
    {0x10de, 0x98, "Nvidia Geforce 7800 Go PCIe"}, /* driver.c:121 */
    {0x10de, 0x99, "Nvidia Geforce 7800 GTX Go PCIe"}, /* driver.c:122 */
    {0x10de, 0x9d, "Nvidia Quadro FX 4500"}, /* driver.c:123 */
    {0x10de, 0xa0, "Nvidia Aladdin TNT2"}, /* driver.c:124 */
    {0x10de, 0xc0, "Nvidia Geforce 6800 GS"}, /* driver.c:125 */
    {0x10de, 0xc1, "Nvidia Geforce FX 6800"}, /* driver.c:126 */
    {0x10de, 0xc2, "Nvidia Geforce FX 6800LE"}, /* driver.c:127 */
    {0x10de, 0xc3, "Nvidia Geforce FX 6800 XT"}, /* driver.c:128 */
    {0x10de, 0xc8, "Nvidia Geforce FX 6800 Go"}, /* driver.c:129 */
    {0x10de, 0xc9, "Nvidia Geforce FX 6800 Ultra Go"}, /* driver.c:130 */
    {0x10de, 0xcc, "Nvidia Quadro FX 1400 Go"}, /* driver.c:131 */
    {0x10de, 0xcd, "Nvidia Quadro FX 3450/4000 SDI"}, /* driver.c:132 */
    {0x10de, 0xce, "Nvidia Quadro FX 1400"}, /* driver.c:133 */
    {0x10de, 0xf0, "Nvidia Geforce FX 6800 (Ultra) AGP(?)"}, /* driver.c:134 */
    {0x10de, 0xf1, "Nvidia Geforce FX 6600 GT AGP"}, /* driver.c:135 */
    {0x10de, 0xf2, "Nvidia Geforce FX 6600 AGP"}, /* driver.c:136 */
    {0x10de, 0xf3, "Nvidia Geforce 6200"}, /* driver.c:137 */
    {0x10de, 0xf4, "Nvidia Geforce 6600 LE"}, /* driver.c:138 */
    {0x10de, 0xf5, "Nvidia Geforce FX 7800 GS AGP"}, /* driver.c:139 */
    {0x10de, 0xf6, "Nvidia Geforce 6800 GS"}, /* driver.c:140 */
    {0x10de, 0xf8, "Nvidia Quadro FX 3400/4400 PCIe"}, /* driver.c:141 */
    {0x10de, 0xf9, "Nvidia Geforce PCX 6800 PCIe"}, /* driver.c:142 */
    {0x10de, 0xfa, "Nvidia Geforce PCX 5750 PCIe"}, /* driver.c:143 */
    {0x10de, 0xfb, "Nvidia Geforce PCX 5900 PCIe"}, /* driver.c:144 */
    {0x10de, 0xfc, "Nvidia Geforce PCX 5300 PCIe"}, /* driver.c:145 */
    {0x10de, 0xfd, "Nvidia Quadro PCX PCIe"}, /* driver.c:146 */
    {0x10de, 0xfe, "Nvidia Quadro FX 1300 PCIe(?)"}, /* driver.c:147 */
    {0x10de, 0xff, "Nvidia Geforce PCX 4300 PCIe"}, /* driver.c:148 */
    {0x10de, 0x100, "Nvidia Geforce256 SDR"}, /* driver.c:149 */
    {0x10de, 0x101, "Nvidia Geforce256 DDR"}, /* driver.c:150 */
    {0x10de, 0x102, "Nvidia Geforce256 Ultra"}, /* driver.c:151 */
    {0x10de, 0x103, "Nvidia Quadro"}, /* driver.c:152 */
    {0x10de, 0x110, "Nvidia Geforce2 MX/MX400"}, /* driver.c:153 */
    {0x10de, 0x111, "Nvidia Geforce2 MX100/MX200 DDR"}, /* driver.c:154 */
    {0x10de, 0x112, "Nvidia Geforce2 Go"}, /* driver.c:155 */
    {0x10de, 0x113, "Nvidia Quadro2 MXR/EX/Go"}, /* driver.c:156 */
    {0x10de, 0x140, "Nvidia Geforce FX 6600 GT"}, /* driver.c:157 */
    {0x10de, 0x141, "Nvidia Geforce FX 6600"}, /* driver.c:158 */
    {0x10de, 0x142, "Nvidia Geforce FX 6600LE"}, /* driver.c:159 */
    {0x10de, 0x143, "Nvidia Geforce 6600 VE"}, /* driver.c:160 */
    {0x10de, 0x144, "Nvidia Geforce FX 6600 Go"}, /* driver.c:161 */
    {0x10de, 0x145, "Nvidia Geforce FX 6610 XL"}, /* driver.c:162 */
    {0x10de, 0x146, "Nvidia Geforce FX 6600 TE Go / 6200 TE Go"}, /* driver.c:163 */
    {0x10de, 0x147, "Nvidia Geforce FX 6700 XL"}, /* driver.c:164 */
    {0x10de, 0x148, "Nvidia Geforce FX 6600 Go"}, /* driver.c:165 */
    {0x10de, 0x149, "Nvidia Geforce FX 6600 GT Go"}, /* driver.c:166 */
    {0x10de, 0x14b, "Nvidia unknown FX"}, /* driver.c:167 */
    {0x10de, 0x14c, "Nvidia Quadro FX 540 MXM"}, /* driver.c:168 */
    {0x10de, 0x14d, "Nvidia unknown FX"}, /* driver.c:169 */
    {0x10de, 0x14e, "Nvidia Quadro FX 540"}, /* driver.c:170 */
    {0x10de, 0x14f, "Nvidia Geforce 6200 PCIe (128Mb)"}, /* driver.c:171 */
    {0x10de, 0x150, "Nvidia Geforce2 GTS/Pro"}, /* driver.c:172 */
    {0x10de, 0x151, "Nvidia Geforce2 Ti DDR"}, /* driver.c:173 */
    {0x10de, 0x152, "Nvidia Geforce2 Ultra"}, /* driver.c:174 */
    {0x10de, 0x153, "Nvidia Quadro2 Pro"}, /* driver.c:175 */
    {0x10de, 0x160, "Nvidia Geforce 6500 Go"}, /* driver.c:176 */
    {0x10de, 0x161, "Nvidia Geforce 6200 TurboCache"}, /* driver.c:177 */
    {0x10de, 0x162, "Nvidia Geforce 6200SE TurboCache"}, /* driver.c:178 */
    {0x10de, 0x163, "Nvidia Geforce 6200LE"}, /* driver.c:179 */
    {0x10de, 0x164, "Nvidia Geforce FX 6200 Go"}, /* driver.c:180 */
    {0x10de, 0x165, "Nvidia Quadro FX NVS 285"}, /* driver.c:181 */
    {0x10de, 0x166, "Nvidia Geforce 6400 Go"}, /* driver.c:182 */
    {0x10de, 0x167, "Nvidia Geforce 6200 Go"}, /* driver.c:183 */
    {0x10de, 0x168, "Nvidia Geforce 6400 Go"}, /* driver.c:184 */
    {0x10de, 0x169, "Nvidia Geforce 6250 Go"}, /* driver.c:185 */
    {0x10de, 0x16a, "Nvidia Geforce 7100 GS"}, /* driver.c:186 */
    {0x10de, 0x16b, "Nvidia unknown FX Go"}, /* driver.c:187 */
    {0x10de, 0x16c, "Nvidia unknown FX Go"}, /* driver.c:188 */
    {0x10de, 0x16d, "Nvidia unknown FX Go"}, /* driver.c:189 */
    {0x10de, 0x16e, "Nvidia unknown FX"}, /* driver.c:190 */
    {0x10de, 0x170, "Nvidia Geforce4 MX 460"}, /* driver.c:191 */
    {0x10de, 0x171, "Nvidia Geforce4 MX 440"}, /* driver.c:192 */
    {0x10de, 0x172, "Nvidia Geforce4 MX 420"}, /* driver.c:193 */
    {0x10de, 0x173, "Nvidia Geforce4 MX 440SE"}, /* driver.c:194 */
    {0x10de, 0x174, "Nvidia Geforce4 440 Go"}, /* driver.c:195 */
    {0x10de, 0x175, "Nvidia Geforce4 420 Go"}, /* driver.c:196 */
    {0x10de, 0x176, "Nvidia Geforce4 420 Go 32M"}, /* driver.c:197 */
    {0x10de, 0x177, "Nvidia Geforce4 460 Go"}, /* driver.c:198 */
    {0x10de, 0x178, "Nvidia Quadro4 500 XGL/550 XGL"}, /* driver.c:199 */
    {0x10de, 0x179, "Nvidia Geforce4 440 Go 64M (PPC: Geforce4 MX)"}, /* driver.c:200 */
    {0x10de, 0x17a, "Nvidia Quadro4 200 NVS/400 NVS"}, /* driver.c:201 */
    {0x10de, 0x17c, "Nvidia Quadro4 500 GoGL"}, /* driver.c:202 */
    {0x10de, 0x17d, "Nvidia Geforce4 410 Go 16M"}, /* driver.c:203 */
    {0x10de, 0x181, "Nvidia Geforce4 MX 440 AGP8X"}, /* driver.c:204 */
    {0x10de, 0x182, "Nvidia Geforce4 MX 440SE AGP8X"}, /* driver.c:205 */
    {0x10de, 0x183, "Nvidia Geforce4 MX 420 AGP8X"}, /* driver.c:206 */
    {0x10de, 0x185, "Nvidia Geforce4 MX 4000 AGP8X"}, /* driver.c:207 */
    {0x10de, 0x186, "Nvidia Geforce4 448 Go"}, /* driver.c:208 */
    {0x10de, 0x187, "Nvidia Geforce4 488 Go"}, /* driver.c:209 */
    {0x10de, 0x188, "Nvidia Quadro4 580 XGL"}, /* driver.c:210 */
    {0x10de, 0x189, "Nvidia Geforce4 MX AGP8X (PPC)"}, /* driver.c:211 */
    {0x10de, 0x18a, "Nvidia Quadro4 280 NVS AGP8X"}, /* driver.c:212 */
    {0x10de, 0x18b, "Nvidia Quadro4 380 XGL"}, /* driver.c:213 */
    {0x10de, 0x18c, "Nvidia Quadro4 NVS 50 PCI"}, /* driver.c:214 */
    {0x10de, 0x18d, "Nvidia Geforce4 448 Go"}, /* driver.c:215 */
    {0x10de, 0x1a0, "Nvidia Geforce2 Integrated GPU"}, /* driver.c:216 */
    {0x10de, 0x1d1, "Nvidia Geforce 7300 LE"}, /* driver.c:217 */
    {0x10de, 0x1d3, "Nvidia Geforce 7300 SE"}, /* driver.c:218 */
    {0x10de, 0x1d7, "Nvidia Quadro NVS 110M/Geforce 7300 Go"}, /* driver.c:219 */
    {0x10de, 0x1d8, "Nvidia Geforce 7400 GO"}, /* driver.c:220 */
    {0x10de, 0x1da, "Nvidia Quadro NVS 110M"}, /* driver.c:221 */
    {0x10de, 0x1dd, "Nvidia Geforce 7500 LE"}, /* driver.c:222 */
    {0x10de, 0x1df, "Nvidia Geforce 7300 GS"}, /* driver.c:223 */
    {0x10de, 0x1f0, "Nvidia Geforce4 MX Integrated GPU"}, /* driver.c:224 */
    {0x10de, 0x200, "Nvidia Geforce3"}, /* driver.c:225 */
    {0x10de, 0x201, "Nvidia Geforce3 Ti 200"}, /* driver.c:226 */
    {0x10de, 0x202, "Nvidia Geforce3 Ti 500"}, /* driver.c:227 */
    {0x10de, 0x203, "Nvidia Quadro DCC"}, /* driver.c:228 */
    {0x10de, 0x211, "Nvidia Geforce FX 6800"}, /* driver.c:229 */
    {0x10de, 0x212, "Nvidia Geforce FX 6800LE"}, /* driver.c:230 */
    {0x10de, 0x215, "Nvidia Geforce FX 6800 GT"}, /* driver.c:231 */
    {0x10de, 0x218, "Nvidia Geforce 6800 XT"}, /* driver.c:232 */
    {0x10de, 0x220, "Nvidia unknown FX"}, /* driver.c:233 */
    {0x10de, 0x221, "Nvidia Geforce 6200 AGP (256Mb - 128bit)"}, /* driver.c:234 */
    {0x10de, 0x222, "Nvidia unknown FX"}, /* driver.c:235 */
    {0x10de, 0x228, "Nvidia unknown FX Go"}, /* driver.c:236 */
    {0x10de, 0x240, "Nvidia Geforce 6150 (NFORCE4 Integr.GPU)"}, /* driver.c:237 */
    {0x10de, 0x241, "Nvidia Geforce 6150 LE (NFORCE4 Integr.GPU)"}, /* driver.c:238 */
    {0x10de, 0x242, "Nvidia Geforce 6100 (NFORCE4 Integr.GPU)"}, /* driver.c:239 */
    {0x10de, 0x244, "Nvidia Geforce Go 6150 (NFORCE4 Integr.GPU)"}, /* driver.c:240 */
    {0x10de, 0x245, "Nvidia Quadro NVS 210S / Geforce 6150LE"}, /* driver.c:241 */
    {0x10de, 0x247, "Nvidia Geforce 6100 Go (NFORCE4 Integr.GPU)"}, /* driver.c:242 */
    {0x10de, 0x250, "Nvidia Geforce4 Ti 4600"}, /* driver.c:243 */
    {0x10de, 0x251, "Nvidia Geforce4 Ti 4400"}, /* driver.c:244 */
    {0x10de, 0x252, "Nvidia Geforce4 Ti 4600"}, /* driver.c:245 */
    {0x10de, 0x253, "Nvidia Geforce4 Ti 4200"}, /* driver.c:246 */
    {0x10de, 0x258, "Nvidia Quadro4 900 XGL"}, /* driver.c:247 */
    {0x10de, 0x259, "Nvidia Quadro4 750 XGL"}, /* driver.c:248 */
    {0x10de, 0x25b, "Nvidia Quadro4 700 XGL"}, /* driver.c:249 */
    {0x10de, 0x280, "Nvidia Geforce4 Ti 4800 AGP8X"}, /* driver.c:250 */
    {0x10de, 0x281, "Nvidia Geforce4 Ti 4200 AGP8X"}, /* driver.c:251 */
    {0x10de, 0x282, "Nvidia Geforce4 Ti 4800SE"}, /* driver.c:252 */
    {0x10de, 0x286, "Nvidia Geforce4 4200 Go"}, /* driver.c:253 */
    {0x10de, 0x288, "Nvidia Quadro4 980 XGL"}, /* driver.c:254 */
    {0x10de, 0x289, "Nvidia Quadro4 780 XGL"}, /* driver.c:255 */
    {0x10de, 0x28c, "Nvidia Quadro4 700 GoGL"}, /* driver.c:256 */
    {0x10de, 0x290, "Nvidia Geforce 7900 GTX"}, /* driver.c:257 */
    {0x10de, 0x291, "Nvidia Geforce 7900 GT"}, /* driver.c:258 */
    {0x10de, 0x292, "Nvidia Geforce 7900 GS"}, /* driver.c:259 */
    {0x10de, 0x293, "Nvidia Geforce 7900 GX2"}, /* driver.c:260 */
    {0x10de, 0x294, "Nvidia Geforce 7950 GX2"}, /* driver.c:261 */
    {0x10de, 0x295, "Nvidia Geforce 7950 GT"}, /* driver.c:262 */
    {0x10de, 0x298, "Nvidia Geforce Go 7900 GS"}, /* driver.c:263 */
    {0x10de, 0x299, "Nvidia Geforce Go 7900 GTX"}, /* driver.c:264 */
    {0x10de, 0x29c, "Nvidia Quadro FX 5500"}, /* driver.c:265 */
    {0x10de, 0x29f, "Nvidia Quadro FX 4500 X2"}, /* driver.c:266 */
    {0x10de, 0x2a0, "Nvidia Geforce3 Integrated GPU"}, /* driver.c:267 */
    {0x10de, 0x2e0, "Nvidia Geforce 7600 GT"}, /* driver.c:268 */
    {0x10de, 0x2e1, "Nvidia Geforce 7600 GS"}, /* driver.c:269 */
    {0x10de, 0x2e2, "Nvidia Geforce 7300 GT"}, /* driver.c:270 */
    {0x10de, 0x301, "Nvidia Geforce FX 5800 Ultra"}, /* driver.c:271 */
    {0x10de, 0x302, "Nvidia Geforce FX 5800"}, /* driver.c:272 */
    {0x10de, 0x308, "Nvidia Quadro FX 2000"}, /* driver.c:273 */
    {0x10de, 0x309, "Nvidia Quadro FX 1000"}, /* driver.c:274 */
    {0x10de, 0x311, "Nvidia Geforce FX 5600 Ultra"}, /* driver.c:275 */
    {0x10de, 0x312, "Nvidia Geforce FX 5600"}, /* driver.c:276 */
    {0x10de, 0x313, "Nvidia unknown FX"}, /* driver.c:277 */
    {0x10de, 0x314, "Nvidia Geforce FX 5600XT"}, /* driver.c:278 */
    {0x10de, 0x316, "Nvidia unknown FX Go"}, /* driver.c:279 */
    {0x10de, 0x317, "Nvidia unknown FX Go"}, /* driver.c:280 */
    {0x10de, 0x31a, "Nvidia Geforce FX 5600 Go"}, /* driver.c:281 */
    {0x10de, 0x31b, "Nvidia Geforce FX 5650 Go"}, /* driver.c:282 */
    {0x10de, 0x31c, "Nvidia Quadro FX 700 Go"}, /* driver.c:283 */
    {0x10de, 0x31d, "Nvidia unknown FX Go"}, /* driver.c:284 */
    {0x10de, 0x31e, "Nvidia unknown FX Go"}, /* driver.c:285 */
    {0x10de, 0x31f, "Nvidia unknown FX Go"}, /* driver.c:286 */
    {0x10de, 0x320, "Nvidia Geforce FX 5200"}, /* driver.c:287 */
    {0x10de, 0x321, "Nvidia Geforce FX 5200 Ultra"}, /* driver.c:288 */
    {0x10de, 0x322, "Nvidia Geforce FX 5200"}, /* driver.c:289 */
    {0x10de, 0x323, "Nvidia Geforce FX 5200LE"}, /* driver.c:290 */
    {0x10de, 0x324, "Nvidia Geforce FX 5200 Go"}, /* driver.c:291 */
    {0x10de, 0x325, "Nvidia Geforce FX 5250 Go"}, /* driver.c:292 */
    {0x10de, 0x326, "Nvidia Geforce FX 5500"}, /* driver.c:293 */
    {0x10de, 0x327, "Nvidia Geforce FX 5100"}, /* driver.c:294 */
    {0x10de, 0x328, "Nvidia Geforce FX 5200 Go 32M/64M"}, /* driver.c:295 */
    {0x10de, 0x329, "Nvidia Geforce FX 5200 (PPC)"}, /* driver.c:296 */
    {0x10de, 0x32a, "Nvidia Quadro NVS 280 PCI"}, /* driver.c:297 */
    {0x10de, 0x32b, "Nvidia Quadro FX 500/600 PCI"}, /* driver.c:298 */
    {0x10de, 0x32c, "Nvidia Geforce FX 5300 Go"}, /* driver.c:299 */
    {0x10de, 0x32d, "Nvidia Geforce FX 5100 Go"}, /* driver.c:300 */
    {0x10de, 0x32e, "Nvidia unknown FX Go"}, /* driver.c:301 */
    {0x10de, 0x32f, "Nvidia unknown FX Go"}, /* driver.c:302 */
    {0x10de, 0x330, "Nvidia Geforce FX 5900 Ultra"}, /* driver.c:303 */
    {0x10de, 0x331, "Nvidia Geforce FX 5900"}, /* driver.c:304 */
    {0x10de, 0x332, "Nvidia Geforce FX 5900 XT"}, /* driver.c:305 */
    {0x10de, 0x333, "Nvidia Geforce FX 5950 Ultra"}, /* driver.c:306 */
    {0x10de, 0x334, "Nvidia Geforce FX 5900 ZT"}, /* driver.c:307 */
    {0x10de, 0x338, "Nvidia Quadro FX 3000"}, /* driver.c:308 */
    {0x10de, 0x33f, "Nvidia Quadro FX 700"}, /* driver.c:309 */
    {0x10de, 0x341, "Nvidia Geforce FX 5700 Ultra"}, /* driver.c:310 */
    {0x10de, 0x342, "Nvidia Geforce FX 5700"}, /* driver.c:311 */
    {0x10de, 0x343, "Nvidia Geforce FX 5700LE"}, /* driver.c:312 */
    {0x10de, 0x344, "Nvidia Geforce FX 5700VE"}, /* driver.c:313 */
    {0x10de, 0x345, "Nvidia unknown FX"}, /* driver.c:314 */
    {0x10de, 0x347, "Nvidia Geforce FX 5700 Go"}, /* driver.c:315 */
    {0x10de, 0x348, "Nvidia Geforce FX 5700 Go"}, /* driver.c:316 */
    {0x10de, 0x349, "Nvidia unknown FX Go"}, /* driver.c:317 */
    {0x10de, 0x34b, "Nvidia unknown FX Go"}, /* driver.c:318 */
    {0x10de, 0x34c, "Nvidia Quadro FX 1000 Go"}, /* driver.c:319 */
    {0x10de, 0x34e, "Nvidia Quadro FX 1100"}, /* driver.c:320 */
    {0x10de, 0x34f, "Nvidia unknown FX"}, /* driver.c:321 */
    {0x10de, 0x391, "Nvidia Geforce 7600 GT"}, /* driver.c:322 */
    {0x10de, 0x392, "Nvidia Geforce 7600 GS"}, /* driver.c:323 */
    {0x10de, 0x393, "Nvidia Geforce 7300 GT"}, /* driver.c:324 */
    {0x10de, 0x394, "Nvidia Geforce 7600 LE"}, /* driver.c:325 */
    {0x10de, 0x398, "Nvidia Geforce 7600 GO"}, /* driver.c:326 */
    {0x10de, 0x3d0, "Nvidia Geforce 6100 nForce 430"}, /* driver.c:327 */
    {0x10de, 0x3d1, "Nvidia Geforce 6100 nForce 405"}, /* driver.c:328 */
    {0x10de, 0x3d2, "Nvidia Geforce 6100 nForce 400"}, /* driver.c:329 */
    {0x10de, 0x3d5, "Nvidia Geforce 6100 nForce 420"}, /* driver.c:330 */
    {0x10de, 0x3d6, "Nvidia Geforce 7025 / nForce 630a"}, /* driver.c:331 */
    {0x10de, 0x6e4, "Nvidia Geforce 8400 GS G98"}, /* driver.c:332 */
    {0x10de, 0x6e8, "Nvidia Geforce 9200M G98M"}, /* driver.c:333 */
    {0x10de, 0x7e1, "Nvidia Geforce 7100 / nForce 630i"}, /* driver.c:334 */
    {0x1048, 0xc60, "Elsa Gladiac Geforce2 MX"}, /* driver.c:339 */
    {0x12d2, 0x20, "Nvidia STB/SGS-Thompson TNT1"}, /* driver.c:344 */
    {0x12d2, 0x28, "Nvidia STB/SGS-Thompson TNT2 (pro)"}, /* driver.c:345 */
    {0x12d2, 0x29, "Nvidia STB/SGS-Thompson TNT2 Ultra"}, /* driver.c:346 */
    {0x12d2, 0x2a, "Nvidia STB/SGS-Thompson TNT2"}, /* driver.c:347 */
    {0x12d2, 0x2b, "Nvidia STB/SGS-Thompson TNT2"}, /* driver.c:348 */
    {0x12d2, 0x2c, "Nvidia STB/SGS-Thompson Vanta (Lt)"}, /* driver.c:349 */
    {0x12d2, 0x2d, "Nvidia STB/SGS-Thompson TNT2-M64 (Pro)"}, /* driver.c:350 */
    {0x12d2, 0x2e, "Nvidia STB/SGS-Thompson NV06 Vanta"}, /* driver.c:351 */
    {0x12d2, 0x2f, "Nvidia STB/SGS-Thompson NV06 Vanta"}, /* driver.c:352 */
    {0x12d2, 0xa0, "Nvidia STB/SGS-Thompson Aladdin TNT2"}, /* driver.c:353 */
    {0x1888, 0x3503, "Varisys Geforce4 MX440"}, /* driver.c:358 */
    {0x1888, 0x3505, "Varisys Geforce4 Ti 4200"}, /* driver.c:359 */
    /* Hand-authored by SCos, and the reason the count above is larger than the upstream family's:
     * the Blackwell display ids the in-tree registry named while nothing bound them.  A row here is a
     * matching rule that lets drivers/gpu/nvidia load for this chip and read NV_PMC_BOOT_0; it is not a
     * claim that anything can be drawn, which is what the capability record below and gpu_ports.c say. */
    {0x10DE, 0x2B85, "GB202 [GeForce RTX 5090]"},        /* Blackwell, identification only */
    {0x10DE, 0x2B87, "GB202 [GeForce RTX 5090 D]"},
    {0x10DE, 0x2B8C, "GB202 [GeForce RTX 5090 D V2]"},
    {0x10DE, 0x2C02, "GB203 [GeForce RTX 5080]"},
    {0x10DE, 0x2C05, "GB203 [GeForce RTX 5070 Ti]"},
    {0x10DE, 0x2C09, "GB203 [GeForce RTX 5070]"},
    {0x10DE, 0x2C18, "GB203M [GeForce RTX 5090 Max-Q / Mobile]"},
    {0x10DE, 0x2C19, "GB203M [GeForce RTX 5080 Max-Q / Mobile]"},
    {0x10DE, 0x2C58, "GB203M-X11 [GeForce RTX 5090 Max-Q / Mobile]"},
    {0x10DE, 0x2C59, "GB203M-X9 [GeForce RTX 5080 Max-Q / Mobile]"},
    {0x10DE, 0x2D04, "GB206 [GeForce RTX 5060 Ti]"},
    {0x10DE, 0x2D05, "GB206 [GeForce RTX 5060]"},
    {0x10DE, 0x2D18, "GB206M [GeForce RTX 5070 Max-Q / Mobile]"},
    {0x10DE, 0x2D19, "GB206M [GeForce RTX 5060 Max-Q / Mobile]"},
    {0x10DE, 0x2D83, "GB207 [GeForce RTX 5050]"},
    {0x10DE, 0x2D98, "GB207M [GeForce RTX 5050 Max-Q / Mobile]"},
    {0x10DE, 0x2F04, "GB205 [GeForce RTX 5070]"},
    {0x10DE, 0x2F06, "GB205 [GeForce RTX 5060]"},
    {0x10DE, 0x2F18, "GB205M [GeForce RTX 5070 Ti Mobile]"},
};

/* matrox: 9 device IDs bound by src/add-ons/kernel/drivers/graphics/matrox/driver.c; no class test upstream (vendor + device only). */
static const struct gpu_pci_id gpu_ids_matrox[] = {
    {0x102b, 0x2527, "G450AGP, G550AGP"}, /* driver.c:98 */
    {0x102b, 0x525, "G400AGP"}, /* driver.c:99 */
    {0x102b, 0x520, "G200PCI"}, /* driver.c:100 */
    {0x102b, 0x521, "G200AGP"}, /* driver.c:101 */
    {0x102b, 0x1000, "G100PCI"}, /* driver.c:102 */
    {0x102b, 0x1001, "G100AGP"}, /* driver.c:103 */
    {0x102b, 0x51b, "MGA-2164 PCI Millennium 2"}, /* driver.c:104 */
    {0x102b, 0x51f, "MGA-2164 AGP Millennium 2"}, /* driver.c:105 */
    {0x102b, 0x519, "MGA-2064 PCI Millennium 1"}, /* driver.c:106 */
};

/* via: 5 device IDs bound by src/add-ons/kernel/drivers/graphics/via/driver.c; no class test upstream (vendor + device only). */
static const struct gpu_pci_id gpu_ids_via[] = {
    {0x1106, 0x3022, "CLE266 Unichrome Pro (CLE3022)"}, /* driver.c:102 */
    {0x1106, 0x3108, "K8M800 Unichrome Pro (unknown chiptype)"}, /* driver.c:103 */
    {0x1106, 0x3122, "CLE266 Unichrome Pro (CLE3122)"}, /* driver.c:104 */
    {0x1106, 0x3205, "KM400 Unichrome (VT3205)"}, /* driver.c:105 */
    {0x1106, 0x7205, "KM400 Unichrome (VT7205)"}, /* driver.c:107 */
};

/* neomagic: 9 device IDs bound by src/add-ons/kernel/drivers/graphics/neomagic/driver.c; no class test upstream (vendor + device only). */
static const struct gpu_pci_id gpu_ids_neomagic[] = {
    {0x10c8, 0x1, "MagicGraph 128 (NM2070)"}, /* driver.c:106 */
    {0x10c8, 0x2, "MagicGraph 128V (NM2090) 0x42"}, /* driver.c:107 */
    {0x10c8, 0x3, "MagicGraph 128ZV (NM2093) 0x43"}, /* driver.c:108 */
    {0x10c8, 0x83, "MagicGraph 128ZV+ (NM2097)"}, /* driver.c:109 */
    {0x10c8, 0x4, "MagicGraph 128XD (NM2160) 0x44"}, /* driver.c:110 */
    {0x10c8, 0x5, "MagicMedia 256AV (NM2200) 0x45"}, /* driver.c:111 */
    {0x10c8, 0x25, "MagicMedia 256AV+ (NM2230)"}, /* driver.c:112 */
    {0x10c8, 0x6, "MagicMedia 256ZX (NM2360)"}, /* driver.c:113 */
    {0x10c8, 0x16, "MagicMedia 256XL+ (NM2380)"}, /* driver.c:114 */
};

/* et6x00: 2 device IDs bound by src/add-ons/kernel/drivers/graphics/et6x00/driver.c; no class test upstream (vendor + device only). */
static const struct gpu_pci_id gpu_ids_et6x00[] = {
    {0x100c, 0x3208, "ET6000/ET6100"}, /* driver.c:105 */
    {0x100c, 0x4702, "ET6300"}, /* driver.c:106 */
};

/* s3: 34 device IDs bound by src/add-ons/kernel/drivers/graphics/s3/driver.cpp; no class test upstream (vendor + device only). */
static const struct gpu_pci_id gpu_ids_s3[] = {
    {0x5333, 0x8811, "Trio64"}, /* driver.cpp:54 */
    {0x5333, 0x8814, "Trio64 UV+"}, /* driver.cpp:55 */
    {0x5333, 0x8901, "Trio64 V2/DX/GX"}, /* driver.cpp:56 */
    {0x5333, 0x5631, "Virge"}, /* driver.cpp:58 */
    {0x5333, 0x883d, "Virge VX"}, /* driver.cpp:59 */
    {0x5333, 0x8a01, "Virge DX/GX"}, /* driver.cpp:60 */
    {0x5333, 0x8a10, "Virge GX2"}, /* driver.cpp:61 */
    {0x5333, 0x8c01, "Virge MX"}, /* driver.cpp:62 */
    {0x5333, 0x8c03, "Virge MX+"}, /* driver.cpp:63 */
    {0x5333, 0x8904, "Trio 3D"}, /* driver.cpp:64 */
    {0x5333, 0x8a13, "Trio 3D/2X"}, /* driver.cpp:65 */
    {0x5333, 0x8a20, "Savage3D"}, /* driver.cpp:67 */
    {0x5333, 0x8a21, "Savage3D-MV"}, /* driver.cpp:68 */
    {0x5333, 0x8a22, "Savage4"}, /* driver.cpp:69 */
    {0x5333, 0x8a25, "ProSavage PM133"}, /* driver.cpp:70 */
    {0x5333, 0x8a26, "ProSavage KM133"}, /* driver.cpp:71 */
    {0x5333, 0x8c10, "Savage/MX-MV"}, /* driver.cpp:72 */
    {0x5333, 0x8c11, "Savage/MX"}, /* driver.cpp:73 */
    {0x5333, 0x8c12, "Savage/IX-MV"}, /* driver.cpp:74 */
    {0x5333, 0x8c13, "Savage/IX"}, /* driver.cpp:75 */
    {0x5333, 0x8c22, "SuperSavage/MX 128"}, /* driver.cpp:76 */
    {0x5333, 0x8c24, "SuperSavage/MX 64"}, /* driver.cpp:77 */
    {0x5333, 0x8c26, "SuperSavage/MX 64C"}, /* driver.cpp:78 */
    {0x5333, 0x8c2a, "SuperSavage/IX 128SDR"}, /* driver.cpp:79 */
    {0x5333, 0x8c2b, "SuperSavage/IX 128DDR"}, /* driver.cpp:80 */
    {0x5333, 0x8c2c, "SuperSavage/IX 64SDR"}, /* driver.cpp:81 */
    {0x5333, 0x8c2d, "SuperSavage/IX 64DDR"}, /* driver.cpp:82 */
    {0x5333, 0x8c2e, "SuperSavage/IXC 64SDR"}, /* driver.cpp:83 */
    {0x5333, 0x8c2f, "SuperSavage/IXC 64DDR"}, /* driver.cpp:84 */
    {0x5333, 0x8d01, "Twister PN133"}, /* driver.cpp:85 */
    {0x5333, 0x8d02, "Twister KN133"}, /* driver.cpp:86 */
    {0x5333, 0x8d03, "ProSavage DDR"}, /* driver.cpp:87 */
    {0x5333, 0x8d04, "ProSavage DDR-K"}, /* driver.cpp:88 */
    {0x5333, 0x9102, "Savage2000"}, /* driver.cpp:89 */
};

/* ati: 77 device IDs bound by src/add-ons/kernel/drivers/graphics/ati/driver.cpp; no class test upstream (vendor + device only). */
static const struct gpu_pci_id gpu_ids_ati[] = {
    {0x1002, 0x4742, "3D RAGE PRO, AGP"}, /* driver.cpp:74 */
    {0x1002, 0x4744, "3D RAGE PRO, AGP"}, /* driver.cpp:75 */
    {0x1002, 0x4749, "3D RAGE PRO, PCI"}, /* driver.cpp:76 */
    {0x1002, 0x474c, "3D RAGE XC, PCI"}, /* driver.cpp:77 */
    {0x1002, 0x474d, "3D RAGE XL, AGP"}, /* driver.cpp:78 */
    {0x1002, 0x474e, "3D RAGE XC, AGP"}, /* driver.cpp:79 */
    {0x1002, 0x474f, "3D RAGE XL, PCI"}, /* driver.cpp:80 */
    {0x1002, 0x4750, "3D RAGE PRO, PCI"}, /* driver.cpp:81 */
    {0x1002, 0x4751, "3D RAGE PRO, PCI"}, /* driver.cpp:82 */
    {0x1002, 0x4752, "3D RAGE XL, PCI"}, /* driver.cpp:83 */
    {0x1002, 0x4753, "3D RAGE XC, PCI"}, /* driver.cpp:84 */
    {0x1002, 0x4754, "3D RAGE II"}, /* driver.cpp:85 */
    {0x1002, 0x4755, "3D RAGE II+"}, /* driver.cpp:86 */
    {0x1002, 0x4756, "3D RAGE IIC, PCI"}, /* driver.cpp:87 */
    {0x1002, 0x4757, "3D RAGE IIC, AGP"}, /* driver.cpp:88 */
    {0x1002, 0x4759, "3D RAGE IIC, PCI"}, /* driver.cpp:89 */
    {0x1002, 0x475a, "3D RAGE IIC, AGP"}, /* driver.cpp:90 */
    {0x1002, 0x4c42, "3D RAGE LT PRO, AGP"}, /* driver.cpp:91 */
    {0x1002, 0x4c44, "3D RAGE LT PRO, AGP"}, /* driver.cpp:92 */
    {0x1002, 0x4c47, "3D RAGE LT"}, /* driver.cpp:93 */
    {0x1002, 0x4c49, "3D RAGE LT PRO, PCI"}, /* driver.cpp:94 */
    {0x1002, 0x4c4d, "3D RAGE Mobility, AGP"}, /* driver.cpp:95 */
    {0x1002, 0x4c4e, "3D RAGE Mobility, AGP"}, /* driver.cpp:96 */
    {0x1002, 0x4c50, "3D RAGE LT PRO, PCI"}, /* driver.cpp:97 */
    {0x1002, 0x4c51, "3D RAGE LT PRO, PCI"}, /* driver.cpp:98 */
    {0x1002, 0x4c52, "3D RAGE Mobility, PCI"}, /* driver.cpp:99 */
    {0x1002, 0x4c53, "3D RAGE Mobility, PCI"}, /* driver.cpp:100 */
    {0x1002, 0x5654, "264VT2"}, /* driver.cpp:101 */
    {0x1002, 0x5655, "264VT3"}, /* driver.cpp:102 */
    {0x1002, 0x5656, "264VT4"}, /* driver.cpp:103 */
    {0x1002, 0x4c45, "RAGE 128 Mobility 3"}, /* driver.cpp:105 */
    {0x1002, 0x4c46, "RAGE 128 Mobility 3"}, /* driver.cpp:106 */
    {0x1002, 0x4d46, "RAGE 128 Mobility 4"}, /* driver.cpp:107 */
    {0x1002, 0x4d4c, "RAGE 128 Mobility 4"}, /* driver.cpp:108 */
    {0x1002, 0x5041, "RAGE 128 PRO GL"}, /* driver.cpp:109 */
    {0x1002, 0x5042, "RAGE 128 PRO GL"}, /* driver.cpp:110 */
    {0x1002, 0x5043, "RAGE 128 PRO GL"}, /* driver.cpp:111 */
    {0x1002, 0x5044, "RAGE 128 PRO GL"}, /* driver.cpp:112 */
    {0x1002, 0x5045, "RAGE 128 PRO GL"}, /* driver.cpp:113 */
    {0x1002, 0x5046, "RAGE 128 PRO GL"}, /* driver.cpp:114 */
    {0x1002, 0x5047, "RAGE 128 PRO VR"}, /* driver.cpp:115 */
    {0x1002, 0x5048, "RAGE 128 PRO VR"}, /* driver.cpp:116 */
    {0x1002, 0x5049, "RAGE 128 PRO VR"}, /* driver.cpp:117 */
    {0x1002, 0x504a, "RAGE 128 PRO VR"}, /* driver.cpp:118 */
    {0x1002, 0x504b, "RAGE 128 PRO VR"}, /* driver.cpp:119 */
    {0x1002, 0x504c, "RAGE 128 PRO VR"}, /* driver.cpp:120 */
    {0x1002, 0x504d, "RAGE 128 PRO VR"}, /* driver.cpp:121 */
    {0x1002, 0x504e, "RAGE 128 PRO VR"}, /* driver.cpp:122 */
    {0x1002, 0x504f, "RAGE 128 PRO VR"}, /* driver.cpp:123 */
    {0x1002, 0x5050, "RAGE 128 PRO VR"}, /* driver.cpp:124 */
    {0x1002, 0x5051, "RAGE 128 PRO VR"}, /* driver.cpp:125 */
    {0x1002, 0x5052, "RAGE 128 PRO VR"}, /* driver.cpp:126 */
    {0x1002, 0x5053, "RAGE 128 PRO VR"}, /* driver.cpp:127 */
    {0x1002, 0x5054, "RAGE 128 PRO VR"}, /* driver.cpp:128 */
    {0x1002, 0x5055, "RAGE 128 PRO VR"}, /* driver.cpp:129 */
    {0x1002, 0x5056, "RAGE 128 PRO VR"}, /* driver.cpp:130 */
    {0x1002, 0x5057, "RAGE 128 PRO VR"}, /* driver.cpp:131 */
    {0x1002, 0x5058, "RAGE 128 PRO VR"}, /* driver.cpp:132 */
    {0x1002, 0x5245, "RAGE 128 GL"}, /* driver.cpp:133 */
    {0x1002, 0x5246, "RAGE 128 GL"}, /* driver.cpp:134 */
    {0x1002, 0x5247, "RAGE 128 GL"}, /* driver.cpp:135 */
    {0x1002, 0x524b, "RAGE 128 VR"}, /* driver.cpp:136 */
    {0x1002, 0x524c, "RAGE 128 VR"}, /* driver.cpp:137 */
    {0x1002, 0x5345, "RAGE 128 VR"}, /* driver.cpp:138 */
    {0x1002, 0x5346, "RAGE 128 VR"}, /* driver.cpp:139 */
    {0x1002, 0x5347, "RAGE 128 VR"}, /* driver.cpp:140 */
    {0x1002, 0x5348, "RAGE 128 VR"}, /* driver.cpp:141 */
    {0x1002, 0x534b, "RAGE 128 GL"}, /* driver.cpp:142 */
    {0x1002, 0x534c, "RAGE 128 GL"}, /* driver.cpp:143 */
    {0x1002, 0x534d, "RAGE 128 GL"}, /* driver.cpp:144 */
    {0x1002, 0x534e, "RAGE 128 GL"}, /* driver.cpp:145 */
    {0x1002, 0x5446, "RAGE 128 PRO Ultra"}, /* driver.cpp:146 */
    {0x1002, 0x544c, "RAGE 128 PRO Ultra"}, /* driver.cpp:147 */
    {0x1002, 0x5452, "RAGE 128 PRO Ultra"}, /* driver.cpp:148 */
    {0x1002, 0x5453, "RAGE 128 PRO Ultra"}, /* driver.cpp:149 */
    {0x1002, 0x5454, "RAGE 128 PRO Ultra"}, /* driver.cpp:150 */
    {0x1002, 0x5455, "RAGE 128 PRO Ultra"}, /* driver.cpp:151 */
};

/* 3dfx: 3 device IDs bound by src/add-ons/kernel/drivers/graphics/3dfx/driver.cpp; no class test upstream (vendor + device only). */
static const struct gpu_pci_id gpu_ids_3dfx[] = {
    {0x121a, 0x3, "Banshee"}, /* driver.cpp:55 */
    {0x121a, 0x5, "Voodoo 3"}, /* driver.cpp:56 */
    {0x121a, 0x9, "Voodoo 5"}, /* driver.cpp:57 */
};

/* intel_810: 4 device IDs bound by src/add-ons/kernel/drivers/graphics/intel_810/driver.cpp; no class test upstream (vendor + device only). */
static const struct gpu_pci_id gpu_ids_intel_810[] = {
    {0x8086, 0x7121, "i810"}, /* driver.cpp:51 */
    {0x8086, 0x7123, "i810-dc100"}, /* driver.cpp:52 */
    {0x8086, 0x7125, "i810e"}, /* driver.cpp:53 */
    {0x8086, 0x1132, "i815"}, /* driver.cpp:54 */
};

/* intel_extreme: 143 device IDs bound by src/add-ons/kernel/drivers/graphics/intel_extreme/driver.cpp; class 0x03 sub 0x00 or 0x80. */
static const struct gpu_pci_id gpu_ids_intel_extreme[] = {
    {0x8086, 0x3577, "i830GM"}, /* driver.cpp:45 */
    {0x8086, 0x2562, "i845G"}, /* driver.cpp:46 */
    {0x8086, 0x2572, "i865G"}, /* driver.cpp:48 */
    {0x8086, 0x3582, "i855G"}, /* driver.cpp:49 */
    {0x8086, 0x358e, "i855G"}, /* driver.cpp:50 */
    {0x8086, 0x2582, "i915G"}, /* driver.cpp:52 */
    {0x8086, 0x258a, "i915"}, /* driver.cpp:53 */
    {0x8086, 0x2592, "i915GM"}, /* driver.cpp:54 */
    {0x8086, 0x2792, "i910"}, /* driver.cpp:55 */
    {0x8086, 0x2772, "i945G"}, /* driver.cpp:56 */
    {0x8086, 0x27a2, "i945GM"}, /* driver.cpp:57 */
    {0x8086, 0x27ae, "i945GME"}, /* driver.cpp:58 */
    {0x8086, 0x2972, "i946G"}, /* driver.cpp:59 */
    {0x8086, 0x2982, "G35"}, /* driver.cpp:60 */
    {0x8086, 0x2992, "i965Q"}, /* driver.cpp:61 */
    {0x8086, 0x29a2, "i965G"}, /* driver.cpp:62 */
    {0x8086, 0x2a02, "i965GM"}, /* driver.cpp:63 */
    {0x8086, 0x2a12, "i965GME"}, /* driver.cpp:64 */
    {0x8086, 0x29b2, "G33G"}, /* driver.cpp:65 */
    {0x8086, 0x29c2, "Q35G"}, /* driver.cpp:66 */
    {0x8086, 0x29d2, "Q33G"}, /* driver.cpp:67 */
    {0x8086, 0x2a42, "GM45"}, /* driver.cpp:69 */
    {0x8086, 0x2e02, "IGD"}, /* driver.cpp:70 */
    {0x8086, 0x2e12, "Q45"}, /* driver.cpp:71 */
    {0x8086, 0x2e22, "G45"}, /* driver.cpp:72 */
    {0x8086, 0x2e32, "G41"}, /* driver.cpp:73 */
    {0x8086, 0x2e42, "B43"}, /* driver.cpp:74 */
    {0x8086, 0x2e92, "B43"}, /* driver.cpp:75 */
    {0x8086, 0xa001, "Atom D4xx"}, /* driver.cpp:77 */
    {0x8086, 0xa002, "Atom D5xx"}, /* driver.cpp:78 */
    {0x8086, 0xa011, "Atom N4xx"}, /* driver.cpp:79 */
    {0x8086, 0xa012, "Atom N5xx"}, /* driver.cpp:80 */
    {0x8086, 0x42, "IronLake Desktop"}, /* driver.cpp:82 */
    {0x8086, 0x46, "IronLake Mobile"}, /* driver.cpp:83 */
    {0x8086, 0x102, "SandyBridge Desktop GT1"}, /* driver.cpp:87 */
    {0x8086, 0x112, "SandyBridge Desktop GT2"}, /* driver.cpp:88 */
    {0x8086, 0x122, "SandyBridge Desktop GT2+"}, /* driver.cpp:89 */
    {0x8086, 0x106, "SandyBridge Mobile GT1"}, /* driver.cpp:90 */
    {0x8086, 0x116, "SandyBridge Mobile GT2"}, /* driver.cpp:91 */
    {0x8086, 0x126, "SandyBridge Mobile GT2+"}, /* driver.cpp:92 */
    {0x8086, 0x10a, "SandyBridge Server"}, /* driver.cpp:93 */
    {0x8086, 0x152, "IvyBridge Desktop GT1"}, /* driver.cpp:95 */
    {0x8086, 0x162, "IvyBridge Desktop GT2"}, /* driver.cpp:96 */
    {0x8086, 0x156, "IvyBridge Mobile GT1"}, /* driver.cpp:97 */
    {0x8086, 0x166, "IvyBridge Mobile GT2"}, /* driver.cpp:98 */
    {0x8086, 0x15a, "IvyBridge Server GT1"}, /* driver.cpp:100 */
    {0x8086, 0x16a, "IvyBridge Server GT2"}, /* driver.cpp:101 */
    {0x8086, 0xa06, "Haswell ULT GT1 Mobile"}, /* driver.cpp:103 */
    {0x8086, 0x412, "Haswell GT2 Desktop"}, /* driver.cpp:104 */
    {0x8086, 0x416, "Haswell GT2 Mobile"}, /* driver.cpp:105 */
    {0x8086, 0xa16, "Haswell ULT GT2 Mobile"}, /* driver.cpp:106 */
    {0x8086, 0xa2e, "Haswell ULT GT3 Mobile"}, /* driver.cpp:107 */
    {0x8086, 0xd26, "Haswell CRW GT3 Mobile"}, /* driver.cpp:108 */
    {0x8086, 0x1606, "Broadwell GT1 ULT"}, /* driver.cpp:111 */
    {0x8086, 0x160b, "Broadwell GT1 Iris"}, /* driver.cpp:112 */
    {0x8086, 0x160e, "Broadwell GT1 ULX"}, /* driver.cpp:113 */
    {0x8086, 0x1602, "Broadwell GT1 ULT"}, /* driver.cpp:114 */
    {0x8086, 0x160a, "Broadwell GT1 Server"}, /* driver.cpp:115 */
    {0x8086, 0x160d, "Broadwell GT1 Workstation"}, /* driver.cpp:116 */
    {0x8086, 0x1616, "Broadwell GT2 ULT"}, /* driver.cpp:117 */
    {0x8086, 0x161b, "Broadwell GT2 ULT"}, /* driver.cpp:118 */
    {0x8086, 0x161e, "Broadwell GT2 ULX"}, /* driver.cpp:119 */
    {0x8086, 0x1612, "Broadwell GT2 Halo"}, /* driver.cpp:120 */
    {0x8086, 0x161a, "Broadwell GT2 Server"}, /* driver.cpp:121 */
    {0x8086, 0x161d, "Broadwell GT2 Workstation"}, /* driver.cpp:122 */
    {0x8086, 0x1626, "Broadwell GT3 ULT"}, /* driver.cpp:123 */
    {0x8086, 0x162b, "Broadwell GT3 Iris"}, /* driver.cpp:124 */
    {0x8086, 0x162e, "Broadwell GT3 ULX"}, /* driver.cpp:125 */
    {0x8086, 0x1622, "Broadwell GT3 ULT"}, /* driver.cpp:126 */
    {0x8086, 0x162a, "Broadwell GT3 Server"}, /* driver.cpp:127 */
    {0x8086, 0x162d, "Broadwell GT3 Workstation"}, /* driver.cpp:128 */
    {0x8086, 0x1902, "Skylake GT1"}, /* driver.cpp:130 */
    {0x8086, 0x1906, "Skylake GT1"}, /* driver.cpp:131 */
    {0x8086, 0x190a, "Skylake GT1"}, /* driver.cpp:132 */
    {0x8086, 0x190b, "Skylake GT1"}, /* driver.cpp:133 */
    {0x8086, 0x190e, "Skylake GT1"}, /* driver.cpp:134 */
    {0x8086, 0x1912, "Skylake GT2"}, /* driver.cpp:135 */
    {0x8086, 0x1916, "Skylake GT2"}, /* driver.cpp:136 */
    {0x8086, 0x191a, "Skylake GT2"}, /* driver.cpp:137 */
    {0x8086, 0x191b, "Skylake GT2"}, /* driver.cpp:138 */
    {0x8086, 0x191d, "Skylake GT2"}, /* driver.cpp:139 */
    {0x8086, 0x191e, "Skylake GT2"}, /* driver.cpp:140 */
    {0x8086, 0x1921, "Skylake GT2F"}, /* driver.cpp:141 */
    {0x8086, 0x1926, "Skylake GT3"}, /* driver.cpp:142 */
    {0x8086, 0x192a, "Skylake GT3"}, /* driver.cpp:143 */
    {0x8086, 0x192b, "Skylake GT3"}, /* driver.cpp:144 */
    {0x8086, 0x5a84, "Apollo Lake GT1.5"}, /* driver.cpp:146 */
    {0x8086, 0x5a85, "Apollo Lake GT1"}, /* driver.cpp:147 */
    {0x8086, 0x5906, "Kabylake ULT GT1"}, /* driver.cpp:149 */
    {0x8086, 0x5902, "Kabylake DT GT1"}, /* driver.cpp:150 */
    {0x8086, 0x5916, "Kabylake ULT GT2"}, /* driver.cpp:151 */
    {0x8086, 0x5921, "Kabylake ULT GT2F"}, /* driver.cpp:152 */
    {0x8086, 0x591c, "Kabylake ULX GT2"}, /* driver.cpp:153 */
    {0x8086, 0x591e, "Kabylake ULX GT2"}, /* driver.cpp:154 */
    {0x8086, 0x5912, "Kabylake DT GT2"}, /* driver.cpp:155 */
    {0x8086, 0x5917, "Kabylake Mobile GT2"}, /* driver.cpp:156 */
    {0x8086, 0x591b, "Kabylake Halo GT2"}, /* driver.cpp:157 */
    {0x8086, 0x591d, "Kabylake WKS GT2"}, /* driver.cpp:158 */
    {0x8086, 0x5926, "Kabylake ULT GT3"}, /* driver.cpp:159 */
    {0x8086, 0x5927, "Kabylake ULT GT3"}, /* driver.cpp:160 */
    {0x8086, 0x3185, "GeminiLake GT1"}, /* driver.cpp:162 */
    {0x8086, 0x3184, "GeminiLake GT1.5"}, /* driver.cpp:163 */
    {0x8086, 0x3e90, "CoffeeLake GT1"}, /* driver.cpp:165 */
    {0x8086, 0x3e93, "CoffeeLake GT1"}, /* driver.cpp:166 */
    {0x8086, 0x3e91, "CoffeeLake GT2"}, /* driver.cpp:167 */
    {0x8086, 0x3e92, "CoffeeLake GT2"}, /* driver.cpp:168 */
    {0x8086, 0x3e96, "CoffeeLake GT2"}, /* driver.cpp:169 */
    {0x8086, 0x3e98, "CoffeeLake GT2"}, /* driver.cpp:170 */
    {0x8086, 0x3e9a, "CoffeeLake GT2"}, /* driver.cpp:171 */
    {0x8086, 0x3e9b, "CoffeeLake Halo GT2"}, /* driver.cpp:172 */
    {0x8086, 0x3eab, "CoffeeLake Halo GT2"}, /* driver.cpp:173 */
    {0x8086, 0x3ea5, "CoffeeLake GT3"}, /* driver.cpp:174 */
    {0x8086, 0x3ea6, "CoffeeLake GT3"}, /* driver.cpp:175 */
    {0x8086, 0x8a56, "IceLake GT1"}, /* driver.cpp:177 */
    {0x8086, 0x8a5c, "IceLake GT1.5"}, /* driver.cpp:178 */
    {0x8086, 0x8a5a, "IceLake GT1.5"}, /* driver.cpp:179 */
    {0x8086, 0x8a51, "IceLake GT2"}, /* driver.cpp:180 */
    {0x8086, 0x8a52, "IceLake GT2"}, /* driver.cpp:181 */
    {0x8086, 0x8a53, "IceLake GT2"}, /* driver.cpp:182 */
    {0x8086, 0x9ba4, "CometLake GT1"}, /* driver.cpp:184 */
    {0x8086, 0x9ba8, "CometLake GT1"}, /* driver.cpp:185 */
    {0x8086, 0x9b21, "CometLake U GT1"}, /* driver.cpp:186 */
    {0x8086, 0x9baa, "CometLake U GT1"}, /* driver.cpp:187 */
    {0x8086, 0x9bc4, "CometLake GT2"}, /* driver.cpp:188 */
    {0x8086, 0x9bc5, "CometLake GT2"}, /* driver.cpp:189 */
    {0x8086, 0x9bc6, "CometLake GT2"}, /* driver.cpp:190 */
    {0x8086, 0x9bc8, "CometLake GT2"}, /* driver.cpp:191 */
    {0x8086, 0x9be6, "CometLake GT2"}, /* driver.cpp:192 */
    {0x8086, 0x9bf6, "CometLake GT2"}, /* driver.cpp:193 */
    {0x8086, 0x9b41, "CometLake U GT2"}, /* driver.cpp:194 */
    {0x8086, 0x9bca, "CometLake U GT2"}, /* driver.cpp:195 */
    {0x8086, 0x9bcc, "CometLake U GT2"}, /* driver.cpp:196 */
    {0x8086, 0x4e55, "JasperLake"}, /* driver.cpp:198 */
    {0x8086, 0x4e61, "JasperLake"}, /* driver.cpp:199 */
    {0x8086, 0x4e71, "JasperLake"}, /* driver.cpp:200 */
    {0x8086, 0x9a49, "TigerLake"}, /* driver.cpp:202 */
    {0x8086, 0x9a78, "TigerLake"}, /* driver.cpp:203 */
    {0x8086, 0x9a40, "TigerLake"}, /* driver.cpp:204 */
    {0x8086, 0x9a60, "TigerLake"}, /* driver.cpp:205 */
    {0x8086, 0x9a68, "TigerLake"}, /* driver.cpp:206 */
    {0x8086, 0x9a70, "TigerLake"}, /* driver.cpp:207 */
    {0x8086, 0x46a6, "Alder Lake-P GT2"}, /* driver.cpp:209 */
    {0x8086, 0x46d1, "Alder Lake-N"}, /* driver.cpp:210 */
};

/* radeon_hd: 340 device IDs bound by src/add-ons/kernel/drivers/graphics/radeon_hd/driver.cpp; class 0x03 sub 0x00 only. */
static const struct gpu_pci_id gpu_ids_radeon_hd[] = {
    {0x1002, 0x94c7, "Radeon HD 2350"}, /* driver.cpp:64 */
    {0x1002, 0x94c1, "Radeon HD 2400"}, /* driver.cpp:65 */
    {0x1002, 0x94c3, "Radeon HD 2400"}, /* driver.cpp:66 */
    {0x1002, 0x94c9, "Mobility Radeon HD 2400"}, /* driver.cpp:67 */
    {0x1002, 0x94cc, "Radeon HD 2400"}, /* driver.cpp:68 */
    {0x1002, 0x9519, "AMD FireStream 9170"}, /* driver.cpp:69 */
    {0x1002, 0x9586, "Radeon HD 2600"}, /* driver.cpp:70 */
    {0x1002, 0x9588, "Radeon HD 2600"}, /* driver.cpp:71 */
    {0x1002, 0x958a, "Radeon HD 2600 X2"}, /* driver.cpp:72 */
    {0x1002, 0x9400, "Radeon HD 2900"}, /* driver.cpp:74 */
    {0x1002, 0x9401, "Radeon HD 2900"}, /* driver.cpp:75 */
    {0x1002, 0x9402, "Radeon HD 2900"}, /* driver.cpp:76 */
    {0x1002, 0x9403, "Radeon HD 2900 Pro"}, /* driver.cpp:77 */
    {0x1002, 0x9405, "Radeon HD 2900"}, /* driver.cpp:78 */
    {0x1002, 0x940a, "Radeon FireGL V8650"}, /* driver.cpp:79 */
    {0x1002, 0x940b, "Radeon FireGL V8600"}, /* driver.cpp:80 */
    {0x1002, 0x940f, "Radeon FireGL V7600"}, /* driver.cpp:81 */
    {0x1002, 0x9616, "Radeon HD 3000"}, /* driver.cpp:82 */
    {0x1002, 0x9611, "Radeon HD 3100"}, /* driver.cpp:83 */
    {0x1002, 0x9613, "Radeon HD 3100"}, /* driver.cpp:84 */
    {0x1002, 0x9610, "Radeon HD 3200"}, /* driver.cpp:85 */
    {0x1002, 0x9612, "Radeon HD 3200"}, /* driver.cpp:86 */
    {0x1002, 0x9615, "Radeon HD 3200"}, /* driver.cpp:87 */
    {0x1002, 0x9614, "Radeon HD 3300"}, /* driver.cpp:88 */
    {0x1002, 0x95c2, "Radeon HD 3430"}, /* driver.cpp:90 */
    {0x1002, 0x95c5, "Radeon HD 3450"}, /* driver.cpp:91 */
    {0x1002, 0x95c6, "Radeon HD 3450"}, /* driver.cpp:92 */
    {0x1002, 0x95c7, "Radeon HD 3450"}, /* driver.cpp:93 */
    {0x1002, 0x95c9, "Radeon HD 3450"}, /* driver.cpp:94 */
    {0x1002, 0x95c4, "Radeon HD 3470"}, /* driver.cpp:95 */
    {0x1002, 0x95c0, "Radeon HD 3550"}, /* driver.cpp:96 */
    {0x1002, 0x9581, "Radeon HD 3600"}, /* driver.cpp:97 */
    {0x1002, 0x9583, "Radeon HD 3600"}, /* driver.cpp:98 */
    {0x1002, 0x9598, "Radeon HD 3600"}, /* driver.cpp:99 */
    {0x1002, 0x9591, "Radeon HD 3600"}, /* driver.cpp:100 */
    {0x1002, 0x9589, "Radeon HD 3610"}, /* driver.cpp:101 */
    {0x1002, 0x9507, "Radeon HD 3830"}, /* driver.cpp:104 */
    {0x1002, 0x9505, "Radeon HD 3850"}, /* driver.cpp:105 */
    {0x1002, 0x9513, "Radeon HD 3850 X2"}, /* driver.cpp:106 */
    {0x1002, 0x9515, "Radeon HD 3850"}, /* driver.cpp:107 */
    {0x1002, 0x9501, "Radeon HD 3870"}, /* driver.cpp:108 */
    {0x1002, 0x950f, "Radeon HD 3870 X2"}, /* driver.cpp:109 */
    {0x1002, 0x9710, "Radeon HD 4200"}, /* driver.cpp:110 */
    {0x1002, 0x9715, "Radeon HD 4250"}, /* driver.cpp:111 */
    {0x1002, 0x9712, "Radeon HD 4270"}, /* driver.cpp:112 */
    {0x1002, 0x9714, "Radeon HD 4290"}, /* driver.cpp:113 */
    {0x1002, 0x954f, "Radeon HD 4300"}, /* driver.cpp:120 */
    {0x1002, 0x9552, "Radeon HD 4300"}, /* driver.cpp:121 */
    {0x1002, 0x9553, "Radeon HD 4500"}, /* driver.cpp:122 */
    {0x1002, 0x9555, "Radeon HD 4350"}, /* driver.cpp:123 */
    {0x1002, 0x9540, "Radeon HD 4550"}, /* driver.cpp:124 */
    {0x1002, 0x9452, "AMD FireStream 9250"}, /* driver.cpp:125 */
    {0x1002, 0x9480, "Radeon HD 4650"}, /* driver.cpp:126 */
    {0x1002, 0x9488, "Radeon HD 4650"}, /* driver.cpp:127 */
    {0x1002, 0x9498, "Radeon HD 4650"}, /* driver.cpp:128 */
    {0x1002, 0x94b4, "Radeon HD 4700"}, /* driver.cpp:129 */
    {0x1002, 0x9490, "Radeon HD 4710"}, /* driver.cpp:130 */
    {0x1002, 0x94b3, "Radeon HD 4770"}, /* driver.cpp:131 */
    {0x1002, 0x94b5, "Radeon HD 4770"}, /* driver.cpp:132 */
    {0x1002, 0x9450, "AMD FireStream 9270"}, /* driver.cpp:133 */
    {0x1002, 0x944a, "Radeon HD 4850"}, /* driver.cpp:134 */
    {0x1002, 0x944e, "Radeon HD 4810"}, /* driver.cpp:135 */
    {0x1002, 0x944c, "Radeon HD 4830"}, /* driver.cpp:136 */
    {0x1002, 0x9442, "Radeon HD 4850"}, /* driver.cpp:137 */
    {0x1002, 0x9443, "Radeon HD 4850 X2"}, /* driver.cpp:138 */
    {0x1002, 0x94a1, "Radeon HD 4860"}, /* driver.cpp:139 */
    {0x1002, 0x9440, "Radeon HD 4870"}, /* driver.cpp:140 */
    {0x1002, 0x9441, "Radeon HD 4870 X2"}, /* driver.cpp:141 */
    {0x1002, 0x9460, "Radeon HD 4890"}, /* driver.cpp:142 */
    {0x1002, 0x68e1, "Radeon HD 5430"}, /* driver.cpp:152 */
    {0x1002, 0x68f9, "Radeon HD 5450"}, /* driver.cpp:153 */
    {0x1002, 0x68e0, "Radeon HD 5470"}, /* driver.cpp:154 */
    {0x1002, 0x68e4, "Radeon HD 6370"}, /* driver.cpp:155 */
    {0x1002, 0x68da, "Radeon HD 5500"}, /* driver.cpp:157 */
    {0x1002, 0x68d9, "Radeon HD 5570"}, /* driver.cpp:158 */
    {0x1002, 0x675f, "Radeon HD 5570"}, /* driver.cpp:159 */
    {0x1002, 0x68b9, "Radeon HD 5600"}, /* driver.cpp:160 */
    {0x1002, 0x68c1, "Radeon HD 5650"}, /* driver.cpp:161 */
    {0x1002, 0x68c8, "FirePro V4800"}, /* driver.cpp:162 */
    {0x1002, 0x68d8, "Radeon HD 5670"}, /* driver.cpp:163 */
    {0x1002, 0x68be, "Radeon HD 5700"}, /* driver.cpp:165 */
    {0x1002, 0x68b8, "Radeon HD 5770"}, /* driver.cpp:166 */
    {0x1002, 0x68ba, "Radeon HD 6770"}, /* driver.cpp:168 */
    {0x1002, 0x689e, "Radeon HD 5800"}, /* driver.cpp:170 */
    {0x1002, 0x6899, "Radeon HD 5850"}, /* driver.cpp:171 */
    {0x1002, 0x6898, "Radeon HD 5870"}, /* driver.cpp:172 */
    {0x1002, 0x689c, "Radeon HD 5900 X2"}, /* driver.cpp:174 */
    {0x1002, 0x689d, "Radeon HD 5900 X2"}, /* driver.cpp:175 */
    {0x1002, 0x9804, "Radeon HD 6250"}, /* driver.cpp:178 */
    {0x1002, 0x9805, "Radeon HD 6290"}, /* driver.cpp:179 */
    {0x1002, 0x9807, "Radeon HD 6290"}, /* driver.cpp:180 */
    {0x1002, 0x9802, "Radeon HD 6310"}, /* driver.cpp:181 */
    {0x1002, 0x9803, "Radeon HD 6310"}, /* driver.cpp:182 */
    {0x1002, 0x9806, "Radeon HD 6320"}, /* driver.cpp:183 */
    {0x1002, 0x9808, "Radeon HD 7340"}, /* driver.cpp:184 */
    {0x1002, 0x9640, "Radeon HD 6550D"}, /* driver.cpp:186 */
    {0x1002, 0x9641, "Radeon HD Sumo"}, /* driver.cpp:187 */
    {0x1002, 0x964a, "Radeon HD 6530D"}, /* driver.cpp:188 */
    {0x1002, 0x964e, "Radeon HD Sumo"}, /* driver.cpp:189 */
    {0x1002, 0x964f, "Radeon HD Sumo"}, /* driver.cpp:190 */
    {0x1002, 0x9642, "Radeon HD 6370D"}, /* driver.cpp:192 */
    {0x1002, 0x9643, "Radeon HD Sumo2"}, /* driver.cpp:193 */
    {0x1002, 0x9644, "Radeon HD 6410D"}, /* driver.cpp:194 */
    {0x1002, 0x9645, "Radeon HD Sumo2"}, /* driver.cpp:195 */
    {0x1002, 0x6761, "Radeon HD 6430"}, /* driver.cpp:201 */
    {0x1002, 0x6762, "Radeon HD Caicos"}, /* driver.cpp:202 */
    {0x1002, 0x6763, "Radeon HD E6460"}, /* driver.cpp:203 */
    {0x1002, 0x6764, "Radeon HD Caicos"}, /* driver.cpp:204 */
    {0x1002, 0x6765, "Radeon HD Caicos"}, /* driver.cpp:205 */
    {0x1002, 0x6766, "Radeon HD Caicos"}, /* driver.cpp:206 */
    {0x1002, 0x6767, "Radeon HD Caicos"}, /* driver.cpp:207 */
    {0x1002, 0x6768, "Radeon HD Caicos"}, /* driver.cpp:208 */
    {0x1002, 0x6770, "Radeon HD 6400"}, /* driver.cpp:209 */
    {0x1002, 0x6778, "Radeon HD 7470/8470"}, /* driver.cpp:210 */
    {0x1002, 0x6779, "Radeon HD 6450/7450/8450"}, /* driver.cpp:211 */
    {0x1002, 0x68fa, "Radeon HD 7350"}, /* driver.cpp:212 */
    {0x1002, 0x677b, "Radeon HD 7400"}, /* driver.cpp:213 */
    {0x1002, 0x6772, "Radeon HD 7400A"}, /* driver.cpp:214 */
    {0x1002, 0x6771, "Radeon HD 8490"}, /* driver.cpp:215 */
    {0x1002, 0x6740, "Radeon HD 6770M"}, /* driver.cpp:217 */
    {0x1002, 0x6741, "Radeon HD 6650M"}, /* driver.cpp:218 */
    {0x1002, 0x6742, "Radeon HD 6625M"}, /* driver.cpp:219 */
    {0x1002, 0x6743, "Radeon HD E6760"}, /* driver.cpp:220 */
    {0x1002, 0x6744, "Radeon HD Turks"}, /* driver.cpp:221 */
    {0x1002, 0x6745, "Radeon HD Turks"}, /* driver.cpp:222 */
    {0x1002, 0x6746, "FirePro V???? (turks)"}, /* driver.cpp:223 */
    {0x1002, 0x6747, "FirePro V???? (turks)"}, /* driver.cpp:224 */
    {0x1002, 0x6748, "FirePro V???? (turks)"}, /* driver.cpp:225 */
    {0x1002, 0x6749, "FirePro V4900"}, /* driver.cpp:226 */
    {0x1002, 0x6750, "Radeon HD 6500"}, /* driver.cpp:227 */
    {0x1002, 0x6758, "Radeon HD 6670"}, /* driver.cpp:228 */
    {0x1002, 0x6759, "Radeon HD 6570/7570"}, /* driver.cpp:229 */
    {0x1002, 0x675d, "Radeon HD 7570"}, /* driver.cpp:230 */
    {0x1002, 0x6850, "Radeon HD 7570"}, /* driver.cpp:231 */
    {0x1002, 0x673e, "Radeon HD 6790"}, /* driver.cpp:233 */
    {0x1002, 0x6738, "Radeon HD 6870"}, /* driver.cpp:234 */
    {0x1002, 0x6700, "Radeon HD Cayman"}, /* driver.cpp:236 */
    {0x1002, 0x6701, "Radeon HD Cayman"}, /* driver.cpp:237 */
    {0x1002, 0x6702, "Radeon HD Cayman"}, /* driver.cpp:238 */
    {0x1002, 0x6703, "Radeon HD Cayman"}, /* driver.cpp:239 */
    {0x1002, 0x6704, "FirePro V7900"}, /* driver.cpp:240 */
    {0x1002, 0x6705, "Radeon HD Cayman"}, /* driver.cpp:241 */
    {0x1002, 0x6706, "FirePro V???? (cayman)"}, /* driver.cpp:242 */
    {0x1002, 0x6707, "Radeon HD Cayman"}, /* driver.cpp:243 */
    {0x1002, 0x6708, "Radeon HD Cayman"}, /* driver.cpp:244 */
    {0x1002, 0x6709, "Radeon HD Cayman"}, /* driver.cpp:245 */
    {0x1002, 0x6718, "Radeon HD 6970"}, /* driver.cpp:246 */
    {0x1002, 0x6719, "Radeon HD 6950"}, /* driver.cpp:247 */
    {0x1002, 0x671c, "Radeon HD Cayman"}, /* driver.cpp:248 */
    {0x1002, 0x671f, "Radeon HD 6900"}, /* driver.cpp:249 */
    {0x1002, 0x671d, "Radeon HD 6990"}, /* driver.cpp:251 */
    {0x1002, 0x6820, "Radeon HD Verde"}, /* driver.cpp:258 */
    {0x1002, 0x6821, "Radeon HD Verde"}, /* driver.cpp:259 */
    {0x1002, 0x6823, "Radeon HD Verde"}, /* driver.cpp:260 */
    {0x1002, 0x6824, "Radeon HD Verde"}, /* driver.cpp:261 */
    {0x1002, 0x6825, "Radeon HD Verde"}, /* driver.cpp:262 */
    {0x1002, 0x6826, "Radeon HD Verde"}, /* driver.cpp:263 */
    {0x1002, 0x6827, "Radeon HD Verde"}, /* driver.cpp:264 */
    {0x1002, 0x6828, "Radeon HD Verde"}, /* driver.cpp:265 */
    {0x1002, 0x6829, "Radeon HD Verde"}, /* driver.cpp:266 */
    {0x1002, 0x682a, "Radeon HD Verde"}, /* driver.cpp:267 */
    {0x1002, 0x682b, "Radeon HD Verde"}, /* driver.cpp:268 */
    {0x1002, 0x682c, "FirePro W4100"}, /* driver.cpp:269 */
    {0x1002, 0x682d, "Radeon HD Verde"}, /* driver.cpp:270 */
    {0x1002, 0x682f, "Radeon HD Verde"}, /* driver.cpp:271 */
    {0x1002, 0x6830, "Radeon HD Verde"}, /* driver.cpp:272 */
    {0x1002, 0x6831, "Radeon HD Verde"}, /* driver.cpp:273 */
    {0x1002, 0x6835, "Radeon R7 Series"}, /* driver.cpp:274 */
    {0x1002, 0x6837, "Radeon HD Verde"}, /* driver.cpp:275 */
    {0x1002, 0x6838, "Radeon HD Verde"}, /* driver.cpp:276 */
    {0x1002, 0x6839, "Radeon HD Verde"}, /* driver.cpp:277 */
    {0x1002, 0x683b, "Radeon HD Verde"}, /* driver.cpp:278 */
    {0x1002, 0x683d, "Radeon HD 7770"}, /* driver.cpp:279 */
    {0x1002, 0x683f, "Radeon HD 7750"}, /* driver.cpp:280 */
    {0x1002, 0x6800, "Radeon HD 7970"}, /* driver.cpp:282 */
    {0x1002, 0x6801, "Radeon HD Pitcairn"}, /* driver.cpp:283 */
    {0x1002, 0x6802, "Radeon HD Pitcairn"}, /* driver.cpp:284 */
    {0x1002, 0x6806, "Radeon HD Pitcairn"}, /* driver.cpp:285 */
    {0x1002, 0x6808, "Radeon HD Pitcairn"}, /* driver.cpp:286 */
    {0x1002, 0x6809, "Radeon HD Pitcairn"}, /* driver.cpp:287 */
    {0x1002, 0x6810, "Radeon HD R9 270X"}, /* driver.cpp:288 */
    {0x1002, 0x6811, "Radeon HD R9 270"}, /* driver.cpp:289 */
    {0x1002, 0x6816, "Radeon HD Pitcairn"}, /* driver.cpp:290 */
    {0x1002, 0x6817, "Radeon HD Pitcairn"}, /* driver.cpp:291 */
    {0x1002, 0x6818, "Radeon HD 7870"}, /* driver.cpp:292 */
    {0x1002, 0x6819, "Radeon HD 7800"}, /* driver.cpp:293 */
    {0x1002, 0x684c, "Radeon HD Pitcairn"}, /* driver.cpp:294 */
    {0x1002, 0x6780, "Radeon HD Tahiti"}, /* driver.cpp:296 */
    {0x1002, 0x6784, "Radeon HD Tahiti"}, /* driver.cpp:297 */
    {0x1002, 0x6788, "Radeon HD Tahiti"}, /* driver.cpp:298 */
    {0x1002, 0x678a, "Radeon HD Tahiti"}, /* driver.cpp:299 */
    {0x1002, 0x6790, "Radeon HD Tahiti"}, /* driver.cpp:300 */
    {0x1002, 0x679e, "Radeon HD Tahiti"}, /* driver.cpp:301 */
    {0x1002, 0x679f, "Radeon HD Tahiti"}, /* driver.cpp:302 */
    {0x1002, 0x679a, "Radeon HD 7950"}, /* driver.cpp:303 */
    {0x1002, 0x6798, "Radeon HD 7970"}, /* driver.cpp:304 */
    {0x1002, 0x6799, "Radeon HD 7990"}, /* driver.cpp:305 */
    {0x1002, 0x9900, "Radeon HD 7660"}, /* driver.cpp:307 */
    {0x1002, 0x9901, "Radeon HD 7660"}, /* driver.cpp:308 */
    {0x1002, 0x9903, "Radeon HD 7640"}, /* driver.cpp:309 */
    {0x1002, 0x9904, "Radeon HD 7560"}, /* driver.cpp:310 */
    {0x1002, 0x9905, "FirePro A300"}, /* driver.cpp:311 */
    {0x1002, 0x9906, "FirePro A300"}, /* driver.cpp:312 */
    {0x1002, 0x9907, "Radeon HD 7560"}, /* driver.cpp:313 */
    {0x1002, 0x9908, "Radeon HD 7620"}, /* driver.cpp:314 */
    {0x1002, 0x9909, "Radeon HD 7500"}, /* driver.cpp:315 */
    {0x1002, 0x990a, "Radeon HD 7500"}, /* driver.cpp:316 */
    {0x1002, 0x990b, "Radeon HD 8650"}, /* driver.cpp:317 */
    {0x1002, 0x990d, "Radeon HD 8550"}, /* driver.cpp:318 */
    {0x1002, 0x990f, "Radeon HD 8610"}, /* driver.cpp:319 */
    {0x1002, 0x9910, "Radeon HD 7660"}, /* driver.cpp:320 */
    {0x1002, 0x9913, "Radeon HD 7640"}, /* driver.cpp:321 */
    {0x1002, 0x9917, "Radeon HD 7620"}, /* driver.cpp:322 */
    {0x1002, 0x9918, "Radeon HD 7600"}, /* driver.cpp:323 */
    {0x1002, 0x9919, "Radeon HD 7500"}, /* driver.cpp:324 */
    {0x1002, 0x9990, "Radeon HD 7920"}, /* driver.cpp:325 */
    {0x1002, 0x9991, "Radeon HD 7540"}, /* driver.cpp:326 */
    {0x1002, 0x9992, "Radeon HD 7420"}, /* driver.cpp:327 */
    {0x1002, 0x9994, "Radeon HD 7400"}, /* driver.cpp:328 */
    {0x1002, 0x9995, "Radeon HD 8450"}, /* driver.cpp:329 */
    {0x1002, 0x9996, "Radeon HD 8470"}, /* driver.cpp:330 */
    {0x1002, 0x9997, "Radeon HD 8350"}, /* driver.cpp:331 */
    {0x1002, 0x999a, "Radeon HD 8410"}, /* driver.cpp:332 */
    {0x1002, 0x999b, "Radeon HD 8310"}, /* driver.cpp:333 */
    {0x1002, 0x999c, "Radeon HD 8650"}, /* driver.cpp:334 */
    {0x1002, 0x999d, "Radeon HD 8550"}, /* driver.cpp:335 */
    {0x1002, 0x99a2, "Radeon HD 7420"}, /* driver.cpp:336 */
    {0x1002, 0x99a4, "Radeon HD 7400"}, /* driver.cpp:337 */
    {0x1002, 0x990c, "Radeon HD 8670"}, /* driver.cpp:339 */
    {0x1002, 0x990e, "Radeon HD 8570"}, /* driver.cpp:340 */
    {0x1002, 0x6600, "Radeon HD 8750M"}, /* driver.cpp:341 */
    {0x1002, 0x6601, "Radeon HD 8730M"}, /* driver.cpp:342 */
    {0x1002, 0x6602, "Radeon HD Oland"}, /* driver.cpp:343 */
    {0x1002, 0x6603, "Radeon HD Oland"}, /* driver.cpp:344 */
    {0x1002, 0x6604, "Radeon R7 M270"}, /* driver.cpp:345 */
    {0x1002, 0x6605, "Radeon R7 M260"}, /* driver.cpp:346 */
    {0x1002, 0x6606, "Radeon HD 8790"}, /* driver.cpp:347 */
    {0x1002, 0x6607, "Radeon HD 8350"}, /* driver.cpp:348 */
    {0x1002, 0x6608, "FirePro W2100"}, /* driver.cpp:349 */
    {0x1002, 0x6610, "Radeon R7 250"}, /* driver.cpp:350 */
    {0x1002, 0x6611, "Radeon R7 200"}, /* driver.cpp:351 */
    {0x1002, 0x6613, "Radeon R7 240"}, /* driver.cpp:352 */
    {0x1002, 0x6620, "Radeon R7 240"}, /* driver.cpp:353 */
    {0x1002, 0x6621, "Radeon HD Oland"}, /* driver.cpp:354 */
    {0x1002, 0x6623, "Radeon HD Oland"}, /* driver.cpp:355 */
    {0x1002, 0x6631, "Radeon HD Oland"}, /* driver.cpp:356 */
    {0x1002, 0x1304, "Radeon HD Kaveri"}, /* driver.cpp:364 */
    {0x1002, 0x1305, "Radeon HD Kaveri"}, /* driver.cpp:365 */
    {0x1002, 0x1306, "Radeon HD Kaveri"}, /* driver.cpp:366 */
    {0x1002, 0x1307, "Radeon HD Kaveri"}, /* driver.cpp:367 */
    {0x1002, 0x1308, "Radeon HD Kaveri"}, /* driver.cpp:368 */
    {0x1002, 0x1309, "Radeon R7 Series"}, /* driver.cpp:369 */
    {0x1002, 0x130a, "Radeon R6 Series"}, /* driver.cpp:370 */
    {0x1002, 0x130b, "Radeon R4 Series"}, /* driver.cpp:371 */
    {0x1002, 0x130c, "Radeon R7 Series"}, /* driver.cpp:372 */
    {0x1002, 0x130d, "Radeon R6 Series"}, /* driver.cpp:373 */
    {0x1002, 0x130e, "Radeon R5 Series"}, /* driver.cpp:374 */
    {0x1002, 0x130f, "Radeon R7 Series"}, /* driver.cpp:375 */
    {0x1002, 0x1310, "Radeon HD Kaveri"}, /* driver.cpp:376 */
    {0x1002, 0x1311, "Radeon HD Kaveri"}, /* driver.cpp:377 */
    {0x1002, 0x1312, "Radeon HD Kaveri"}, /* driver.cpp:378 */
    {0x1002, 0x1313, "Radeon R7 Series"}, /* driver.cpp:379 */
    {0x1002, 0x1314, "Radeon HD Kaveri"}, /* driver.cpp:380 */
    {0x1002, 0x1315, "Radeon R5 Series"}, /* driver.cpp:381 */
    {0x1002, 0x1316, "Radeon R5 Series"}, /* driver.cpp:382 */
    {0x1002, 0x1317, "Radeon HD Kaveri"}, /* driver.cpp:383 */
    {0x1002, 0x1318, "Radeon R5 Series"}, /* driver.cpp:384 */
    {0x1002, 0x131b, "Radeon R5 Series"}, /* driver.cpp:385 */
    {0x1002, 0x131c, "Radeon R7 Series"}, /* driver.cpp:386 */
    {0x1002, 0x131d, "Radeon R6 Series"}, /* driver.cpp:387 */
    {0x1002, 0x6640, "Radeon R9 380"}, /* driver.cpp:389 */
    {0x1002, 0x6641, "Radeon HD 8930M"}, /* driver.cpp:390 */
    {0x1002, 0x6646, "Radeon R9 380"}, /* driver.cpp:391 */
    {0x1002, 0x6647, "Radeon R9 380"}, /* driver.cpp:392 */
    {0x1002, 0x6649, "FirePro W5100"}, /* driver.cpp:393 */
    {0x1002, 0x6650, "Radeon HD Bonaire"}, /* driver.cpp:394 */
    {0x1002, 0x6651, "Radeon HD Bonaire"}, /* driver.cpp:395 */
    {0x1002, 0x6658, "Radeon R7 200"}, /* driver.cpp:396 */
    {0x1002, 0x665c, "Radeon HD 7790"}, /* driver.cpp:397 */
    {0x1002, 0x665d, "Radeon R7 200"}, /* driver.cpp:398 */
    {0x1002, 0x665f, "Radeon R7 300"}, /* driver.cpp:399 */
    {0x1002, 0x9832, "Radeon HD 8330"}, /* driver.cpp:401 */
    {0x1002, 0x9833, "Radeon HD 8330"}, /* driver.cpp:402 */
    {0x1002, 0x9834, "Radeon HD 8210"}, /* driver.cpp:403 */
    {0x1002, 0x9835, "Radeon HD 8210"}, /* driver.cpp:404 */
    {0x1002, 0x9836, "Radeon HD 8280"}, /* driver.cpp:405 */
    {0x1002, 0x9837, "Radeon HD 8280"}, /* driver.cpp:406 */
    {0x1002, 0x9838, "Radeon HD 8240"}, /* driver.cpp:407 */
    {0x1002, 0x9839, "Radeon HD 8180"}, /* driver.cpp:408 */
    {0x1002, 0x983a, "Radeon HD Kabini"}, /* driver.cpp:409 */
    {0x1002, 0x983b, "Radeon HD Kabini"}, /* driver.cpp:410 */
    {0x1002, 0x983c, "Radeon HD Kabini"}, /* driver.cpp:411 */
    {0x1002, 0x983d, "Radeon HD 8250"}, /* driver.cpp:412 */
    {0x1002, 0x983e, "Radeon HD Kabini"}, /* driver.cpp:413 */
    {0x1002, 0x983f, "Radeon HD Kabini"}, /* driver.cpp:414 */
    {0x1002, 0x9850, "Radeon HD R3"}, /* driver.cpp:416 */
    {0x1002, 0x9851, "Radeon HD R2"}, /* driver.cpp:417 */
    {0x1002, 0x9852, "Radeon HD R2"}, /* driver.cpp:418 */
    {0x1002, 0x9853, "Radeon HD R2"}, /* driver.cpp:419 */
    {0x1002, 0x9854, "Radeon HD R2"}, /* driver.cpp:420 */
    {0x1002, 0x9855, "Radeon HD R3"}, /* driver.cpp:421 */
    {0x1002, 0x9856, "Radeon HD R2"}, /* driver.cpp:422 */
    {0x1002, 0x9857, "Radeon HD R2"}, /* driver.cpp:423 */
    {0x1002, 0x9858, "Radeon HD Mullins"}, /* driver.cpp:424 */
    {0x1002, 0x9859, "Radeon HD Mullins"}, /* driver.cpp:425 */
    {0x1002, 0x985a, "Radeon HD Mullins"}, /* driver.cpp:426 */
    {0x1002, 0x985b, "Radeon HD Mullins"}, /* driver.cpp:427 */
    {0x1002, 0x985c, "Radeon HD Mullins"}, /* driver.cpp:428 */
    {0x1002, 0x985d, "Radeon HD Mullins"}, /* driver.cpp:429 */
    {0x1002, 0x985e, "Radeon HD Mullins"}, /* driver.cpp:430 */
    {0x1002, 0x985f, "Radeon HD Mullins"}, /* driver.cpp:431 */
    {0x1002, 0x67a0, "Radeon FirePro W9100"}, /* driver.cpp:433 */
    {0x1002, 0x67a1, "Radeon FirePro W8100"}, /* driver.cpp:434 */
    {0x1002, 0x67a2, "Radeon HD Hawaii"}, /* driver.cpp:435 */
    {0x1002, 0x67a8, "Radeon HD Hawaii"}, /* driver.cpp:436 */
    {0x1002, 0x67a9, "Radeon HD Hawaii"}, /* driver.cpp:437 */
    {0x1002, 0x67aa, "Radeon HD Hawaii"}, /* driver.cpp:438 */
    {0x1002, 0x67b0, "Radeon R9 290X/390X"}, /* driver.cpp:439 */
    {0x1002, 0x67b1, "Radeon R9 290/390"}, /* driver.cpp:440 */
    {0x1002, 0x67b8, "Radeon HD Hawaii"}, /* driver.cpp:441 */
    {0x1002, 0x67b9, "Radeon R9 295X2"}, /* driver.cpp:442 */
    {0x1002, 0x67ba, "Radeon HD Hawaii"}, /* driver.cpp:443 */
    {0x1002, 0x67be, "Radeon HD Hawaii"}, /* driver.cpp:444 */
    {0x1002, 0x73a0, "Radeon RX Navi"}, /* driver.cpp:449 */
    {0x1002, 0x73a1, "Radeon RX Navi"}, /* driver.cpp:450 */
    {0x1002, 0x73a2, "Radeon RX Navi"}, /* driver.cpp:451 */
    {0x1002, 0x73a3, "Radeon RX Navi"}, /* driver.cpp:452 */
    {0x1002, 0x73ab, "Radeon RX Navi"}, /* driver.cpp:453 */
    {0x1002, 0x73ae, "Radeon RX Navi"}, /* driver.cpp:454 */
    {0x1002, 0x73bf, "Radeon RX 6800 / 6900 XT"}, /* driver.cpp:455 */
    {0x1002, 0x73cf, "Radeon RX Navi"}, /* driver.cpp:456 */
    {0x1002, 0x163f, "Radeon RX Navi (Van Gogh)"}, /* driver.cpp:458 */
    {0x1002, 0x73c0, "Radeon RX Navi (Navy)"}, /* driver.cpp:460 */
    {0x1002, 0x73c1, "Radeon RX Navi (Navy)"}, /* driver.cpp:461 */
    {0x1002, 0x73c3, "Radeon RX Navi (Navy)"}, /* driver.cpp:462 */
    {0x1002, 0x73df, "Radeon RX 6700 XT"}, /* driver.cpp:463 */
    {0x1002, 0x73e0, "Radeon RX Navi (Dimgrey)"}, /* driver.cpp:465 */
    {0x1002, 0x73e1, "Radeon RX Navi (Dimgrey)"}, /* driver.cpp:466 */
    {0x1002, 0x73e2, "Radeon RX Navi (Dimgrey)"}, /* driver.cpp:467 */
    {0x1002, 0x73ff, "Radeon RX Navi (Dimgrey)"}, /* driver.cpp:468 */
};

/* Per-family match records.  `.upstream` is what the family's hook table
 * hands out today in that checkout; it is a capability *inventory*, not a
 * statement that SCos has ported the code that uses it. */
/* The one local record, described above the generator's own provenance header: this family is
 * not read out of an upstream driver.  The id row is what the module claims and the loader
 * cross-checks; deleting it here stops drivers/gpu/cirrus from loading at all rather than leaving it
 * unverified. */
static const struct gpu_pci_id gpu_ids_cirrus[] = {
    {0x1013, 0x00B8, "GD 5446 (PCI)"},        /* the last Cirrus with a bitBLT engine */
};

static const struct gpu_match gpu_match_table[] = {
    {
        .family = "radeon", .primary_vendor = 0x1002,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = gpu_ids_radeon, .id_count = 144u,
        .upstream = {
        .engine2d = 1, .vsync = 1, .pan = 1, .cursor = 0, .overlay = 1,
        .fill = 1, .blit = 1, .span = 1, .modeset = 1, .dpms = 1,
        },
        .features = "engine:advertises B_2D_ACCELERATION (src/add-ons/accelerants/radeon/EngineManagment.c:49); r"
        "etrace:direct; pan:direct; cursor:disabled-by-comment; overlay:direct; fill_rect:direct; scr"
        "een_blit:direct; fill_span:direct; set_mode:direct; dpms:direct",
        .source = "src/add-ons/kernel/drivers/graphics/radeon/detect.c",
        .note = "3 duplicate rows collapsed",
    },
    {
        .family = "nvidia", .primary_vendor = 0x10de,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = gpu_ids_nvidia, .id_count = 268u,
        .upstream = {
        .engine2d = 1, .vsync = 1, .pan = 1, .cursor = 0, .overlay = 1,
        .fill = 1, .blit = 1, .span = 1, .modeset = 1, .dpms = 1,
        },
        .features = "engine:advertises B_2D_ACCELERATION (src/add-ons/accelerants/nvidia/EngineManagment.c:22); r"
        "etrace:direct; pan:direct; cursor:conditional; overlay:direct; fill_rect:direct; screen_blit"
        ":direct; fill_span:direct; set_mode:direct; dpms:direct",
        .source = "src/add-ons/kernel/drivers/graphics/nvidia/driver.c",
        .note = "19 id rows added by SCos (Blackwell), not from the upstream table",
    },
    {
        .family = "matrox", .primary_vendor = 0x102b,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = gpu_ids_matrox, .id_count = 9u,
        .upstream = {
        .engine2d = 1, .vsync = 1, .pan = 1, .cursor = 0, .overlay = 1,
        .fill = 1, .blit = 1, .span = 1, .modeset = 1, .dpms = 1,
        },
        .features = "engine:advertises B_2D_ACCELERATION (src/add-ons/accelerants/matrox/EngineManagment.c:15); r"
        "etrace:direct; pan:direct; cursor:conditional; overlay:direct; fill_rect:direct; screen_blit"
        ":direct; fill_span:direct; set_mode:direct; dpms:direct",
        .source = "src/add-ons/kernel/drivers/graphics/matrox/driver.c",
    },
    {
        .family = "via", .primary_vendor = 0x1106,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = gpu_ids_via, .id_count = 5u,
        .upstream = {
        .engine2d = 1, .vsync = 1, .pan = 1, .cursor = 0, .overlay = 1,
        .fill = 1, .blit = 1, .span = 1, .modeset = 1, .dpms = 1,
        },
        .features = "engine:advertises B_2D_ACCELERATION (src/add-ons/accelerants/via/EngineManagement.c:15); ret"
        "race:direct; pan:direct; cursor:conditional; overlay:direct; fill_rect:direct; screen_blit:d"
        "irect; fill_span:direct; set_mode:direct; dpms:direct",
        .source = "src/add-ons/kernel/drivers/graphics/via/driver.c",
    },
    {
        .family = "neomagic", .primary_vendor = 0x10c8,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = gpu_ids_neomagic, .id_count = 9u,
        .upstream = {
        .engine2d = 1, .vsync = 1, .pan = 1, .cursor = 0, .overlay = 1,
        .fill = 1, .blit = 1, .span = 1, .modeset = 1, .dpms = 1,
        },
        .features = "engine:advertises B_2D_ACCELERATION (src/add-ons/accelerants/neomagic/EngineManagment.c:15);"
        " retrace:direct; pan:direct; cursor:conditional; overlay:direct; fill_rect:direct; screen_bl"
        "it:direct; fill_span:direct; set_mode:direct; dpms:direct",
        .source = "src/add-ons/kernel/drivers/graphics/neomagic/driver.c",
    },
    {
        .family = "et6x00", .primary_vendor = 0x100c,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = gpu_ids_et6x00, .id_count = 2u,
        .upstream = {
        .engine2d = 1, .vsync = 0, .pan = 0, .cursor = 0, .overlay = 0,
        .fill = 1, .blit = 1, .span = 0, .modeset = 1, .dpms = 0,
        },
        .features = "engine:advertises B_2D_ACCELERATION (src/add-ons/accelerants/et6x00/EngineManagment.c:11); r"
        "etrace:disabled-by-comment; pan:absent; cursor:absent; overlay:absent; fill_rect:direct; scr"
        "een_blit:direct; fill_span:absent; set_mode:direct; dpms:absent",
        .source = "src/add-ons/kernel/drivers/graphics/et6x00/driver.c",
    },
    {
        .family = "s3", .primary_vendor = 0x5333,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = gpu_ids_s3, .id_count = 34u,
        .upstream = {
        .engine2d = 1, .vsync = 1, .pan = 1, .cursor = 1, .overlay = 0,
        .fill = 1, .blit = 1, .span = 1, .modeset = 1, .dpms = 1,
        },
        .features = "engine:advertises B_2D_ACCELERATION (src/add-ons/accelerants/s3/engine.cpp:12); retrace:dire"
        "ct; pan:direct; cursor:direct; overlay:absent; fill_rect:direct; screen_blit:direct; fill_sp"
        "an:direct; set_mode:direct; dpms:direct",
        .source = "src/add-ons/kernel/drivers/graphics/s3/driver.cpp",
    },
    {
        .family = "ati", .primary_vendor = 0x1002,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = gpu_ids_ati, .id_count = 77u,
        .upstream = {
        .engine2d = 1, .vsync = 1, .pan = 1, .cursor = 1, .overlay = 1,
        .fill = 1, .blit = 1, .span = 1, .modeset = 1, .dpms = 1,
        },
        .features = "engine:advertises B_2D_ACCELERATION (src/add-ons/accelerants/ati/engine.cpp:12); retrace:dir"
        "ect; pan:direct; cursor:direct; overlay:direct; fill_rect:direct; screen_blit:direct; fill_s"
        "pan:direct; set_mode:direct; dpms:direct",
        .source = "src/add-ons/kernel/drivers/graphics/ati/driver.cpp",
    },
    {
        .family = "3dfx", .primary_vendor = 0x121a,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = gpu_ids_3dfx, .id_count = 3u,
        .upstream = {
        .engine2d = 1, .vsync = 0, .pan = 1, .cursor = 1, .overlay = 1,
        .fill = 1, .blit = 1, .span = 1, .modeset = 1, .dpms = 1,
        },
        .features = "engine:advertises B_2D_ACCELERATION (src/add-ons/accelerants/3dfx/engine.cpp:12); retrace:de"
        "nied; pan:direct; cursor:direct; overlay:direct; fill_rect:direct; screen_blit:direct; fill_"
        "span:direct; set_mode:direct; dpms:direct",
        .source = "src/add-ons/kernel/drivers/graphics/3dfx/driver.cpp",
    },
    {
        .family = "intel_810", .primary_vendor = 0x8086,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = gpu_ids_intel_810, .id_count = 4u,
        .upstream = {
        .engine2d = 1, .vsync = 0, .pan = 1, .cursor = 0, .overlay = 0,
        .fill = 0, .blit = 0, .span = 0, .modeset = 1, .dpms = 1,
        },
        .features = "engine:advertises B_2D_ACCELERATION (src/add-ons/accelerants/intel_810/engine.cpp:14); retra"
        "ce:denied; pan:direct; cursor:absent; overlay:absent; fill_rect:absent; screen_blit:absent; "
        "fill_span:absent; set_mode:direct; dpms:direct",
        .source = "src/add-ons/kernel/drivers/graphics/intel_810/driver.cpp",
    },
    {
        .family = "intel_extreme", .primary_vendor = 0x8086,
        .class_base = 0x03, .class_sub_a = 0x00, .class_sub_b = 0x80,
        .ids = gpu_ids_intel_extreme, .id_count = 143u,
        .upstream = {
        .engine2d = 0, .vsync = 1, .pan = 1, .cursor = 0, .overlay = 0,
        .fill = 1, .blit = 1, .span = 0, .modeset = 1, .dpms = 1,
        },
        .features = "engine:no 2D capability bit (src/add-ons/accelerants/intel_extreme/engine.cpp:29); retrace:d"
        "irect; pan:direct; cursor:gated; overlay:denied-for-some-devices; fill_rect:direct; screen_b"
        "lit:direct; fill_span:denied; set_mode:direct; dpms:direct",
        .source = "src/add-ons/kernel/drivers/graphics/intel_extreme/driver.cpp",
        .note = "3 duplicate rows collapsed",
    },
    {
        .family = "radeon_hd", .primary_vendor = 0x1002,
        .class_base = 0x03, .class_sub_a = 0x00, .class_sub_b = 0xff,
        .ids = gpu_ids_radeon_hd, .id_count = 340u,
        .upstream = {
        .engine2d = 0, .vsync = 1, .pan = 0, .cursor = 0, .overlay = 0,
        .fill = 1, .blit = 1, .span = 1, .modeset = 1, .dpms = 1,
        },
        .features = "engine:no 2D capability bit (src/add-ons/accelerants/radeon_hd/engine.cpp:27); retrace:direc"
        "t; pan:absent; cursor:absent; overlay:absent; fill_rect:direct; screen_blit:direct; fill_spa"
        "n:direct; set_mode:direct; dpms:direct",
        .source = "src/add-ons/kernel/drivers/graphics/radeon_hd/driver.cpp",
    },
    {
        .family = "vesa", .primary_vendor = 0x0,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = NULL, .id_count = 0u,
        .upstream = {
        .engine2d = 0, .vsync = 1, .pan = 1, .cursor = 1, .overlay = 1,
        .fill = 0, .blit = 0, .span = 0, .modeset = 1, .dpms = 1,
        },
        .features = "engine:no 2D capability bit (family has no engine source); retrace:direct; pan:direct; curso"
        "r:direct; overlay:direct; fill_rect:absent; screen_blit:absent; fill_span:absent; set_mode:d"
        "irect; dpms:direct",
        .source = "src/add-ons/accelerants/vesa",
        .note = "no PCI ID table: binds by class or firmware",
    },
    {
        .family = "framebuffer", .primary_vendor = 0x0,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = NULL, .id_count = 0u,
        .upstream = {
        .engine2d = 0, .vsync = 1, .pan = 0, .cursor = 0, .overlay = 0,
        .fill = 0, .blit = 0, .span = 0, .modeset = 1, .dpms = 0,
        },
        .features = "engine:no 2D capability bit (family has no engine source); retrace:direct; pan:absent; curso"
        "r:absent; overlay:absent; fill_rect:absent; screen_blit:absent; fill_span:absent; set_mode:d"
        "irect; dpms:absent",
        .source = "src/add-ons/accelerants/framebuffer",
        .note = "no PCI ID table: binds by class or firmware",
    },
    {
        .family = "virtio", .primary_vendor = 0x0,
        .class_base = 0xff, .class_sub_a = 0xff, .class_sub_b = 0xff,
        .ids = NULL, .id_count = 0u,
        .upstream = {
        .engine2d = 0, .vsync = 1, .pan = 0, .cursor = 0, .overlay = 0,
        .fill = 0, .blit = 0, .span = 0, .modeset = 1, .dpms = 0,
        },
        .features = "engine:no 2D capability bit (family has no engine source); retrace:direct; pan:absent; curso"
        "r:absent; overlay:absent; fill_rect:absent; screen_blit:absent; fill_span:absent; set_mode:d"
        "irect; dpms:absent",
        .source = "src/add-ons/accelerants/virtio",
        .note = "no PCI ID table: binds by class or firmware",
    },
    {
        .family = "cirrus", .primary_vendor = 0x1013,
        .class_base = 0x03, .class_sub_a = 0x00, .class_sub_b = 0xff,
        .ids = gpu_ids_cirrus, .id_count = 1u,
        .upstream = {
        .engine2d = 1, .vsync = 0, .pan = 0, .cursor = 0, .overlay = 0,
        .fill = 1, .blit = 1, .span = 0, .modeset = 0, .dpms = 0,
        },
        .features = "engine:SCos-authored bitBLT driver, device-verified; retrace:absent; pan:absent;"
        " cursor:absent; overlay:absent; fill_rect:direct; screen_blit:direct; fill_span:absent; set_"
        "mode:absent; dpms:absent",
        .source = "drivers/gpu/cirrus (no upstream driver; verified against QEMU's CL-GD5446 model)",
        .note = "hand-authored id row and capability record, not generated from an upstream table",
    },
};

/* GPU_MATCH_COUNT and GPU_ID_TOTAL include the hand-authored cirrus record: 16 families, and
 * 1039 exact ids that bind a driver (1019 from upstream tables, the one local row, and the
 * 19 rows SCos added inside 1 upstream family array). */
#define GPU_MATCH_COUNT 16u
#define GPU_ID_TOTAL 1039u

#endif
