/* Generated by tools/research/gen_gpu_tables.py --registry-only - do not edit by hand.
 *
 * Chip NAMES only, from tools/research/pci.ids.display.txt.  These rows exist so that a
 * machine can be told what it has when no driver in this tree covers it, instead of being
 * told "unknown device".  A row here never selects a module and never implies
 * acceleration: gpu_match_device() reports it separately, and the boot stub and
 * gpu_module.c both refuse to load a driver for it.  The rows that bind a driver live in
 * gpu_ids.h, generated from the pinned upstream driver sources; no id appears in both.
 * Source: pci.ids (PCI ID Project), version 2026.09.21 (dated 2026-09-21 03:15:02).
 *
 * Refresh: gen_gpu_tables.py --extract-pci-ids <pci.ids>, then --registry-only.
 */
#ifndef SCOS_GPU_IDS_REGISTRY_H
#define SCOS_GPU_IDS_REGISTRY_H

/* Included only by kernel/drivers/gpu/gpu_match.c, which owns both generated tables: these
 * are `static` arrays, so exactly one translation unit may include this file. */

/* intel_extreme: 135 display ids named by the registry and bound by no
   driver table in the tree - known chips with nothing ported for them. */
static const struct gpu_pci_id gpu_registry_intel_extreme[] = {
    {0x8086, 0x10b, "Xeon E3-1200/2nd Generation Core Processor Family Integrat"}, /* pci.ids */
    {0x8086, 0x176, "3rd Gen Core processor Graphics Controller"}, /* pci.ids */
    {0x8086, 0x402, "Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics"}, /* pci.ids */
    {0x8086, 0x406, "Haswell Integrated Graphics Controller"}, /* pci.ids */
    {0x8086, 0x40a, "Xeon E3-1200 v3 Processor Integrated Graphics Controller"}, /* pci.ids */
    {0x8086, 0x41e, "4th Generation Core Processor Family Integrated Graphics C"}, /* pci.ids */
    {0x8086, 0x8cf, "Atom Processor Z2760 Integrated Graphics Controller"}, /* pci.ids */
    {0x8086, 0xbe0, "Atom Processor D2xxx/N2xxx Integrated Graphics Controller"}, /* pci.ids */
    {0x8086, 0xd12, "Crystal Well Integrated Graphics Controller"}, /* pci.ids */
    {0x8086, 0xd22, "Crystal Well Integrated Iris Pro Graphics 5200"}, /* pci.ids */
    {0x8086, 0xf31, "Atom Processor Z36xxx/Z37xxx Series Graphics & Display"}, /* pci.ids */
    {0x8086, 0x1240, "82752 (752) AGP Graphics Accelerator"}, /* pci.ids */
    {0x8086, 0x1923, "HD Graphics 535"}, /* pci.ids */
    {0x8086, 0x1927, "Skylake-U GT3 [Iris Graphics 550]"}, /* pci.ids */
    {0x8086, 0x192d, "Skylake-H GT3 [Iris Graphics P555]"}, /* pci.ids */
    {0x8086, 0x1932, "Iris Pro Graphics 580"}, /* pci.ids */
    {0x8086, 0x193a, "Skylake-H GT4 [Iris Pro Graphics P580]"}, /* pci.ids */
    {0x8086, 0x193b, "Skylake-H GT4 [Iris Pro Graphics 580]"}, /* pci.ids */
    {0x8086, 0x1a12, "Timna CPU Graphics"}, /* pci.ids */
    {0x8086, 0x22b0, "Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integr"}, /* pci.ids */
    {0x8086, 0x2780, "82915G/GV/GL/910GL [Grantsdale] Graphics Device"}, /* pci.ids */
    {0x8086, 0x2782, "82915G Integrated Graphics Controller"}, /* pci.ids */
    {0x8086, 0x27a6, "Mobile 945GM/GMS/GME, 943/940GML Express Integrated Graphi"}, /* pci.ids */
    {0x8086, 0x2a03, "Mobile GM965/GL960 Integrated Graphics Controller (seconda"}, /* pci.ids */
    {0x8086, 0x2a41, "Mobile 4 Series Chipset PCI Express Graphics Port"}, /* pci.ids */
    {0x8086, 0x2e5b, "Graphics Media Accelerator 500 Graphics"}, /* pci.ids */
    {0x8086, 0x3e94, "Coffee Lake-S GT2 [UHD Graphics P630]"}, /* pci.ids */
    {0x8086, 0x3e9c, "Coffee Lake-S GT1 [UHD Graphics 610]"}, /* pci.ids */
    {0x8086, 0x3ea0, "WhiskeyLake-U GT2 [UHD Graphics 620]"}, /* pci.ids */
    {0x8086, 0x3ea1, "Whiskey Lake-U GT1 [UHD Graphics 610]"}, /* pci.ids */
    {0x8086, 0x3ea8, "Coffee Lake-U GT3 [Iris Plus Graphics 655]"}, /* pci.ids */
    {0x8086, 0x3ea9, "Coffee Lake-U GT2 [UHD Graphics 620]"}, /* pci.ids */
    {0x8086, 0x4108, "Atom Processor E6xx Integrated Graphics Controller"}, /* pci.ids */
    {0x8086, 0x4555, "Elkhart Lake [UHD Graphics Gen11 16EU]"}, /* pci.ids */
    {0x8086, 0x4571, "Elkhart Lake [UHD Graphics Gen11 32EU]"}, /* pci.ids */
    {0x8086, 0x4626, "Alder Lake-P Integrated Graphics Controller"}, /* pci.ids */
    {0x8086, 0x4628, "Alder Lake-UP3 GT2 [UHD Graphics]"}, /* pci.ids */
    {0x8086, 0x462a, "AlderLake-P [UHD Graphics]"}, /* pci.ids */
    {0x8086, 0x4680, "Alder Lake-S GT1 [UHD Graphics 770]"}, /* pci.ids */
    {0x8086, 0x4682, "Alder Lake-S GT1 [UHD Graphics 730]"}, /* pci.ids */
    {0x8086, 0x4688, "Alder Lake-HX GT1 [UHD Graphics 770]"}, /* pci.ids */
    {0x8086, 0x468a, "Alder Lake-S [UHD Graphics]"}, /* pci.ids */
    {0x8086, 0x4693, "Alder Lake-S GT1 [UHD Graphics 710]"}, /* pci.ids */
    {0x8086, 0x46a1, "UHD Graphics"}, /* pci.ids */
    {0x8086, 0x46a3, "Alder Lake-P GT1 [UHD Graphics]"}, /* pci.ids */
    {0x8086, 0x46a8, "Alder Lake-UP3 GT2 [Iris Xe Graphics]"}, /* pci.ids */
    {0x8086, 0x46aa, "Alder Lake-UP4 GT2 [Iris Xe Graphics]"}, /* pci.ids */
    {0x8086, 0x46b0, "AlderLake-P [Iris Xe Graphics]"}, /* pci.ids */
    {0x8086, 0x46b3, "Alder Lake-UP3 GT1 [UHD Graphics]"}, /* pci.ids */
    {0x8086, 0x46c1, "AlderLake-M [Iris Xe Graphics]"}, /* pci.ids */
    {0x8086, 0x46c3, "Alder Lake-UP4 GT1 [UHD Graphics]"}, /* pci.ids */
    {0x8086, 0x46d0, "Alder Lake-N [UHD Graphics]"}, /* pci.ids */
    {0x8086, 0x46d3, "Alder Lake-N [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0x4905, "DG1 [Iris Xe MAX Graphics]"}, /* pci.ids */
    {0x8086, 0x4906, "DG1 [Iris Xe Pod]"}, /* pci.ids */
    {0x8086, 0x4908, "DG1 [Iris Xe Graphics]"}, /* pci.ids */
    {0x8086, 0x4909, "DG1 [Iris Xe MAX 100]"}, /* pci.ids */
    {0x8086, 0x4c8a, "RocketLake-S GT1 [UHD Graphics 750]"}, /* pci.ids */
    {0x8086, 0x4c8b, "RocketLake-S GT1 [UHD Graphics 730]"}, /* pci.ids */
    {0x8086, 0x4c90, "RocketLake-S GT1 [UHD Graphics P750]"}, /* pci.ids */
    {0x8086, 0x4c9a, "RocketLake-S [UHD Graphics]"}, /* pci.ids */
    {0x8086, 0x4f80, "DG2 [Intel Xe Graphics]"}, /* pci.ids */
    {0x8086, 0x4f89, "ACMP [Xe Graphics]"}, /* pci.ids */
    {0x8086, 0x5002, "LE80578 Graphics Processor Unit"}, /* pci.ids */
    {0x8086, 0x5690, "DG2 [Arc A770M]"}, /* pci.ids */
    {0x8086, 0x5691, "DG2 [Arc A730M]"}, /* pci.ids */
    {0x8086, 0x5692, "DG2 [Arc A550M]"}, /* pci.ids */
    {0x8086, 0x5693, "DG2 [Arc A370M]"}, /* pci.ids */
    {0x8086, 0x5694, "DG2 [Arc A350M]"}, /* pci.ids */
    {0x8086, 0x5695, "DG2 [Iris Xe MAX A200M]"}, /* pci.ids */
    {0x8086, 0x5696, "DG2 [Arc A570M]"}, /* pci.ids */
    {0x8086, 0x5697, "DG2 [Arc A530M]"}, /* pci.ids */
    {0x8086, 0x5698, "DG2 [Arc Xe Graphics]"}, /* pci.ids */
    {0x8086, 0x56a0, "DG2 [Arc A770]"}, /* pci.ids */
    {0x8086, 0x56a1, "DG2 [Arc A750]"}, /* pci.ids */
    {0x8086, 0x56a2, "DG2 [Arc A580]"}, /* pci.ids */
    {0x8086, 0x56a5, "DG2 [Arc A380]"}, /* pci.ids */
    {0x8086, 0x56a6, "DG2 [Arc A310]"}, /* pci.ids */
    {0x8086, 0x56b0, "DG2 [Arc Pro A30M]"}, /* pci.ids */
    {0x8086, 0x56b1, "DG2 [Arc Pro A40/A50]"}, /* pci.ids */
    {0x8086, 0x56b2, "DG2 [Arc Pro A60M]"}, /* pci.ids */
    {0x8086, 0x56b3, "DG2 [Arc Pro A60]"}, /* pci.ids */
    {0x8086, 0x56ba, "DG2 [Arc A380E]"}, /* pci.ids */
    {0x8086, 0x56bb, "DG2 [Arc A310E]"}, /* pci.ids */
    {0x8086, 0x56bc, "DG2 [Arc A370E]"}, /* pci.ids */
    {0x8086, 0x56bd, "DG2 [Arc A350E]"}, /* pci.ids */
    {0x8086, 0x56be, "DG2 [Arc A750E]"}, /* pci.ids */
    {0x8086, 0x56bf, "DG2 [Arc A580E]"}, /* pci.ids */
    {0x8086, 0x590b, "HD Graphics 610"}, /* pci.ids */
    {0x8086, 0x5923, "HD Graphics 635"}, /* pci.ids */
    {0x8086, 0x6420, "Lunar Lake [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0x64a0, "Core Ultra 200V Series Processors Arc Graphics 130V/140V G"}, /* pci.ids */
    {0x8086, 0x7120, "82810 GMCH (Graphics Memory Controller Hub)"}, /* pci.ids */
    {0x8086, 0x7122, "82810 DC-100 (GMCH) Graphics Memory Controller Hub"}, /* pci.ids */
    {0x8086, 0x7124, "82810E DC-133 (GMCH) Graphics Memory Controller Hub"}, /* pci.ids */
    {0x8086, 0x7126, "82810 DC-133 System and Graphics Controller"}, /* pci.ids */
    {0x8086, 0x7128, "82810-M DC-100 System and Graphics Controller"}, /* pci.ids */
    {0x8086, 0x712a, "82810-M DC-133 System and Graphics Controller"}, /* pci.ids */
    {0x8086, 0x7800, "82740 (i740) AGP Graphics Accelerator"}, /* pci.ids */
    {0x8086, 0x7d40, "Meteor Lake-M [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0x7d41, "Arrow Lake-U [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0x7d45, "Meteor Lake-P [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0x7d51, "Arrow Lake-P [Arc Pro 130T/140T]"}, /* pci.ids */
    {0x8086, 0x7d55, "Meteor Lake-P [Intel Arc Graphics]"}, /* pci.ids */
    {0x8086, 0x7d67, "Arrow Lake-S [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0x7dd1, "Arrow Lake-P [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0x8108, "US15W/US15X SCH [Poulsbo] Graphics Controller"}, /* pci.ids */
    {0x8086, 0x8109, "US15L/UL11L SCH [Poulsbo] Graphics Controller"}, /* pci.ids */
    {0x8086, 0x87c0, "UHD Graphics 617"}, /* pci.ids */
    {0x8086, 0x8a58, "Ice Lake-Y GT1 [UHD Graphics G1]"}, /* pci.ids */
    {0x8086, 0x9840, "Lakefield GT2 [UHD Graphics]"}, /* pci.ids */
    {0x8086, 0x9841, "Lakefield GT1.5 [UHD Graphics]"}, /* pci.ids */
    {0x8086, 0xa70d, "Raptor Lake PCI Express 5.0 Graphics Port (PEG010)"}, /* pci.ids */
    {0x8086, 0xa720, "Raptor Lake-P [UHD Graphics]"}, /* pci.ids */
    {0x8086, 0xa74d, "Raptor Lake PCI Express 4.0 Graphics Port"}, /* pci.ids */
    {0x8086, 0xa780, "Raptor Lake-S GT1 [UHD Graphics 770]"}, /* pci.ids */
    {0x8086, 0xa781, "Raptor Lake-S UHD Graphics"}, /* pci.ids */
    {0x8086, 0xa7a0, "Raptor Lake-P [Iris Xe Graphics]"}, /* pci.ids */
    {0x8086, 0xa7aa, "Raptor Lake-P [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0xa7ac, "Raptor Lake-U [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0xb080, "Panther Lake [Arc B390]"}, /* pci.ids */
    {0x8086, 0xb081, "Panther Lake [Arc B370]"}, /* pci.ids */
    {0x8086, 0xb084, "Panther Lake [Arc Pro B390]"}, /* pci.ids */
    {0x8086, 0xb085, "Panther Lake [Arc Pro B370]"}, /* pci.ids */
    {0x8086, 0xb08f, "Panther Lake [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0xb640, "Arrow Lake-H [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0xe202, "Battlemage G21 [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0xe20b, "Battlemage G21 [Arc B580]"}, /* pci.ids */
    {0x8086, 0xe20c, "Battlemage G21 [Arc B570]"}, /* pci.ids */
    {0x8086, 0xe211, "Battlemage G21 [Arc Pro B60]"}, /* pci.ids */
    {0x8086, 0xe212, "Battlemage G21 [Arc Pro B50]"}, /* pci.ids */
    {0x8086, 0xe220, "Battlemage G31 [Intel Graphics]"}, /* pci.ids */
    {0x8086, 0xe222, "Battlemage G31 [Arc Pro B65]"}, /* pci.ids */
    {0x8086, 0xe223, "Battlemage G31 [Arc Pro B70]"}, /* pci.ids */
    {0x8086, 0xfd80, "Wildcat Lake [Intel Graphics]"}, /* pci.ids */
};

/* nvidia: 804 display ids named by the registry and bound by no
   driver table in the tree - known chips with nothing ported for them. */
static const struct gpu_pci_id gpu_registry_nvidia[] = {
    {0x10de, 0x18, "NV3 [Riva 128]"}, /* pci.ids */
    {0x10de, 0x19, "NV3 [Riva 128ZX]"}, /* pci.ids */
    {0x10de, 0x44, "NV40 [GeForce 6800 XT]"}, /* pci.ids */
    {0x10de, 0x8e, "nForce2 Serial ATA Controller"}, /* pci.ids */
    {0x10de, 0x90, "G70 [GeForce 7800 GTX]"}, /* pci.ids */
    {0x10de, 0x93, "G70 [GeForce 7800 GS]"}, /* pci.ids */
    {0x10de, 0x95, "G70 [GeForce 7800 SLI]"}, /* pci.ids */
    {0x10de, 0x97, "G70 [GeForce GTS 250]"}, /* pci.ids */
    {0x10de, 0xe3, "nForce3 Serial ATA Controller"}, /* pci.ids */
    {0x10de, 0xe4, "nForce 250Gb PCI System Management"}, /* pci.ids */
    {0x10de, 0xee, "nForce3 Serial ATA Controller 2"}, /* pci.ids */
    {0x10de, 0x14a, "NV43 [Quadro NVS 440]"}, /* pci.ids */
    {0x10de, 0x184, "NV18 [GeForce4 MX]"}, /* pci.ids */
    {0x10de, 0x190, "G80 [GeForce 8800 GTS / 8800 GTX]"}, /* pci.ids */
    {0x10de, 0x191, "G80 [GeForce 8800 GTX]"}, /* pci.ids */
    {0x10de, 0x192, "G80 [GeForce 8800 GTS]"}, /* pci.ids */
    {0x10de, 0x194, "G80 [GeForce 8800 Ultra]"}, /* pci.ids */
    {0x10de, 0x197, "G80GL [Tesla C870]"}, /* pci.ids */
    {0x10de, 0x19d, "G80GL [Quadro FX 5600]"}, /* pci.ids */
    {0x10de, 0x19e, "G80GL [Quadro FX 4600]"}, /* pci.ids */
    {0x10de, 0x1ab, "nForce 420 Memory Controller (DDR)"}, /* pci.ids */
    {0x10de, 0x1ac, "nForce 220/420 Memory Controller"}, /* pci.ids */
    {0x10de, 0x1b4, "nForce PCI System Management"}, /* pci.ids */
    {0x10de, 0x1d0, "G72 [GeForce 7350 LE]"}, /* pci.ids */
    {0x10de, 0x1d2, "G72 [GeForce 7550 LE]"}, /* pci.ids */
    {0x10de, 0x1d6, "G72M [GeForce Go 7200]"}, /* pci.ids */
    {0x10de, 0x1d9, "G72M [GeForce Go 7450]"}, /* pci.ids */
    {0x10de, 0x1db, "G72M [Quadro NVS 120M]"}, /* pci.ids */
    {0x10de, 0x1dc, "G72GLM [Quadro FX 350M]"}, /* pci.ids */
    {0x10de, 0x1de, "G72GL [Quadro FX 350]"}, /* pci.ids */
    {0x10de, 0x1e0, "nForce2 IGP2"}, /* pci.ids */
    {0x10de, 0x1e8, "nForce2 AGP"}, /* pci.ids */
    {0x10de, 0x1ea, "nForce2 Memory Controller 0"}, /* pci.ids */
    {0x10de, 0x1eb, "nForce2 Memory Controller 1"}, /* pci.ids */
    {0x10de, 0x1ec, "nForce2 Memory Controller 2"}, /* pci.ids */
    {0x10de, 0x1ed, "nForce2 Memory Controller 3"}, /* pci.ids */
    {0x10de, 0x1ee, "nForce2 Memory Controller 4"}, /* pci.ids */
    {0x10de, 0x1ef, "nForce2 Memory Controller 5"}, /* pci.ids */
    {0x10de, 0x297, "G71M [GeForce Go 7950 GTX]"}, /* pci.ids */
    {0x10de, 0x29a, "G71GLM [Quadro FX 2500M]"}, /* pci.ids */
    {0x10de, 0x29b, "G71GLM [Quadro FX 1500M]"}, /* pci.ids */
    {0x10de, 0x29d, "G71GL [Quadro FX 3500]"}, /* pci.ids */
    {0x10de, 0x29e, "G71GL [Quadro FX 1500]"}, /* pci.ids */
    {0x10de, 0x2e3, "G71 [GeForce 7900 GS AGP]"}, /* pci.ids */
    {0x10de, 0x2e4, "G71 [GeForce 7950 GT AGP]"}, /* pci.ids */
    {0x10de, 0x2e5, "G71 [GeForce 7600 GS AGP]"}, /* pci.ids */
    {0x10de, 0x300, "NV30 [GeForce FX]"}, /* pci.ids */
    {0x10de, 0x38b, "G73 [GeForce 7650 GS]"}, /* pci.ids */
    {0x10de, 0x397, "G73M [GeForce Go 7700]"}, /* pci.ids */
    {0x10de, 0x399, "G73M [GeForce Go 7600 GT]"}, /* pci.ids */
    {0x10de, 0x39a, "G73M [Quadro NVS 300M]"}, /* pci.ids */
    {0x10de, 0x39b, "G73M [GeForce Go 7900 SE]"}, /* pci.ids */
    {0x10de, 0x39c, "G73GLM [Quadro FX 550M]"}, /* pci.ids */
    {0x10de, 0x39e, "G73GL [Quadro FX 560]"}, /* pci.ids */
    {0x10de, 0x400, "G84 [GeForce 8600 GTS]"}, /* pci.ids */
    {0x10de, 0x401, "G84 [GeForce 8600 GT]"}, /* pci.ids */
    {0x10de, 0x403, "G84 [GeForce 8600 GS]"}, /* pci.ids */
    {0x10de, 0x404, "G84 [GeForce 8400 GS]"}, /* pci.ids */
    {0x10de, 0x405, "G84M [GeForce 9500M GS]"}, /* pci.ids */
    {0x10de, 0x406, "G84 [GeForce 8300 GS]"}, /* pci.ids */
    {0x10de, 0x407, "G84M [GeForce 8600M GT]"}, /* pci.ids */
    {0x10de, 0x408, "G84M [GeForce 9650M GS]"}, /* pci.ids */
    {0x10de, 0x409, "G84M [GeForce 8700M GT]"}, /* pci.ids */
    {0x10de, 0x40a, "G84GL [Quadro FX 370]"}, /* pci.ids */
    {0x10de, 0x40b, "G84GLM [Quadro NVS 320M]"}, /* pci.ids */
    {0x10de, 0x40c, "G84GLM [Quadro FX 570M]"}, /* pci.ids */
    {0x10de, 0x40d, "G84GLM [Quadro FX 1600M]"}, /* pci.ids */
    {0x10de, 0x40e, "G84GL [Quadro FX 570]"}, /* pci.ids */
    {0x10de, 0x40f, "G84GL [Quadro FX 1700]"}, /* pci.ids */
    {0x10de, 0x410, "G92 [GeForce GT 330]"}, /* pci.ids */
    {0x10de, 0x414, "G92 [GeForce 9800 GT]"}, /* pci.ids */
    {0x10de, 0x418, "G92 [GeForce GT 330 OEM]"}, /* pci.ids */
    {0x10de, 0x420, "G86 [GeForce 8400 SE]"}, /* pci.ids */
    {0x10de, 0x421, "G86 [GeForce 8500 GT]"}, /* pci.ids */
    {0x10de, 0x422, "G86 [GeForce 8400 GS]"}, /* pci.ids */
    {0x10de, 0x423, "G86 [GeForce 8300 GS]"}, /* pci.ids */
    {0x10de, 0x425, "G86M [GeForce 8600M GS]"}, /* pci.ids */
    {0x10de, 0x426, "G86M [GeForce 8400M GT]"}, /* pci.ids */
    {0x10de, 0x427, "G86M [GeForce 8400M GS]"}, /* pci.ids */
    {0x10de, 0x428, "G86M [GeForce 8400M G]"}, /* pci.ids */
    {0x10de, 0x429, "G86M [Quadro NVS 140M]"}, /* pci.ids */
    {0x10de, 0x42a, "G86M [Quadro NVS 130M]"}, /* pci.ids */
    {0x10de, 0x42b, "G86M [Quadro NVS 135M]"}, /* pci.ids */
    {0x10de, 0x42c, "G86 [GeForce 9400 GT]"}, /* pci.ids */
    {0x10de, 0x42d, "G86GLM [Quadro FX 360M]"}, /* pci.ids */
    {0x10de, 0x42e, "G86M [GeForce 9300M G]"}, /* pci.ids */
    {0x10de, 0x42f, "G86 [Quadro NVS 290]"}, /* pci.ids */
    {0x10de, 0x531, "C67 [GeForce 7150M / nForce 630M]"}, /* pci.ids */
    {0x10de, 0x533, "C67 [GeForce 7000M / nForce 610M]"}, /* pci.ids */
    {0x10de, 0x53a, "C68 [GeForce 7050 PV / nForce 630a]"}, /* pci.ids */
    {0x10de, 0x53e, "C68 [GeForce 7025 / nForce 630a]"}, /* pci.ids */
    {0x10de, 0x568, "MCP78S [GeForce 8200] Memory Controller"}, /* pci.ids */
    {0x10de, 0x5be, "NF200 PCIe 2.0 switch for Quadro Plex S4 / Tesla S870 / Te"}, /* pci.ids */
    {0x10de, 0x5e0, "GT200b [GeForce GTX 295]"}, /* pci.ids */
    {0x10de, 0x5e1, "GT200 [GeForce GTX 280]"}, /* pci.ids */
    {0x10de, 0x5e2, "GT200 [GeForce GTX 260]"}, /* pci.ids */
    {0x10de, 0x5e3, "GT200b [GeForce GTX 285]"}, /* pci.ids */
    {0x10de, 0x5e6, "GT200b [GeForce GTX 275]"}, /* pci.ids */
    {0x10de, 0x5e7, "GT200GL [Tesla C1060 / M1060]"}, /* pci.ids */
    {0x10de, 0x5eb, "GT200 [GeForce GTX 295]"}, /* pci.ids */
    {0x10de, 0x5ed, "GT200GL [Quadro Plex 2200 D2]"}, /* pci.ids */
    {0x10de, 0x5f8, "GT200GL [Quadro Plex 2200 S4]"}, /* pci.ids */
    {0x10de, 0x5f9, "GT200GL [Quadro CX]"}, /* pci.ids */
    {0x10de, 0x5fd, "GT200GL [Quadro FX 5800]"}, /* pci.ids */
    {0x10de, 0x5fe, "GT200GL [Quadro FX 4800]"}, /* pci.ids */
    {0x10de, 0x5ff, "GT200GL [Quadro FX 3800]"}, /* pci.ids */
    {0x10de, 0x600, "G92 [GeForce 8800 GTS 512]"}, /* pci.ids */
    {0x10de, 0x602, "G92 [GeForce 8800 GT]"}, /* pci.ids */
    {0x10de, 0x603, "G92 [GeForce GT 230 OEM]"}, /* pci.ids */
    {0x10de, 0x604, "G92 [GeForce 9800 GX2]"}, /* pci.ids */
    {0x10de, 0x606, "G92 [GeForce 8800 GS]"}, /* pci.ids */
    {0x10de, 0x607, "G92 [GeForce GTS 240]"}, /* pci.ids */
    {0x10de, 0x608, "G92M [GeForce 9800M GTX]"}, /* pci.ids */
    {0x10de, 0x609, "G92M [GeForce 8800M GTS]"}, /* pci.ids */
    {0x10de, 0x60a, "G92M [GeForce GTX 280M]"}, /* pci.ids */
    {0x10de, 0x60b, "G92M [GeForce 9800M GT]"}, /* pci.ids */
    {0x10de, 0x60c, "G92M [GeForce 8800M GTX]"}, /* pci.ids */
    {0x10de, 0x60f, "G92M [GeForce GTX 285M]"}, /* pci.ids */
    {0x10de, 0x610, "G92 [GeForce 9600 GSO]"}, /* pci.ids */
    {0x10de, 0x612, "G92 [GeForce 9800 GTX / 9800 GTX+]"}, /* pci.ids */
    {0x10de, 0x613, "G92 [GeForce 9800 GTX+]"}, /* pci.ids */
    {0x10de, 0x615, "G92 [GeForce GTS 250]"}, /* pci.ids */
    {0x10de, 0x618, "G92M [GeForce GTX 260M]"}, /* pci.ids */
    {0x10de, 0x619, "G92GL [Quadro FX 4700 X2]"}, /* pci.ids */
    {0x10de, 0x61a, "G92GL [Quadro FX 3700]"}, /* pci.ids */
    {0x10de, 0x61b, "G92GL [Quadro VX 200]"}, /* pci.ids */
    {0x10de, 0x61c, "G92GLM [Quadro FX 3600M]"}, /* pci.ids */
    {0x10de, 0x61d, "G92GLM [Quadro FX 2800M]"}, /* pci.ids */
    {0x10de, 0x61e, "G92GLM [Quadro FX 3700M]"}, /* pci.ids */
    {0x10de, 0x61f, "G92GLM [Quadro FX 3800M]"}, /* pci.ids */
    {0x10de, 0x620, "G94 [GeForce 9800 GT]"}, /* pci.ids */
    {0x10de, 0x621, "G94 [GeForce GT 230]"}, /* pci.ids */
    {0x10de, 0x622, "G94 [GeForce 9600 GT]"}, /* pci.ids */
    {0x10de, 0x623, "G94 [GeForce 9600 GS]"}, /* pci.ids */
    {0x10de, 0x624, "G94 [GeForce 9600 GT Green Edition]"}, /* pci.ids */
    {0x10de, 0x625, "G94 [GeForce 9600 GSO 512]"}, /* pci.ids */
    {0x10de, 0x626, "G94 [GeForce GT 130]"}, /* pci.ids */
    {0x10de, 0x627, "G94 [GeForce GT 140]"}, /* pci.ids */
    {0x10de, 0x628, "G94M [GeForce 9800M GTS]"}, /* pci.ids */
    {0x10de, 0x62a, "G94M [GeForce 9700M GTS]"}, /* pci.ids */
    {0x10de, 0x62b, "G94M [GeForce 9800M GS]"}, /* pci.ids */
    {0x10de, 0x62f, "G94 [GeForce 9800 S]"}, /* pci.ids */
    {0x10de, 0x631, "G94M [GeForce GTS 160M]"}, /* pci.ids */
    {0x10de, 0x632, "G94M [GeForce GTS 150M]"}, /* pci.ids */
    {0x10de, 0x633, "G94 [GeForce GT 220]"}, /* pci.ids */
    {0x10de, 0x635, "G94 [GeForce 9600 GSO]"}, /* pci.ids */
    {0x10de, 0x638, "G94GL [Quadro FX 1800]"}, /* pci.ids */
    {0x10de, 0x63a, "G94GLM [Quadro FX 2700M]"}, /* pci.ids */
    {0x10de, 0x63f, "G94 [GeForce 9600 GE]"}, /* pci.ids */
    {0x10de, 0x640, "G96C [GeForce 9500 GT]"}, /* pci.ids */
    {0x10de, 0x641, "G96C [GeForce 9400 GT]"}, /* pci.ids */
    {0x10de, 0x643, "G96 [GeForce 9500 GT]"}, /* pci.ids */
    {0x10de, 0x644, "G96 [GeForce 9500 GS]"}, /* pci.ids */
    {0x10de, 0x645, "G96C [GeForce 9500 GS]"}, /* pci.ids */
    {0x10de, 0x646, "G96C [GeForce GT 120]"}, /* pci.ids */
    {0x10de, 0x647, "G96CM [GeForce 9600M GT]"}, /* pci.ids */
    {0x10de, 0x648, "G96CM [GeForce 9600M GS]"}, /* pci.ids */
    {0x10de, 0x64a, "G96M [GeForce 9700M GT]"}, /* pci.ids */
    {0x10de, 0x64b, "G96M [GeForce 9500M G]"}, /* pci.ids */
    {0x10de, 0x64c, "G96CM [GeForce 9650M GT]"}, /* pci.ids */
    {0x10de, 0x64e, "G96C [GeForce 9600 GSO / 9800 GT]"}, /* pci.ids */
    {0x10de, 0x651, "G96CM [GeForce G 110M]"}, /* pci.ids */
    {0x10de, 0x652, "G96CM [GeForce GT 130M]"}, /* pci.ids */
    {0x10de, 0x653, "G96CM [GeForce GT 120M]"}, /* pci.ids */
    {0x10de, 0x654, "G96CM [GeForce GT 220M]"}, /* pci.ids */
    {0x10de, 0x655, "G96 [GeForce GT 120 Mac Edition]"}, /* pci.ids */
    {0x10de, 0x658, "G96GL [Quadro FX 380]"}, /* pci.ids */
    {0x10de, 0x659, "G96CGL [Quadro FX 580]"}, /* pci.ids */
    {0x10de, 0x65a, "G96GLM [Quadro FX 1700M]"}, /* pci.ids */
    {0x10de, 0x65c, "G96GLM [Quadro FX 770M]"}, /* pci.ids */
    {0x10de, 0x65d, "G96 [GeForce 9500 GA / 9600 GT / GTS 250]"}, /* pci.ids */
    {0x10de, 0x65f, "G96C [GeForce G210]"}, /* pci.ids */
    {0x10de, 0x6c0, "GF100 [GeForce GTX 480] (Fermi)"}, /* pci.ids */
    {0x10de, 0x6c4, "GF100 [GeForce GTX 465] (Fermi)"}, /* pci.ids */
    {0x10de, 0x6ca, "GF100M [GeForce GTX 480M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x6cd, "GF100 [GeForce GTX 470] (Fermi)"}, /* pci.ids */
    {0x10de, 0x6d1, "GF100GL [Tesla C2050 / C2070] (Fermi)"}, /* pci.ids */
    {0x10de, 0x6d2, "GF100GL [Tesla M2070] (Fermi)"}, /* pci.ids */
    {0x10de, 0x6d8, "GF100GL [Quadro 6000] (Fermi)"}, /* pci.ids */
    {0x10de, 0x6d9, "GF100GL [Quadro 5000] (Fermi)"}, /* pci.ids */
    {0x10de, 0x6da, "GF100GLM [Quadro 5000M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x6dd, "GF100GL [Quadro 4000] (Fermi)"}, /* pci.ids */
    {0x10de, 0x6de, "GF100GL [Tesla T20 Processor] (Fermi)"}, /* pci.ids */
    {0x10de, 0x6df, "GF100GL [Tesla M2070-Q] (Fermi)"}, /* pci.ids */
    {0x10de, 0x6e0, "G98 [GeForce 9300 GE]"}, /* pci.ids */
    {0x10de, 0x6e1, "G98 [GeForce 9300 GS]"}, /* pci.ids */
    {0x10de, 0x6e2, "G98 [GeForce 8400]"}, /* pci.ids */
    {0x10de, 0x6e3, "G98 [GeForce 8300 GS]"}, /* pci.ids */
    {0x10de, 0x6e5, "G98M [GeForce 9300M GS]"}, /* pci.ids */
    {0x10de, 0x6e6, "G98 [GeForce G 100]"}, /* pci.ids */
    {0x10de, 0x6e7, "G98 [GeForce 9300 SE]"}, /* pci.ids */
    {0x10de, 0x6ea, "G98M [Quadro NVS 150M]"}, /* pci.ids */
    {0x10de, 0x6eb, "G98M [Quadro NVS 160M]"}, /* pci.ids */
    {0x10de, 0x6ec, "G98M [GeForce G 105M]"}, /* pci.ids */
    {0x10de, 0x6ed, "G98 [GeForce 9600 GT / 9800 GT]"}, /* pci.ids */
    {0x10de, 0x6ee, "G98 [GeForce 9600 GT / 9800 GT / GT 240]"}, /* pci.ids */
    {0x10de, 0x6ef, "G98M [GeForce G 103M]"}, /* pci.ids */
    {0x10de, 0x6f8, "G98 [Quadro NVS 420]"}, /* pci.ids */
    {0x10de, 0x6f9, "G98GL [Quadro FX 370 LP]"}, /* pci.ids */
    {0x10de, 0x6fa, "G98 [Quadro NVS 450]"}, /* pci.ids */
    {0x10de, 0x6fb, "G98GLM [Quadro FX 370M]"}, /* pci.ids */
    {0x10de, 0x6fd, "G98 [Quadro NVS 295]"}, /* pci.ids */
    {0x10de, 0x753, "MCP78S [GeForce 8200] Co-Processor"}, /* pci.ids */
    {0x10de, 0x7cb, "nForce 610i/630i memory controller"}, /* pci.ids */
    {0x10de, 0x7e0, "C73 [GeForce 7150 / nForce 630i]"}, /* pci.ids */
    {0x10de, 0x7e2, "C73 [GeForce 7050 / nForce 630i]"}, /* pci.ids */
    {0x10de, 0x7e3, "C73 [GeForce 7050 / nForce 610i]"}, /* pci.ids */
    {0x10de, 0x7e5, "C73 [GeForce 7100 / nForce 620i]"}, /* pci.ids */
    {0x10de, 0x840, "C77 [GeForce 8200M]"}, /* pci.ids */
    {0x10de, 0x844, "C77 [GeForce 9100M G]"}, /* pci.ids */
    {0x10de, 0x845, "C77 [GeForce 8200M G]"}, /* pci.ids */
    {0x10de, 0x846, "C77 [GeForce 9200]"}, /* pci.ids */
    {0x10de, 0x847, "C78 [GeForce 9100]"}, /* pci.ids */
    {0x10de, 0x848, "C77 [GeForce 8300]"}, /* pci.ids */
    {0x10de, 0x849, "C77 [GeForce 8200]"}, /* pci.ids */
    {0x10de, 0x84a, "C77 [nForce 730a]"}, /* pci.ids */
    {0x10de, 0x84c, "C77 [nForce 780a/980a SLI]"}, /* pci.ids */
    {0x10de, 0x84d, "C77 [nForce 750a SLI]"}, /* pci.ids */
    {0x10de, 0x84f, "C77 [GeForce 8100 / nForce 720a]"}, /* pci.ids */
    {0x10de, 0x860, "C79 [GeForce 9300]"}, /* pci.ids */
    {0x10de, 0x861, "C79 [GeForce 9400]"}, /* pci.ids */
    {0x10de, 0x862, "C79 [GeForce 9400M G]"}, /* pci.ids */
    {0x10de, 0x863, "C79 [GeForce 9400M]"}, /* pci.ids */
    {0x10de, 0x865, "C79 [GeForce 9300 / ION]"}, /* pci.ids */
    {0x10de, 0x868, "C79 [nForce 760i SLI]"}, /* pci.ids */
    {0x10de, 0x869, "MCP7A [GeForce 9400]"}, /* pci.ids */
    {0x10de, 0x86c, "C79 [GeForce 9300 / nForce 730i]"}, /* pci.ids */
    {0x10de, 0x86d, "C79 [GeForce 9200]"}, /* pci.ids */
    {0x10de, 0x86e, "C79 [GeForce 9100M G]"}, /* pci.ids */
    {0x10de, 0x86f, "MCP79 [GeForce 8200M G]"}, /* pci.ids */
    {0x10de, 0x872, "C79 [GeForce G102M]"}, /* pci.ids */
    {0x10de, 0x876, "C79 [GeForce 9400M / ION]"}, /* pci.ids */
    {0x10de, 0x8a0, "MCP89 [GeForce 320M]"}, /* pci.ids */
    {0x10de, 0xa20, "GT216 [GeForce GT 220]"}, /* pci.ids */
    {0x10de, 0xa21, "GT216M [GeForce GT 330M]"}, /* pci.ids */
    {0x10de, 0xa22, "GT216 [GeForce 315]"}, /* pci.ids */
    {0x10de, 0xa23, "GT216 [GeForce 210]"}, /* pci.ids */
    {0x10de, 0xa24, "GT216 [GeForce 405]"}, /* pci.ids */
    {0x10de, 0xa28, "GT216M [GeForce GT 230M]"}, /* pci.ids */
    {0x10de, 0xa2c, "GT216M [NVS 5100M]"}, /* pci.ids */
    {0x10de, 0xa2d, "GT216M [GeForce GT 320M]"}, /* pci.ids */
    {0x10de, 0xa30, "GT216 [GeForce 505]"}, /* pci.ids */
    {0x10de, 0xa32, "GT216 [GeForce GT 415]"}, /* pci.ids */
    {0x10de, 0xa34, "GT216M [GeForce GT 240M]"}, /* pci.ids */
    {0x10de, 0xa35, "GT216M [GeForce GT 325M]"}, /* pci.ids */
    {0x10de, 0xa38, "GT216GL [Quadro 400]"}, /* pci.ids */
    {0x10de, 0xa3c, "GT216GLM [Quadro FX 880M]"}, /* pci.ids */
    {0x10de, 0xa60, "GT218 [GeForce G210]"}, /* pci.ids */
    {0x10de, 0xa62, "GT218 [GeForce 205]"}, /* pci.ids */
    {0x10de, 0xa63, "GT218 [GeForce 310]"}, /* pci.ids */
    {0x10de, 0xa65, "GT218 [GeForce 210]"}, /* pci.ids */
    {0x10de, 0xa67, "GT218 [GeForce 315]"}, /* pci.ids */
    {0x10de, 0xa68, "GT218M [GeForce G 105M]"}, /* pci.ids */
    {0x10de, 0xa6a, "GT218M [NVS 2100M]"}, /* pci.ids */
    {0x10de, 0xa6c, "GT218M [NVS 3100M]"}, /* pci.ids */
    {0x10de, 0xa6e, "GT218M [GeForce 305M]"}, /* pci.ids */
    {0x10de, 0xa70, "GT218M [GeForce 310M]"}, /* pci.ids */
    {0x10de, 0xa74, "GT218M [GeForce G210M]"}, /* pci.ids */
    {0x10de, 0xa78, "GT218GL [Quadro FX 380 LP]"}, /* pci.ids */
    {0x10de, 0xa7a, "GT218M [GeForce 315M]"}, /* pci.ids */
    {0x10de, 0xa7b, "GT218 [GeForce 505]"}, /* pci.ids */
    {0x10de, 0xa7c, "GT218GLM [Quadro FX 380M]"}, /* pci.ids */
    {0x10de, 0xad4, "MCP78S [GeForce 8200] AHCI Controller"}, /* pci.ids */
    {0x10de, 0xca0, "GT215 [GeForce GT 330]"}, /* pci.ids */
    {0x10de, 0xca2, "GT215 [GeForce GT 320]"}, /* pci.ids */
    {0x10de, 0xca3, "GT215 [GeForce GT 240]"}, /* pci.ids */
    {0x10de, 0xca4, "GT215 [GeForce GT 340]"}, /* pci.ids */
    {0x10de, 0xca5, "GT215 [GeForce GT 220]"}, /* pci.ids */
    {0x10de, 0xca8, "GT215M [GeForce GTS 260M]"}, /* pci.ids */
    {0x10de, 0xca9, "GT215M [GeForce GTS 250M]"}, /* pci.ids */
    {0x10de, 0xcac, "GT215 [GeForce GT 220/315]"}, /* pci.ids */
    {0x10de, 0xcaf, "GT215M [GeForce GT 335M]"}, /* pci.ids */
    {0x10de, 0xcb0, "GT215M [GeForce GTS 350M]"}, /* pci.ids */
    {0x10de, 0xcb1, "GT215M [GeForce GTS 360M]"}, /* pci.ids */
    {0x10de, 0xcbc, "GT215GLM [Quadro FX 1800M]"}, /* pci.ids */
    {0x10de, 0xdc0, "GF106 [GeForce GT 440] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdc4, "GF106 [GeForce GTS 450] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdc5, "GF106 [GeForce GTS 450 OEM] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdcd, "GF106M [GeForce GT 555M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdd1, "GF106M [GeForce GTX 460M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdd2, "GF106M [GeForce GT 445M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdd3, "GF106M [GeForce GT 435M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdd6, "GF106M [GeForce GT 550M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdd8, "GF106GL [Quadro 2000] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdda, "GF106GLM [Quadro 2000M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xde0, "GF108 [GeForce GT 440] (Fermi)"}, /* pci.ids */
    {0x10de, 0xde1, "GF108 [GeForce GT 430] (Fermi)"}, /* pci.ids */
    {0x10de, 0xde2, "GF108 [GeForce GT 420] (Fermi)"}, /* pci.ids */
    {0x10de, 0xde3, "GF108M [GeForce GT 635M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xde4, "GF108 [GeForce GT 520] (Fermi)"}, /* pci.ids */
    {0x10de, 0xde5, "GF108 [GeForce GT 530] (Fermi)"}, /* pci.ids */
    {0x10de, 0xde7, "GF108 [GeForce GT 610] (Fermi)"}, /* pci.ids */
    {0x10de, 0xde8, "GF108M [GeForce GT 620M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xde9, "GF108M [GeForce GT 620M/630M/635M/640M LE] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdea, "GF108M [GeForce 610M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdeb, "GF108M [GeForce GT 555M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdec, "GF108M [GeForce GT 525M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xded, "GF108M [GeForce GT 520M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdee, "GF108M [GeForce GT 415M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdef, "GF108M [NVS 5400M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdf0, "GF108M [GeForce GT 425M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdf1, "GF108M [GeForce GT 420M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdf2, "GF108M [GeForce GT 435M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdf4, "GF108M [GeForce GT 540M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdf6, "GF108M [GeForce GT 550M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdf8, "GF108GL [Quadro 600] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdf9, "GF108GLM [Quadro 500M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdfa, "GF108GLM [Quadro 1000M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xdfc, "GF108GLM [NVS 5200M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xe22, "GF104 [GeForce GTX 460] (Fermi)"}, /* pci.ids */
    {0x10de, 0xe23, "GF104 [GeForce GTX 460 SE] (Fermi)"}, /* pci.ids */
    {0x10de, 0xe24, "GF104 [GeForce GTX 460 OEM] (Fermi)"}, /* pci.ids */
    {0x10de, 0xe30, "GF104M [GeForce GTX 470M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xe31, "GF104M [GeForce GTX 485M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xe3a, "GF104GLM [Quadro 3000M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xe3b, "GF104GLM [Quadro 4000M] (Fermi)"}, /* pci.ids */
    {0x10de, 0xf00, "GF108 [GeForce GT 630] (Fermi)"}, /* pci.ids */
    {0x10de, 0xf01, "GF108 [GeForce GT 620] (Fermi)"}, /* pci.ids */
    {0x10de, 0xf02, "GF108 [GeForce GT 730] (Fermi)"}, /* pci.ids */
    {0x10de, 0xfc0, "GK107 [GeForce GT 640 OEM] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfc1, "GK107 [GeForce GT 640] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfc2, "GK107 [GeForce GT 630 OEM] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfc5, "GK107 [GeForce GT 1030] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfc6, "GK107 [GeForce GTX 650] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfc8, "GK107 [GeForce GT 740] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfc9, "GK107 [GeForce GT 730] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfcc, "GK107 [GeForce GT 720] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfcd, "GK107M [GeForce GT 755M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfce, "GK107M [GeForce GT 640M LE] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfd1, "GK107M [GeForce GT 650M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfd2, "GK107M [GeForce GT 640M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfd4, "GK107M [GeForce GTX 660M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfd5, "GK107M [GeForce GT 650M Mac Edition] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfd8, "GK107M [GeForce GT 640M Mac Edition] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfd9, "GK107M [GeForce GT 645M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfdf, "GK107M [GeForce GT 740M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfe0, "GK107M [GeForce GTX 660M Mac Edition] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfe1, "GK107M [GeForce GT 730M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfe2, "GK107M [GeForce GT 745M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfe4, "GK107M [GeForce GT 750M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfe5, "GK107 [GeForce K340 USM] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfe6, "GK107 [GRID K1 NVS USM] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfe9, "GK107M [GeForce GT 750M Mac Edition] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfea, "GK107M [GeForce GT 755M Mac Edition] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfec, "GK107M [GeForce 710A] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfed, "GK107M [GeForce 820M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfee, "GK107M [GeForce 810M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xff1, "GK107 [NVS 1000] (Kepler)"}, /* pci.ids */
    {0x10de, 0xff3, "GK107GL [Quadro K420] (Kepler)"}, /* pci.ids */
    {0x10de, 0xff5, "GK107GL [GRID K1 Tesla USM] (Kepler)"}, /* pci.ids */
    {0x10de, 0xff6, "GK107GLM [Quadro K1100M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xff8, "GK107GLM [Quadro K500M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xff9, "GK107GL [Quadro K2000D] (Kepler)"}, /* pci.ids */
    {0x10de, 0xffa, "GK107GL [Quadro K600] (Kepler)"}, /* pci.ids */
    {0x10de, 0xffb, "GK107GLM [Quadro K2000M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xffc, "GK107GLM [Quadro K1000M] (Kepler)"}, /* pci.ids */
    {0x10de, 0xffd, "GK107 [NVS 510] (Kepler)"}, /* pci.ids */
    {0x10de, 0xffe, "GK107GL [Quadro K2000] (Kepler)"}, /* pci.ids */
    {0x10de, 0xfff, "GK107GL [Quadro 410] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1001, "GK110B [GeForce GTX TITAN Z] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1003, "GK110 [GeForce GTX Titan LE] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1004, "GK110 [GeForce GTX 780] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1005, "GK110 [GeForce GTX TITAN] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1007, "GK110 [GeForce GTX 780 Rev. 2] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1008, "GK110 [GeForce GTX 780 Ti 6GB] (Kepler)"}, /* pci.ids */
    {0x10de, 0x100a, "GK110B [GeForce GTX 780 Ti] (Kepler)"}, /* pci.ids */
    {0x10de, 0x100c, "GK110B [GeForce GTX TITAN Black] (Kepler)"}, /* pci.ids */
    {0x10de, 0x101e, "GK110GL [Tesla K20X] (Kepler)"}, /* pci.ids */
    {0x10de, 0x101f, "GK110GL [Tesla K20] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1021, "GK110GL [Tesla K20Xm] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1022, "GK110GL [Tesla K20c] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1023, "GK110BGL [Tesla K40m] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1024, "GK180GL [Tesla K40c] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1026, "GK110GL [Tesla K20s] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1027, "GK110BGL [Tesla K40st] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1028, "GK110GL [Tesla K20m] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1029, "GK110BGL [Tesla K40s] (Kepler)"}, /* pci.ids */
    {0x10de, 0x102a, "GK110BGL [Tesla K40t] (Kepler)"}, /* pci.ids */
    {0x10de, 0x102d, "GK210GL [Tesla K80] (Kepler)"}, /* pci.ids */
    {0x10de, 0x102e, "GK110BGL [Tesla K40d] (Kepler)"}, /* pci.ids */
    {0x10de, 0x102f, "GK110BGL [Tesla Stella Solo] (Kepler)"}, /* pci.ids */
    {0x10de, 0x103a, "GK110GL [Quadro K6000] (Kepler)"}, /* pci.ids */
    {0x10de, 0x103c, "GK110GL [Quadro K5200] (Kepler)"}, /* pci.ids */
    {0x10de, 0x103f, "GK110BGL [Tesla Stella SXM] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1040, "GF119 [GeForce GT 520] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1042, "GF119 [GeForce 510] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1048, "GF119 [GeForce 605] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1049, "GF119 [GeForce GT 620 OEM] (Fermi)"}, /* pci.ids */
    {0x10de, 0x104a, "GF119 [GeForce GT 610] (Fermi)"}, /* pci.ids */
    {0x10de, 0x104b, "GF119 [GeForce GT 625 OEM] (Fermi)"}, /* pci.ids */
    {0x10de, 0x104c, "GF119 [GeForce GT 705] (Fermi)"}, /* pci.ids */
    {0x10de, 0x104d, "GF119 [GeForce GT 710] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1050, "GF119M [GeForce GT 520M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1051, "GF119M [GeForce GT 520MX] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1054, "GF119M [GeForce 410M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1056, "GF119M [NVS 4200M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1057, "GF119M [Quadro NVS 4200M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1058, "GF119M [GeForce 610M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x105b, "GF119M [GeForce 705M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x107c, "GF119 [NVS 315] (Fermi)"}, /* pci.ids */
    {0x10de, 0x107d, "GF119 [NVS 310] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1080, "GF110 [GeForce GTX 580] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1081, "GF110 [GeForce GTX 570] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1082, "GF110 [GeForce GTX 560 Ti OEM] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1084, "GF110 [GeForce GTX 560 OEM] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1086, "GF110 [GeForce GTX 570 Rev. 2] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1087, "GF110 [GeForce GTX 560 Ti 448 Cores] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1088, "GF110 [GeForce GTX 590] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1089, "GF110 [GeForce GTX 580 Rev. 2] (Fermi)"}, /* pci.ids */
    {0x10de, 0x108e, "GF110GL [Tesla C2090] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1091, "GF110GL [Tesla M2090] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1094, "GF110GL [Tesla M2075] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1096, "GF110GL [Tesla C2050 / C2075] (Fermi)"}, /* pci.ids */
    {0x10de, 0x109a, "GF100GLM [Quadro 5010M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x109b, "GF100GL [Quadro 7000] (Fermi)"}, /* pci.ids */
    {0x10de, 0x10c0, "GT218 [GeForce 9300 GS Rev. 2]"}, /* pci.ids */
    {0x10de, 0x10c3, "GT218 [GeForce 8400 GS Rev. 3]"}, /* pci.ids */
    {0x10de, 0x10c5, "GT218 [GeForce 405]"}, /* pci.ids */
    {0x10de, 0x10d8, "GT218 [NVS 300]"}, /* pci.ids */
    {0x10de, 0x1140, "GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/72"}, /* pci.ids */
    {0x10de, 0x1180, "GK104 [GeForce GTX 680] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1182, "GK104 [GeForce GTX 760 Ti] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1183, "GK104 [GeForce GTX 660 Ti] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1184, "GK104 [GeForce GTX 770] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1185, "GK104 [GeForce GTX 660 OEM] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1187, "GK104 [GeForce GTX 760] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1188, "GK104 [GeForce GTX 690] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1189, "GK104 [GeForce GTX 670] (Kepler)"}, /* pci.ids */
    {0x10de, 0x118b, "GK104GL [GRID K2 GeForce USM] (Kepler)"}, /* pci.ids */
    {0x10de, 0x118c, "GK104 [GRID K2 NVS USM] (Kepler)"}, /* pci.ids */
    {0x10de, 0x118e, "GK104 [GeForce GTX 760 OEM] (Kepler)"}, /* pci.ids */
    {0x10de, 0x118f, "GK104GL [Tesla K10] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1191, "GK104 [GeForce GTX 760 Rev. 2] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1193, "GK104 [GeForce GTX 760 Ti OEM] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1194, "GK104GL [Tesla K8] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1195, "GK104 [GeForce GTX 660 Rev. 2] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1198, "GK104M [GeForce GTX 880M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1199, "GK104M [GeForce GTX 870M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x119a, "GK104M [GeForce GTX 860M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x119d, "GK104M [GeForce GTX 775M Mac Edition] (Kepler)"}, /* pci.ids */
    {0x10de, 0x119e, "GK104M [GeForce GTX 780M Mac Edition] (Kepler)"}, /* pci.ids */
    {0x10de, 0x119f, "GK104M [GeForce GTX 780M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11a0, "GK104M [GeForce GTX 680M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11a1, "GK104M [GeForce GTX 670MX] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11a2, "GK104M [GeForce GTX 675MX Mac Edition] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11a3, "GK104M [GeForce GTX 680MX] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11a7, "GK104M [GeForce GTX 675MX] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11a8, "GK104GLM [Quadro K5100M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11b1, "GK104GL [GRID K2 Tesla USM] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11b4, "GK104GL [Quadro K4200] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11b6, "GK104GLM [Quadro K3100M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11b7, "GK104GLM [Quadro K4100M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11ba, "GK104GL [Quadro K5000] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11bb, "GK104GL [Quadro 4100] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11bc, "GK104GLM [Quadro K5000M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11bd, "GK104GLM [Quadro K4000M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11be, "GK104GLM [Quadro K3000M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11c0, "GK106 [GeForce GTX 660] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11c2, "GK106 [GeForce GTX 650 Ti Boost] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11c3, "GK106 [GeForce GTX 650 Ti OEM] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11c4, "GK106 [GeForce GTX 645 OEM] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11c5, "GK106 [GeForce GT 740] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11c6, "GK106 [GeForce GTX 650 Ti] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11c7, "GK106 [GeForce GTX 750 Ti] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11c8, "GK106 [GeForce GTX 650 OEM] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11e0, "GK106M [GeForce GTX 770M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11e1, "GK106M [GeForce GTX 765M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11e3, "GK106M [GeForce GTX 760M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11fa, "GK106GL [Quadro K4000] (Kepler)"}, /* pci.ids */
    {0x10de, 0x11fc, "GK106GLM [Quadro K2100M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1200, "GF114 [GeForce GTX 560 Ti] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1201, "GF114 [GeForce GTX 560] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1202, "GF114 [GeForce GTX 560 Ti OEM] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1203, "GF114 [GeForce GTX 460 SE v2] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1205, "GF114 [GeForce GTX 460 v2] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1206, "GF114 [GeForce GTX 555] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1207, "GF114 [GeForce GT 645 OEM] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1208, "GF114 [GeForce GTX 560 SE] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1210, "GF114M [GeForce GTX 570M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1211, "GF114M [GeForce GTX 580M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1212, "GF114M [GeForce GTX 675M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1213, "GF114M [GeForce GTX 670M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1241, "GF116 [GeForce GT 545 OEM] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1243, "GF116 [GeForce GT 545] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1244, "GF116 [GeForce GTX 550 Ti] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1245, "GF116 [GeForce GTS 450 Rev. 2] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1246, "GF116M [GeForce GT 550M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1247, "GF116M [GeForce GT 555M/635M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1249, "GF116 [GeForce GTS 450 Rev. 3] (Fermi)"}, /* pci.ids */
    {0x10de, 0x124b, "GF116 [GeForce GT 640 OEM] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1251, "GF116M [GeForce GT 560M] (Fermi)"}, /* pci.ids */
    {0x10de, 0x1280, "GK208 [GeForce GT 635] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1281, "GK208 [GeForce GT 710] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1282, "GK208 [GeForce GT 640 Rev. 2] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1284, "GK208 [GeForce GT 630 Rev. 2] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1286, "GK208 [GeForce GT 720] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1287, "GK208B [GeForce GT 730] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1288, "GK208B [GeForce GT 720] (Kepler)"}, /* pci.ids */
    {0x10de, 0x128b, "GK208B [GeForce GT 710] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1290, "GK208M [GeForce GT 730M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1291, "GK208M [GeForce GT 735M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1292, "GK208M [GeForce GT 740M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1295, "GK208M [GeForce 710M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1296, "GK208M [GeForce 825M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1298, "GK208M [GeForce GT 720M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1299, "GK208BM [GeForce 920M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x129a, "GK208BM [GeForce 910M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x12b9, "GK208GLM [Quadro K610M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x12ba, "GK208GLM [Quadro K510M] (Kepler)"}, /* pci.ids */
    {0x10de, 0x1340, "GM108M [GeForce 830M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1341, "GM108M [GeForce 840M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1344, "GM108M [GeForce 845M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1346, "GM108M [GeForce 930M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1347, "GM108M [GeForce 940M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1348, "GM108M [GeForce 945M / 945A] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x134b, "GM108M [GeForce 940MX] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x134e, "GM108M [GeForce 930MX] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x134f, "GM108M [GeForce 920MX] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x137a, "GM108GLM [Quadro K620M / Quadro M500M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x137b, "GM108GLM [Quadro M520 Mobile] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x137d, "GM108M [GeForce 940A] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1380, "GM107 [GeForce GTX 750 Ti] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1381, "GM107 [GeForce GTX 750] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1382, "GM107 [GeForce GTX 745] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1390, "GM107M [GeForce 845M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1391, "GM107M [GeForce GTX 850M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1392, "GM107M [GeForce GTX 860M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1393, "GM107M [GeForce 840M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1399, "GM107M [GeForce 945M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x139a, "GM107M [GeForce GTX 950M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x139b, "GM107M [GeForce GTX 960M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x139c, "GM107M [GeForce 940M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x139d, "GM107M [GeForce GTX 750 Ti] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13b0, "GM107GLM [Quadro M2000M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13b1, "GM107GLM [Quadro M1000M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13b2, "GM107GLM [Quadro M600M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13b3, "GM107GLM [Quadro K2200M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13b4, "GM107GLM [Quadro M620 Mobile] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13b6, "GM107GLM [Quadro M1200 Mobile] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13b9, "GM107GL [NVS 810] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13ba, "GM107GL [Quadro K2200] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13bb, "GM107GL [Quadro K620] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13bc, "GM107GL [Quadro K1200] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13bd, "GM107GL [Tesla M10] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13c0, "GM204 [GeForce GTX 980] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13c2, "GM204 [GeForce GTX 970] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13d7, "GM204M [GeForce GTX 980M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13d8, "GM204M [GeForce GTX 960 OEM / 970M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13d9, "GM204M [GeForce GTX 965M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13da, "GM204M [GeForce GTX 980 Mobile] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13e7, "GM204GL [GeForce GTX 980 Engineering Sample] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13f0, "GM204GL [Quadro M5000] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13f1, "GM204GL [Quadro M4000] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13f2, "GM204GL [Tesla M60] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13f3, "GM204GL [Tesla M6] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13f8, "GM204GLM [Quadro M5000M / M5000 SE] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13f9, "GM204GLM [Quadro M4000M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13fa, "GM204GLM [Quadro M3000M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x13fb, "GM204GLM [Quadro M5500] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1401, "GM206 [GeForce GTX 960] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1402, "GM206 [GeForce GTX 950] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1404, "GM206 [GeForce GTX 960 FAKE] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1406, "GM206 [GeForce GTX 960 OEM] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1407, "GM206 [GeForce GTX 750 v2] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1427, "GM206M [GeForce GTX 965M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1430, "GM206GL [Quadro M2000] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1431, "GM206GL [Tesla M4] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1436, "GM206GLM [Quadro M2200 Mobile] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x15f0, "GP100GL [Quadro GP100] (Pascal)"}, /* pci.ids */
    {0x10de, 0x15f7, "GP100GL [Tesla P100 PCIe 12GB] (Pascal)"}, /* pci.ids */
    {0x10de, 0x15f8, "GP100GL [Tesla P100 PCIe 16GB] (Pascal)"}, /* pci.ids */
    {0x10de, 0x15f9, "GP100GL [Tesla P100 SXM2 16GB] (Pascal)"}, /* pci.ids */
    {0x10de, 0x15fc, "GP100GL [Tesla P100-DGXS-16GB] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1618, "GM204M [GeForce GTX 970M] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1676, "GM204GLM [Quadro M2200 Mobile] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x174d, "GM108M [GeForce MX130] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x174e, "GM108M [GeForce MX110] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x179c, "GM107 [GeForce 940MX] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x17c2, "GM200 [GeForce GTX TITAN X] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x17c8, "GM200 [GeForce GTX 980 Ti] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x17f0, "GM200GL [Quadro M6000] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x17f1, "GM200GL [Quadro M6000 24GB] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x17fd, "GM200GL [Tesla M40] (Maxwell)"}, /* pci.ids */
    {0x10de, 0x1b01, "GP102 [GeForce GTX 1080 Ti 10GB] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1b06, "GP102 [GeForce GTX 1080 Ti] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1b30, "GP102GL [Quadro P6000] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1b38, "GP102GL [Tesla P40] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1b39, "GP102GL [Tesla P10] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1b80, "GP104 [GeForce GTX 1080] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1b81, "GP104 [GeForce GTX 1070] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1b82, "GP104 [GeForce GTX 1070 Ti] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1b83, "GP104 [GeForce GTX 1060 6GB] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1b84, "GP104 [GeForce GTX 1060 3GB] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1ba0, "GP104M [GeForce GTX 1080 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1ba1, "GP104M [GeForce GTX 1070 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1bad, "GP104 [GeForce GTX 1070 Engineering Sample] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1bb0, "GP104GL [Quadro P5000] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1bb1, "GP104GL [Quadro P4000] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1bb3, "GP104GL [Tesla P4] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1bb4, "GP104GL [Tesla P6] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1bb5, "GP104GLM [Quadro P5200 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1bb6, "GP104GLM [Quadro P5000 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1bb7, "GP104GLM [Quadro P4000 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1bb8, "GP104GLM [Quadro P3000 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1bb9, "GP104GLM [Quadro P4200 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1bbb, "GP104GLM [Quadro P3200 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1be0, "GP104BM [GeForce GTX 1080 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1be1, "GP104BM [GeForce GTX 1070 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c02, "GP106 [GeForce GTX 1060 3GB] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c03, "GP106 [GeForce GTX 1060 6GB] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c04, "GP106 [GeForce GTX 1060 5GB] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c06, "GP106 [GeForce GTX 1060 6GB Rev. 2] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c20, "GP106M [GeForce GTX 1060 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c21, "GP106M [GeForce GTX 1050 Ti Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c22, "GP106M [GeForce GTX 1050 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c23, "GP106M [GeForce GTX 1060 Mobile Rev. 2] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c30, "GP106GL [Quadro P2000] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c31, "GP106GL [Quadro P2200] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c35, "GP106M [Quadro P2000 Mobile / DRIVE PX 2 AutoChauffeur] (P"}, /* pci.ids */
    {0x10de, 0x1c60, "GP106BM [GeForce GTX 1060 Mobile 6GB] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c61, "GP106BM [GeForce GTX 1050 Ti Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c62, "GP106BM [GeForce GTX 1050 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c81, "GP107 [GeForce GTX 1050] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c82, "GP107 [GeForce GTX 1050 Ti] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c83, "GP107 [GeForce GTX 1050 3GB] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c8c, "GP107M [GeForce GTX 1050 Ti Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c8d, "GP107M [GeForce GTX 1050 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c8f, "GP107M [GeForce GTX 1050 Ti Max-Q] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c90, "GP107M [GeForce MX150] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c91, "GP107M [GeForce GTX 1050 3 GB Max-Q] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1c94, "GP107M [GeForce MX350] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1cb1, "GP107GL [Quadro P1000] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1cb2, "GP107GL [Quadro P600] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1cb3, "GP107GL [Quadro P400] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1cb6, "GP107GL [Quadro P620] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1cba, "GP107GLM [Quadro P2000 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1cbb, "GP107GLM [Quadro P1000 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1cbc, "GP107GLM [Quadro P600 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1cbd, "GP107GLM [Quadro P620] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1ccc, "GP107BM [GeForce GTX 1050 Ti Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1ccd, "GP107BM [GeForce GTX 1050 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1cfa, "GP107GL [Quadro P2000] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1d01, "GP108 [GeForce GT 1030] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1d02, "GP108 [GeForce GT 1010] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1d10, "GP108M [GeForce MX150] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1d11, "GP108M [GeForce MX230] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1d13, "GP108M [GeForce MX250] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1d16, "GP108M [GeForce MX330] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1d33, "GP108GLM [Quadro P500 Mobile] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1d34, "GP108GLM [Quadro P520] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1d52, "GP108BM [GeForce MX250] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1d56, "GP108BM [GeForce MX330] (Pascal)"}, /* pci.ids */
    {0x10de, 0x1db0, "GV100GL [Tesla GV100 SXM2-16GB SKU 890] (Volta)"}, /* pci.ids */
    {0x10de, 0x1db1, "GV100GL [Tesla V100 SXM2 16GB] (Volta)"}, /* pci.ids */
    {0x10de, 0x1db2, "GV100GL [Tesla V100 DGXS 16GB] (Volta)"}, /* pci.ids */
    {0x10de, 0x1db3, "GV100GL [Tesla V100 FHHL 16GB] (Volta)"}, /* pci.ids */
    {0x10de, 0x1db4, "GV100GL [Tesla V100 PCIe 16GB] (Volta)"}, /* pci.ids */
    {0x10de, 0x1db5, "GV100GL [Tesla V100 SXM2 32GB] (Volta)"}, /* pci.ids */
    {0x10de, 0x1db6, "GV100GL [Tesla V100 PCIe 32GB] (Volta)"}, /* pci.ids */
    {0x10de, 0x1db7, "GV100GL [Tesla V100 DGXS 32GB] (Volta)"}, /* pci.ids */
    {0x10de, 0x1db8, "GV100GL [Tesla V100 SXM3 32GB] (Volta)"}, /* pci.ids */
    {0x10de, 0x1dba, "GV100GL [Quadro GV100] (Volta)"}, /* pci.ids */
    {0x10de, 0x1dbd, "GV100GL [Tesla GV100 DGX1-V] (Volta)"}, /* pci.ids */
    {0x10de, 0x1df0, "GV100GL [Tesla PG500-216] (Volta)"}, /* pci.ids */
    {0x10de, 0x1df2, "GV100GL [Tesla PG503-216] (Volta)"}, /* pci.ids */
    {0x10de, 0x1df6, "GV100GL [Tesla V100S PCIe 32GB] (Volta)"}, /* pci.ids */
    {0x10de, 0x1e03, "TU102 [GeForce RTX 2080 Ti 12GB] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e04, "TU102 [GeForce RTX 2080 Ti] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e07, "TU102 [GeForce RTX 2080 Ti Rev. A] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e2d, "TU102 [GeForce RTX 2080 Ti Engineering Sample] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e2e, "TU102 [GeForce RTX 2080 Ti 12GB Engineering Sample] (Turin"}, /* pci.ids */
    {0x10de, 0x1e30, "TU102GL [Quadro RTX 6000/8000] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e35, "TU102GL [Tesla T10] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e36, "TU102GL [Quadro RTX 6000] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e37, "TU102GL [Tesla T10 16GB / GRID RTX T10-2/T10-4/T10-8] (Tur"}, /* pci.ids */
    {0x10de, 0x1e38, "TU102GL [Tesla T40 24GB] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e81, "TU104 [GeForce RTX 2080 SUPER] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e82, "TU104 [GeForce RTX 2080] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e84, "TU104 [GeForce RTX 2070 SUPER] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e87, "TU104 [GeForce RTX 2080 Rev. A] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e89, "TU104 [GeForce RTX 2060] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e90, "TU104M [GeForce RTX 2080 Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e91, "TU104M [GeForce RTX 2070 SUPER Mobile / Max-Q] (Turing)"}, /* pci.ids */
    {0x10de, 0x1e93, "TU104M [GeForce RTX 2080 SUPER Mobile / Max-Q] (Turing)"}, /* pci.ids */
    {0x10de, 0x1eae, "TU104M [GeForce GTX 2080 Engineering Sample] (Turing)"}, /* pci.ids */
    {0x10de, 0x1eb0, "TU104GL [Quadro RTX 5000] (Turing)"}, /* pci.ids */
    {0x10de, 0x1eb1, "TU104GL [Quadro RTX 4000] (Turing)"}, /* pci.ids */
    {0x10de, 0x1eb5, "TU104GLM [Quadro RTX 5000 Mobile / Max-Q] (Turing)"}, /* pci.ids */
    {0x10de, 0x1eb6, "TU104GLM [Quadro RTX 4000 Mobile / Max-Q] (Turing)"}, /* pci.ids */
    {0x10de, 0x1eb8, "TU104GL [Tesla T4] (Turing)"}, /* pci.ids */
    {0x10de, 0x1ed0, "TU104BM [GeForce RTX 2080 Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x1ed1, "TU104BM [GeForce RTX 2070 SUPER Mobile / Max-Q] (Turing)"}, /* pci.ids */
    {0x10de, 0x1ed3, "TU104BM [GeForce RTX 2080 SUPER Mobile / Max-Q] (Turing)"}, /* pci.ids */
    {0x10de, 0x1ef5, "TU104GLM [Quadro RTX 5000 Mobile Refresh] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f02, "TU106 [GeForce RTX 2070] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f03, "TU106 [GeForce RTX 2060 12GB] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f06, "TU106 [GeForce RTX 2060 SUPER] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f07, "TU106 [GeForce RTX 2070 Rev. A] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f08, "TU106 [GeForce RTX 2060 Rev. A] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f09, "TU106 [GeForce GTX 1660 SUPER] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f0a, "TU106 [GeForce GTX 1650] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f10, "TU106M [GeForce RTX 2070 Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f11, "TU106M [GeForce RTX 2060 Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f12, "TU106M [GeForce RTX 2060 Max-Q] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f14, "TU106M [GeForce RTX 2070 Mobile / Max-Q Refresh] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f36, "TU106GLM [Quadro RTX 3000 Mobile / Max-Q] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f50, "TU106BM [GeForce RTX 2070 Mobile / Max-Q] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f51, "TU106BM [GeForce RTX 2060 Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f54, "TU106BM [GeForce RTX 2070 Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f76, "TU106GLM [Quadro RTX 3000 Mobile Refresh] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f82, "TU117 [GeForce GTX 1650] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f83, "TU117 [GeForce GTX 1630] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f91, "TU117M [GeForce GTX 1650 Mobile / Max-Q] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f92, "TU117M [GeForce GTX 1650 Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f95, "TU117M [GeForce GTX 1650 Ti Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f97, "TU117M [GeForce MX450] (Turing)"}, /* pci.ids */
    {0x10de, 0x1f9f, "TU117M [GeForce MX550] (Turing)"}, /* pci.ids */
    {0x10de, 0x1fb0, "TU117GLM [Quadro T1000 Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x1fb2, "TU117GLM [Quadro T400 Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x1fb8, "TU117GLM [Quadro T2000 Mobile / Max-Q] (Turing)"}, /* pci.ids */
    {0x10de, 0x1fbb, "TU117GLM [Quadro T500 Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x1fd9, "TU117BM [GeForce GTX 1650 Mobile Refresh] (Turing)"}, /* pci.ids */
    {0x10de, 0x2182, "TU116 [GeForce GTX 1660 Ti] (Turing)"}, /* pci.ids */
    {0x10de, 0x2184, "TU116 [GeForce GTX 1660] (Turing)"}, /* pci.ids */
    {0x10de, 0x2187, "TU116 [GeForce GTX 1650 SUPER] (Turing)"}, /* pci.ids */
    {0x10de, 0x2188, "TU116 [GeForce GTX 1650] (Turing)"}, /* pci.ids */
    {0x10de, 0x2191, "TU116M [GeForce GTX 1660 Ti Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x2192, "TU116M [GeForce GTX 1650 Ti Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x21c4, "TU116 [GeForce GTX 1660 SUPER] (Turing)"}, /* pci.ids */
    {0x10de, 0x21d1, "TU116BM [GeForce GTX 1660 Ti Mobile] (Turing)"}, /* pci.ids */
    {0x10de, 0x2203, "GA102 [GeForce RTX 3090 Ti] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2204, "GA102 [GeForce RTX 3090] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2205, "GA102 [GeForce RTX 3080 Ti 20GB] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2206, "GA102 [GeForce RTX 3080] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2207, "GA102 [GeForce RTX 3070 Ti] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2208, "GA102 [GeForce RTX 3080 Ti] (Ampere)"}, /* pci.ids */
    {0x10de, 0x220a, "GA102 [GeForce RTX 3080 12GB] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2216, "GA102 [GeForce RTX 3080 Lite Hash Rate] (Ampere)"}, /* pci.ids */
    {0x10de, 0x222b, "GA102 [GeForce RTX 3090 Engineering Sample] (Ampere)"}, /* pci.ids */
    {0x10de, 0x222f, "GA102 [GeForce RTX 3080 11GB / 12GB Engineering Sample] (A"}, /* pci.ids */
    {0x10de, 0x2414, "GA103 [GeForce RTX 3060 Ti] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2420, "GA103M [GeForce RTX 3080 Ti Mobile] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2460, "GA103M [GeForce RTX 3080 Ti Laptop GPU] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2482, "GA104 [GeForce RTX 3070 Ti] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2484, "GA104 [GeForce RTX 3070] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2486, "GA104 [GeForce RTX 3060 Ti] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2487, "GA104 [GeForce RTX 3060] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2488, "GA104 [GeForce RTX 3070 Lite Hash Rate] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2489, "GA104 [GeForce RTX 3060 Ti Lite Hash Rate] (Ampere)"}, /* pci.ids */
    {0x10de, 0x249c, "GA104M [GeForce RTX 3080 Mobile / Max-Q 8GB/16GB] (Ampere)"}, /* pci.ids */
    {0x10de, 0x249d, "GA104M [GeForce RTX 3070 Mobile / Max-Q] (Ampere)"}, /* pci.ids */
    {0x10de, 0x24a0, "GA104 [Geforce RTX 3070 Ti Laptop GPU] (Ampere)"}, /* pci.ids */
    {0x10de, 0x24ac, "GA104 [GeForce RTX 30x0 Engineering Sample] (Ampere)"}, /* pci.ids */
    {0x10de, 0x24ad, "GA104 [GeForce RTX 3060 Engineering Sample] (Ampere)"}, /* pci.ids */
    {0x10de, 0x24af, "GA104 [GeForce RTX 3070 Engineering Sample] (Ampere)"}, /* pci.ids */
    {0x10de, 0x24c7, "GA104 [GeForce RTX 3060 8GB] (Ampere)"}, /* pci.ids */
    {0x10de, 0x24c8, "GA104 [GeForce RTX 3070 GDDR6X] (Ampere)"}, /* pci.ids */
    {0x10de, 0x24c9, "GA104 [GeForce RTX 3060 Ti GDDR6X] (Ampere)"}, /* pci.ids */
    {0x10de, 0x24e0, "GA104M [Geforce RTX 3070 Ti Laptop GPU] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2501, "GA106 [GeForce RTX 3060] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2504, "GA106 [GeForce RTX 3060 Lite Hash Rate] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2507, "GA106 [Geforce RTX 3050] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2508, "GA106 [GeForce RTX 3050 OEM] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2509, "GA106 [GeForce RTX 3060 12GB Rev. 2] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2520, "GA106M [GeForce RTX 3060 Mobile / Max-Q] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2521, "GA106M [GeForce RTX 3060 Laptop GPU] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2523, "GA106M [GeForce RTX 3050 Ti Mobile / Max-Q] (Ampere)"}, /* pci.ids */
    {0x10de, 0x252f, "GA106 [GeForce RTX 3060 Engineering Sample] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2582, "GA107 [GeForce RTX 3050 8GB] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2583, "GA107 [GeForce RTX 3050 4GB] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2584, "GA107 [GeForce RTX 3050 6GB] (Ampere)"}, /* pci.ids */
    {0x10de, 0x25a0, "GA107M [GeForce RTX 3050 Ti Mobile] (Ampere)"}, /* pci.ids */
    {0x10de, 0x25a2, "GA107M [GeForce RTX 3050 Mobile] (Ampere)"}, /* pci.ids */
    {0x10de, 0x25a6, "GA107M [GeForce MX570] (Ampere)"}, /* pci.ids */
    {0x10de, 0x25a9, "GA107M [GeForce RTX 2050] (Ampere)"}, /* pci.ids */
    {0x10de, 0x25aa, "GA107M [GeForce MX570 A] (Ampere)"}, /* pci.ids */
    {0x10de, 0x25ab, "GA107M [GeForce RTX 3050 4GB Laptop GPU] (Ampere)"}, /* pci.ids */
    {0x10de, 0x25ac, "GA107BM / GN20-P0-R-K2 [GeForce RTX 3050 6GB Laptop GPU] ("}, /* pci.ids */
    {0x10de, 0x25ad, "GA107 [GeForce RTX 2050] (Ampere)"}, /* pci.ids */
    {0x10de, 0x25af, "GA107 [GeForce RTX 3050 Engineering Sample] (Ampere)"}, /* pci.ids */
    {0x10de, 0x25e0, "GA107BM [GeForce RTX 3050 Ti Mobile] (Ampere)"}, /* pci.ids */
    {0x10de, 0x25e2, "GA107BM [GeForce RTX 3050 Mobile] (Ampere)"}, /* pci.ids */
    {0x10de, 0x2684, "AD102 [GeForce RTX 4090] (Ada)"}, /* pci.ids */
    {0x10de, 0x2685, "AD102 [GeForce RTX 4090 D] (Ada)"}, /* pci.ids */
    {0x10de, 0x2689, "AD102 [GeForce RTX 4070 Ti SUPER] (Ada)"}, /* pci.ids */
    {0x10de, 0x2702, "AD103 [GeForce RTX 4080 SUPER] (Ada)"}, /* pci.ids */
    {0x10de, 0x2704, "AD103 [GeForce RTX 4080] (Ada)"}, /* pci.ids */
    {0x10de, 0x2705, "AD103 [GeForce RTX 4070 Ti SUPER] (Ada)"}, /* pci.ids */
    {0x10de, 0x2709, "AD103 [GeForce RTX 4070] (Ada)"}, /* pci.ids */
    {0x10de, 0x2717, "AD103M / GN21-X11 [GeForce RTX 4090 Laptop GPU] (Ada)"}, /* pci.ids */
    {0x10de, 0x2782, "AD104 [GeForce RTX 4070 Ti] (Ada)"}, /* pci.ids */
    {0x10de, 0x2783, "AD104 [GeForce RTX 4070 SUPER] (Ada)"}, /* pci.ids */
    {0x10de, 0x2786, "AD104 [GeForce RTX 4070] (Ada)"}, /* pci.ids */
    {0x10de, 0x2788, "AD104 [GeForce RTX 4060 Ti] (Ada)"}, /* pci.ids */
    {0x10de, 0x27a0, "AD104M [GeForce RTX 4080 Max-Q / Mobile] (Ada)"}, /* pci.ids */
    {0x10de, 0x2803, "AD106 [GeForce RTX 4060 Ti] (Ada)"}, /* pci.ids */
    {0x10de, 0x2805, "AD106 [GeForce RTX 4060 Ti 16GB] (Ada)"}, /* pci.ids */
    {0x10de, 0x2808, "AD106 [GeForce RTX 4060] (Ada)"}, /* pci.ids */
    {0x10de, 0x2820, "AD106M [GeForce RTX 4070 Max-Q / Mobile] (Ada)"}, /* pci.ids */
    {0x10de, 0x2822, "AD106M [GeForce RTX 3050 A Laptop GPU] (Ada)"}, /* pci.ids */
    {0x10de, 0x2882, "AD107 [GeForce RTX 4060] (Ada)"}, /* pci.ids */
    {0x10de, 0x28a0, "AD107M [GeForce RTX 4060 Max-Q / Mobile] (Ada)"}, /* pci.ids */
    {0x10de, 0x28a1, "AD107M [GeForce RTX 4050 Max-Q / Mobile] (Ada)"}, /* pci.ids */
    {0x10de, 0x28a3, "AD107M [GeForce RTX 3050 A Laptop GPU] (Ada)"}, /* pci.ids */
};

/* radeon_hd: 338 display ids named by the registry and bound by no
   driver table in the tree - known chips with nothing ported for them. */
static const struct gpu_pci_id gpu_registry_radeon_hd[] = {
    {0x1002, 0x1114, "Krackan [Radeon 840M / 860M Graphics]"}, /* pci.ids */
    {0x1002, 0x13c0, "Granite Ridge [Radeon 610M]"}, /* pci.ids */
    {0x1002, 0x1506, "Mendocino [Radeon 610M]"}, /* pci.ids */
    {0x1002, 0x150e, "Strix [Radeon 880M / 890M]"}, /* pci.ids */
    {0x1002, 0x154c, "Kryptos [Radeon RX 350]"}, /* pci.ids */
    {0x1002, 0x1586, "Strix Halo [Radeon Graphics / Radeon 8050S Graphics / Rade"}, /* pci.ids */
    {0x1002, 0x15d8, "Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile S"}, /* pci.ids */
    {0x1002, 0x15dd, "Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Serie"}, /* pci.ids */
    {0x1002, 0x1636, "Renoir [Radeon Vega Series / Radeon Vega Mobile Series]"}, /* pci.ids */
    {0x1002, 0x1638, "Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]"}, /* pci.ids */
    {0x1002, 0x164e, "Raphael [Radeon 610M]"}, /* pci.ids */
    {0x1002, 0x1681, "Rembrandt [Radeon 680M]"}, /* pci.ids */
    {0x1002, 0x3151, "RV380 GL [FireMV 2400]"}, /* pci.ids */
    {0x1002, 0x3152, "RV370/M22 [Mobility Radeon X300]"}, /* pci.ids */
    {0x1002, 0x3171, "RV380 GL [FireMV 2400] (Secondary)"}, /* pci.ids */
    {0x1002, 0x3e70, "RV380 [Radeon X550/X600] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4164, "R300 [Radeon 9500 PRO] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4165, "R300 [Radeon 9700 PRO] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4168, "RV350 [Radeon 9800 SE] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4170, "RV350 [Radeon 9550/9600/X1050 Series] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4171, "RV350 [Radeon 9600] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4172, "RV350 [Radeon 9600/X1050 Series] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4173, "RV350 [Radeon 9550] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4354, "215CT [Mach64 CT PCI]"}, /* pci.ids */
    {0x1002, 0x4358, "Mach64 CX [Graphics Xpression]"}, /* pci.ids */
    {0x1002, 0x4554, "210888ET [Mach64 ET]"}, /* pci.ids */
    {0x1002, 0x4654, "Mach64 VT"}, /* pci.ids */
    {0x1002, 0x4758, "Mach64 GX [WinTurbo]"}, /* pci.ids */
    {0x1002, 0x496e, "RV250 [Radeon 9000] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4a54, "R420 [Radeon X800 VE AGP]"}, /* pci.ids */
    {0x1002, 0x4a69, "R420 [Radeon X800 PRO/GTO] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4a6a, "R420 [Radeon X800] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4a6b, "R420 [Radeon X800 XT AGP] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4a70, "R420 [Radeon X800 XT Platinum Edition AGP] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4a74, "R420 [Radeon X800 VE] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4b69, "R481 [Radeon X850 XT AGP] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4b6b, "R481 [Radeon X850 PRO AGP] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4b6c, "R481 [Radeon X850 XT Platinum Edition AGP] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4c54, "264LT [Mach64 LT]"}, /* pci.ids */
    {0x1002, 0x4c6e, "RV250/M9 [Mobility Radeon 9000] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4d52, "Theater 550 PRO PCI [ATI TV Wonder 550]"}, /* pci.ids */
    {0x1002, 0x4e67, "R300 GL [FireGL X1] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4e68, "R350 [Radeon 9800 PRO] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4e69, "R350 [Radeon 9800] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4e6a, "RV350 [Radeon 9800 XT] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4e71, "RV350/M10 [Mobility Radeon 9600] (Secondary)"}, /* pci.ids */
    {0x1002, 0x4f73, "RV250 [Radeon 9000 Series] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5354, "Mach 64 VT"}, /* pci.ids */
    {0x1002, 0x5569, "R423 [Radeon X800 PRO] (Secondary)"}, /* pci.ids */
    {0x1002, 0x556b, "R423 [Radeon X800 GT] (Secondary)"}, /* pci.ids */
    {0x1002, 0x556d, "R480 [Radeon X800 GTO2/XL] (Secondary)"}, /* pci.ids */
    {0x1002, 0x556f, "R430 [Radeon X800] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5571, "R423 GL [FireGL V5100] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5657, "RV410 [Radeon X550 XTX / X700]"}, /* pci.ids */
    {0x1002, 0x5854, "RS480 [Radeon Xpress 200 Series] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5874, "RS480 [Radeon Xpress 1150] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5940, "RV280 [Radeon 9200 PRO] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5941, "RV280 [Radeon 9200] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5944, "RV280 [Radeon 9200 SE PCI]"}, /* pci.ids */
    {0x1002, 0x5b70, "RV370 [Radeon X300 SE]"}, /* pci.ids */
    {0x1002, 0x5b72, "RV380 [Radeon X300/X550/X1050 Series] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5b73, "RV370 [Radeon X300/X550/X1050 Series] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5b74, "RV370 GL [FireGL V3100] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5b75, "RV370 GL [FireMV 2200] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5d44, "RV280 [Radeon 9200 SE] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5d45, "RV280 GL [FireMV 2200 PCI] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5d6d, "R480 [Radeon X850 XT Platinum Edition] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5d6f, "R480 [Radeon X800 GTO] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5d72, "R480 [Radeon X850 XT] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5d77, "R423 [Radeon X800 XT] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5e49, "RV410 [Radeon X700 Series]"}, /* pci.ids */
    {0x1002, 0x5e6b, "RV410 [Radeon X700 PRO] (Secondary)"}, /* pci.ids */
    {0x1002, 0x5e6d, "RV410 [Radeon X700] (Secondary)"}, /* pci.ids */
    {0x1002, 0x6609, "Oland GL [FirePro W2100 / Barco MXRT 2600]"}, /* pci.ids */
    {0x1002, 0x6617, "Oland LE [Radeon R7 240]"}, /* pci.ids */
    {0x1002, 0x664d, "Bonaire [FirePro W5100 / Barco MXRT-5600]"}, /* pci.ids */
    {0x1002, 0x6660, "Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / Rad"}, /* pci.ids */
    {0x1002, 0x6663, "Sun PRO [Radeon HD 8570A/8570M]"}, /* pci.ids */
    {0x1002, 0x6664, "Jet XT [Radeon R5 M240]"}, /* pci.ids */
    {0x1002, 0x6665, "Jet PRO [Radeon R5 M230 / R7 M260DX / Radeon 520/610 Mobil"}, /* pci.ids */
    {0x1002, 0x6667, "Jet ULT [Radeon R5 M230]"}, /* pci.ids */
    {0x1002, 0x666f, "Sun LE [Radeon HD 8550M / R5 M230]"}, /* pci.ids */
    {0x1002, 0x66a0, "Vega 20 [Radeon Pro/Radeon Instinct]"}, /* pci.ids */
    {0x1002, 0x66a1, "Vega 20 [Radeon Pro VII/Radeon Instinct MI50]"}, /* pci.ids */
    {0x1002, 0x66a3, "Vega 20 [Radeon Pro Vega II/Radeon Pro Vega II Duo]"}, /* pci.ids */
    {0x1002, 0x66a7, "Vega 20 [Radeon Pro Vega 20]"}, /* pci.ids */
    {0x1002, 0x66af, "Vega 20 [Radeon VII]"}, /* pci.ids */
    {0x1002, 0x6720, "Blackcomb [Radeon HD 6970M/6990M]"}, /* pci.ids */
    {0x1002, 0x6739, "Barts PRO [Radeon HD 6850]"}, /* pci.ids */
    {0x1002, 0x674a, "Turks GL [FirePro V3900]"}, /* pci.ids */
    {0x1002, 0x6751, "Turks [Radeon HD 7650A/7670A]"}, /* pci.ids */
    {0x1002, 0x675b, "Turks [Radeon HD 7600 Series]"}, /* pci.ids */
    {0x1002, 0x6760, "Seymour [Radeon HD 6400M/7400M Series]"}, /* pci.ids */
    {0x1002, 0x679b, "Malta [Radeon HD 7990/8990 OEM]"}, /* pci.ids */
    {0x1002, 0x67c0, "Ellesmere [Radeon Pro WX 7100 Mobile]"}, /* pci.ids */
    {0x1002, 0x67c2, "Ellesmere [Radeon Pro V7300X / V7350x2]"}, /* pci.ids */
    {0x1002, 0x67c4, "Ellesmere [Radeon Pro WX 7100]"}, /* pci.ids */
    {0x1002, 0x67c7, "Ellesmere [Radeon Pro WX 5100]"}, /* pci.ids */
    {0x1002, 0x67d4, "Ellesmere [Radeon Pro WX 7100 / Barco MXRT-8700]"}, /* pci.ids */
    {0x1002, 0x67d7, "Ellesmere [Radeon Pro WX 5100 / Barco MXRT-6700]"}, /* pci.ids */
    {0x1002, 0x67df, "Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]"}, /* pci.ids */
    {0x1002, 0x67e0, "Baffin [Radeon Pro WX 4170]"}, /* pci.ids */
    {0x1002, 0x67e3, "Baffin [Radeon Pro WX 4100]"}, /* pci.ids */
    {0x1002, 0x67e8, "Baffin [Radeon Pro WX 4130/4150]"}, /* pci.ids */
    {0x1002, 0x67eb, "Baffin [Radeon Pro V5300X]"}, /* pci.ids */
    {0x1002, 0x67ef, "Baffin [Radeon RX 460/560D / Pro 450/455/460/555/555X/560/"}, /* pci.ids */
    {0x1002, 0x67ff, "Baffin [Radeon RX 550 640SP / RX 560/560X]"}, /* pci.ids */
    {0x1002, 0x6822, "Venus PRO [Radeon E8860]"}, /* pci.ids */
    {0x1002, 0x6840, "Thames [Radeon HD 7500M/7600M Series]"}, /* pci.ids */
    {0x1002, 0x6841, "Thames [Radeon HD 7550M/7570M/7650M]"}, /* pci.ids */
    {0x1002, 0x6842, "Thames LE [Radeon HD 7000M Series]"}, /* pci.ids */
    {0x1002, 0x6843, "Thames [Radeon HD 7670M]"}, /* pci.ids */
    {0x1002, 0x6861, "Vega 10 XT [Radeon PRO WX 9100]"}, /* pci.ids */
    {0x1002, 0x6862, "Vega 10 XT [Radeon PRO SSG]"}, /* pci.ids */
    {0x1002, 0x6863, "Vega 10 XTX [Radeon Vega Frontier Edition]"}, /* pci.ids */
    {0x1002, 0x6864, "Vega 10 [Radeon Pro V340/Instinct MI25x2]"}, /* pci.ids */
    {0x1002, 0x6867, "Vega 10 XL [Radeon Pro Vega 56]"}, /* pci.ids */
    {0x1002, 0x6868, "Vega 10 [Radeon PRO WX 8100/8200]"}, /* pci.ids */
    {0x1002, 0x6869, "Vega 10 XGA [Radeon Pro Vega 48]"}, /* pci.ids */
    {0x1002, 0x686b, "Vega 10 XTXA [Radeon Pro Vega 64X]"}, /* pci.ids */
    {0x1002, 0x687f, "Vega 10 XL/XT [Radeon RX Vega 56/64]"}, /* pci.ids */
    {0x1002, 0x6880, "Lexington [Radeon HD 6550M]"}, /* pci.ids */
    {0x1002, 0x6888, "Cypress XT [FirePro V8800]"}, /* pci.ids */
    {0x1002, 0x6889, "Cypress PRO [FirePro V7800]"}, /* pci.ids */
    {0x1002, 0x688a, "Cypress XT [FirePro V9800]"}, /* pci.ids */
    {0x1002, 0x689b, "Cypress PRO [Radeon HD 6800 Series]"}, /* pci.ids */
    {0x1002, 0x68a0, "Broadway XT [Mobility Radeon HD 5870]"}, /* pci.ids */
    {0x1002, 0x68a1, "Broadway PRO [Mobility Radeon HD 5850]"}, /* pci.ids */
    {0x1002, 0x68a8, "Granville [Radeon HD 6850M/6870M]"}, /* pci.ids */
    {0x1002, 0x68a9, "Juniper XT [FirePro V5800]"}, /* pci.ids */
    {0x1002, 0x68bf, "Juniper PRO [Radeon HD 6750]"}, /* pci.ids */
    {0x1002, 0x68c0, "Madison [Mobility Radeon HD 5730 / 6570M]"}, /* pci.ids */
    {0x1002, 0x68c7, "Pinewood [Mobility Radeon HD 5570/6550A]"}, /* pci.ids */
    {0x1002, 0x68c9, "Redwood PRO GL [FirePro V3800]"}, /* pci.ids */
    {0x1002, 0x68e5, "Robson LE [Radeon HD 6330M]"}, /* pci.ids */
    {0x1002, 0x68e9, "Cedar [ATI FirePro (FireGL) Graphics Adapter]"}, /* pci.ids */
    {0x1002, 0x68f1, "Cedar GL [FirePro 2460]"}, /* pci.ids */
    {0x1002, 0x68f2, "Cedar GL [FirePro 2270]"}, /* pci.ids */
    {0x1002, 0x68f8, "Cedar [Radeon HD 7300 Series]"}, /* pci.ids */
    {0x1002, 0x6900, "Topaz XT [Radeon R7 M260/M265 / M340/M360 / M440/M445 / 53"}, /* pci.ids */
    {0x1002, 0x6901, "Topaz PRO [Radeon R5 M255]"}, /* pci.ids */
    {0x1002, 0x6907, "Meso XT [Radeon R5 M315]"}, /* pci.ids */
    {0x1002, 0x6929, "Tonga XT GL [FirePro S7150]"}, /* pci.ids */
    {0x1002, 0x692b, "Tonga PRO GL [FirePro W7100]"}, /* pci.ids */
    {0x1002, 0x692f, "Tonga XTV GL [FirePro S7150V]"}, /* pci.ids */
    {0x1002, 0x6930, "Tonga PRO [Radeon R9 380 4GB]"}, /* pci.ids */
    {0x1002, 0x6939, "Tonga PRO [Radeon R9 285/380]"}, /* pci.ids */
    {0x1002, 0x693b, "Tonga PRO GL [FirePro W7100 / Barco MXRT-7600]"}, /* pci.ids */
    {0x1002, 0x694c, "Polaris 22 XT [Radeon RX Vega M GH]"}, /* pci.ids */
    {0x1002, 0x694e, "Polaris 22 XL [Radeon RX Vega M GL]"}, /* pci.ids */
    {0x1002, 0x694f, "Polaris 22 MGL XL [Radeon Pro WX Vega M GL]"}, /* pci.ids */
    {0x1002, 0x6981, "Lexa XT [Radeon PRO WX 3200]"}, /* pci.ids */
    {0x1002, 0x6985, "Lexa XT [Radeon PRO WX 3100]"}, /* pci.ids */
    {0x1002, 0x6987, "Lexa [Radeon 540X/550X/630 / RX 640 / E9171 MCM]"}, /* pci.ids */
    {0x1002, 0x698f, "Lexa XT [Radeon PRO WX 3100 / Barco MXRT 4700]"}, /* pci.ids */
    {0x1002, 0x6995, "Lexa XT [Radeon PRO WX 2100]"}, /* pci.ids */
    {0x1002, 0x699f, "Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X]"}, /* pci.ids */
    {0x1002, 0x69af, "Vega 12 [Radeon Pro Vega 20]"}, /* pci.ids */
    {0x1002, 0x6fdf, "Polaris 20 XL/XTR [Radeon RX 580 2048SP / RX 590 GME]"}, /* pci.ids */
    {0x1002, 0x7100, "R520 [Radeon X1800 XT]"}, /* pci.ids */
    {0x1002, 0x7101, "R520/M58 [Mobility Radeon X1800 XT]"}, /* pci.ids */
    {0x1002, 0x7102, "R520/M58 [Mobility Radeon X1800]"}, /* pci.ids */
    {0x1002, 0x7104, "R520 GL [FireGL V7200 / Barco MXTR-5100]"}, /* pci.ids */
    {0x1002, 0x7109, "R520 [Radeon X1800 XL]"}, /* pci.ids */
    {0x1002, 0x710a, "R520 [Radeon X1800 GTO]"}, /* pci.ids */
    {0x1002, 0x710e, "R520 GL [FireGL V7300]"}, /* pci.ids */
    {0x1002, 0x710f, "R520 GL [FireGL V7350]"}, /* pci.ids */
    {0x1002, 0x7120, "R520 [Radeon X1800] (Secondary)"}, /* pci.ids */
    {0x1002, 0x7124, "R520 GL [FireGL V7200] (Secondary)"}, /* pci.ids */
    {0x1002, 0x712e, "R520 GL [FireGL V7300] (Secondary)"}, /* pci.ids */
    {0x1002, 0x712f, "R520 GL [FireGL V7350] (Secondary)"}, /* pci.ids */
    {0x1002, 0x7140, "RV515 [Radeon X1300/X1550/X1600 Series]"}, /* pci.ids */
    {0x1002, 0x7142, "RV515 PRO [Radeon X1300/X1550 Series]"}, /* pci.ids */
    {0x1002, 0x7143, "RV505 [Radeon X1300/X1550 Series]"}, /* pci.ids */
    {0x1002, 0x7145, "RV515/M54 [Mobility Radeon X1400]"}, /* pci.ids */
    {0x1002, 0x7146, "RV515 [Radeon X1300/X1550]"}, /* pci.ids */
    {0x1002, 0x7147, "RV505 [Radeon X1550 64-bit]"}, /* pci.ids */
    {0x1002, 0x7149, "RV515/M52 [Mobility Radeon X1300]"}, /* pci.ids */
    {0x1002, 0x7152, "RV515 GL [FireGL V3300]"}, /* pci.ids */
    {0x1002, 0x7153, "RV515 GL [FireGL V3350]"}, /* pci.ids */
    {0x1002, 0x715f, "RV505 CE [Radeon X1550 64-bit]"}, /* pci.ids */
    {0x1002, 0x7162, "RV515 PRO [Radeon X1300/X1550 Series] (Secondary)"}, /* pci.ids */
    {0x1002, 0x7163, "RV505 [Radeon X1550 Series] (Secondary)"}, /* pci.ids */
    {0x1002, 0x7166, "RV515 [Radeon X1300/X1550 Series] (Secondary)"}, /* pci.ids */
    {0x1002, 0x7167, "RV515 [Radeon X1550 64-bit] (Secondary)"}, /* pci.ids */
    {0x1002, 0x7172, "RV515 GL [FireGL V3300] (Secondary)"}, /* pci.ids */
    {0x1002, 0x7173, "RV515 GL [FireGL V3350] (Secondary)"}, /* pci.ids */
    {0x1002, 0x7181, "RV516 [Radeon X1600/X1650 Series]"}, /* pci.ids */
    {0x1002, 0x7183, "RV516 [Radeon X1300/X1550 Series]"}, /* pci.ids */
    {0x1002, 0x7186, "RV516/M64 [Mobility Radeon X1450]"}, /* pci.ids */
    {0x1002, 0x7188, "RV516/M64-S [Mobility Radeon X2300]"}, /* pci.ids */
    {0x1002, 0x718a, "RV516/M64 [Mobility Radeon X2300]"}, /* pci.ids */
    {0x1002, 0x718b, "RV516/M62 [Mobility Radeon X1350]"}, /* pci.ids */
    {0x1002, 0x718c, "RV516/M62-CSP64 [Mobility Radeon X1350]"}, /* pci.ids */
    {0x1002, 0x718d, "RV516/M64-CSP128 [Mobility Radeon X1450]"}, /* pci.ids */
    {0x1002, 0x7193, "RV516 [Radeon X1550 Series]"}, /* pci.ids */
    {0x1002, 0x7196, "RV516/M62-S [Mobility Radeon X1350]"}, /* pci.ids */
    {0x1002, 0x719b, "RV516 GL [FireMV 2250]"}, /* pci.ids */
    {0x1002, 0x71a0, "RV516 [Radeon X1300/X1550 Series] (Secondary)"}, /* pci.ids */
    {0x1002, 0x71a1, "RV516 [Radeon X1600/X1650 Series] (Secondary)"}, /* pci.ids */
    {0x1002, 0x71bb, "RV516 GL [FireMV 2250] (Secondary)"}, /* pci.ids */
    {0x1002, 0x71c0, "RV530 [Radeon X1600 XT/X1650 GTO]"}, /* pci.ids */
    {0x1002, 0x71c1, "RV535 [Radeon X1650 PRO]"}, /* pci.ids */
    {0x1002, 0x71c2, "RV530 [Radeon X1600 PRO]"}, /* pci.ids */
    {0x1002, 0x71c4, "RV530/M56 GL [Mobility FireGL V5200]"}, /* pci.ids */
    {0x1002, 0x71c5, "RV530/M56-P [Mobility Radeon X1600]"}, /* pci.ids */
    {0x1002, 0x71c6, "RV530LE [Radeon X1600/X1650 PRO]"}, /* pci.ids */
    {0x1002, 0x71ce, "RV530 [Radeon X1300 XT/X1600 PRO]"}, /* pci.ids */
    {0x1002, 0x71d2, "RV530 GL [FireGL V3400]"}, /* pci.ids */
    {0x1002, 0x71d4, "RV530/M66 GL [Mobility FireGL V5250]"}, /* pci.ids */
    {0x1002, 0x71d5, "RV530/M66-P [Mobility Radeon X1700]"}, /* pci.ids */
    {0x1002, 0x71d6, "RV530/M66-XT [Mobility Radeon X1700]"}, /* pci.ids */
    {0x1002, 0x71de, "RV530/M66 [Mobility Radeon X1700/X2500]"}, /* pci.ids */
    {0x1002, 0x71e0, "RV530 [Radeon X1600] (Secondary)"}, /* pci.ids */
    {0x1002, 0x71e1, "RV535 [Radeon X1650 PRO] (Secondary)"}, /* pci.ids */
    {0x1002, 0x71e6, "RV530 [Radeon X1650] (Secondary)"}, /* pci.ids */
    {0x1002, 0x71f2, "RV530 GL [FireGL V3400] (Secondary)"}, /* pci.ids */
    {0x1002, 0x7210, "RV550/M71 [Mobility Radeon HD 2300]"}, /* pci.ids */
    {0x1002, 0x7211, "RV550/M71 [Mobility Radeon X2300 HD]"}, /* pci.ids */
    {0x1002, 0x7240, "R580+ [Radeon X1950 XTX]"}, /* pci.ids */
    {0x1002, 0x7244, "R580+ [Radeon X1950 XT]"}, /* pci.ids */
    {0x1002, 0x7248, "R580 [Radeon X1950]"}, /* pci.ids */
    {0x1002, 0x7249, "R580 [Radeon X1900 XT]"}, /* pci.ids */
    {0x1002, 0x724b, "R580 [Radeon X1900 GT]"}, /* pci.ids */
    {0x1002, 0x724e, "R580 GL [FireGL V7350]"}, /* pci.ids */
    {0x1002, 0x7269, "R580 [Radeon X1900 XT] (Secondary)"}, /* pci.ids */
    {0x1002, 0x726b, "R580 [Radeon X1900 GT] (Secondary)"}, /* pci.ids */
    {0x1002, 0x7280, "RV570 [Radeon X1950 PRO]"}, /* pci.ids */
    {0x1002, 0x7288, "RV570 [Radeon X1950 GT]"}, /* pci.ids */
    {0x1002, 0x7291, "RV560 [Radeon X1650 XT]"}, /* pci.ids */
    {0x1002, 0x7293, "RV560 [Radeon X1650 GT]"}, /* pci.ids */
    {0x1002, 0x72a0, "RV570 [Radeon X1950 PRO] (Secondary)"}, /* pci.ids */
    {0x1002, 0x72a8, "RV570 [Radeon X1950 GT] (Secondary)"}, /* pci.ids */
    {0x1002, 0x72b1, "RV560 [Radeon X1650 XT] (Secondary)"}, /* pci.ids */
    {0x1002, 0x72b3, "RV560 [Radeon X1650 GT] (Secondary)"}, /* pci.ids */
    {0x1002, 0x7300, "Fiji [Radeon R9 FURY / NANO Series]"}, /* pci.ids */
    {0x1002, 0x7310, "Navi 10 [Radeon Pro W5700X]"}, /* pci.ids */
    {0x1002, 0x7312, "Navi 10 [Radeon Pro W5700]"}, /* pci.ids */
    {0x1002, 0x7319, "Navi 10 [Radeon Pro 5700 XT]"}, /* pci.ids */
    {0x1002, 0x731b, "Navi 10 [Radeon Pro 5700]"}, /* pci.ids */
    {0x1002, 0x731f, "Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]"}, /* pci.ids */
    {0x1002, 0x7340, "Navi 14 [Radeon RX 5500/5500M / Pro 5300/5300M/5500M]"}, /* pci.ids */
    {0x1002, 0x7341, "Navi 14 [Radeon Pro W5500]"}, /* pci.ids */
    {0x1002, 0x7347, "Navi 14 [Radeon Pro W5500M]"}, /* pci.ids */
    {0x1002, 0x734f, "Navi 14 [Radeon Pro W5300M]"}, /* pci.ids */
    {0x1002, 0x7360, "Navi 12 [Radeon Pro 5600M/V520/BC-160]"}, /* pci.ids */
    {0x1002, 0x7362, "Navi 12 [Radeon Pro V520/V540]"}, /* pci.ids */
    {0x1002, 0x73a5, "Navi 21 [Radeon RX 6950 XT]"}, /* pci.ids */
    {0x1002, 0x73af, "Navi 21 [Radeon RX 6900 XT]"}, /* pci.ids */
    {0x1002, 0x73e3, "Navi 23 WKS-XL [Radeon PRO W6600]"}, /* pci.ids */
    {0x1002, 0x73ef, "Navi 23 [Radeon RX 6650 XT / 6700S / 6800S]"}, /* pci.ids */
    {0x1002, 0x73f0, "Navi 33 [Radeon RX 7600M XT]"}, /* pci.ids */
    {0x1002, 0x7421, "Navi 24 [Radeon PRO W6500M]"}, /* pci.ids */
    {0x1002, 0x7422, "Navi 24 [Radeon PRO W6400]"}, /* pci.ids */
    {0x1002, 0x7423, "Navi 24 [Radeon PRO W6300/W6300M]"}, /* pci.ids */
    {0x1002, 0x7424, "Navi 24 [Radeon RX 6300]"}, /* pci.ids */
    {0x1002, 0x743f, "Navi 24 [Radeon RX 6400/6500 XT/6500M]"}, /* pci.ids */
    {0x1002, 0x7448, "Navi 31 [Radeon Pro W7900]"}, /* pci.ids */
    {0x1002, 0x7449, "Navi 31 [Radeon Pro W7800 48GB]"}, /* pci.ids */
    {0x1002, 0x744a, "Navi 31 [Radeon Pro W7900 Dual Slot]"}, /* pci.ids */
    {0x1002, 0x744b, "Navi 31 [Radeon Pro W7900D]"}, /* pci.ids */
    {0x1002, 0x744c, "Navi 31 [Radeon RX 7900 XT/7900 XTX/7900 GRE/7900M]"}, /* pci.ids */
    {0x1002, 0x745e, "Navi 31 [Radeon Pro W7800]"}, /* pci.ids */
    {0x1002, 0x7460, "Navi 32 GL-XL [AMD Radeon PRO V710]"}, /* pci.ids */
    {0x1002, 0x7461, "Navi 32 [AMD Radeon PRO V710]"}, /* pci.ids */
    {0x1002, 0x7470, "Navi 32 [Radeon PRO W7700]"}, /* pci.ids */
    {0x1002, 0x747e, "Navi 32 [Radeon RX 7700 XT / 7800 XT]"}, /* pci.ids */
    {0x1002, 0x7480, "Navi 33 [Radeon RX 7600/7600 XT/7600M XT/7600S/7700S / PRO"}, /* pci.ids */
    {0x1002, 0x7481, "Navi 33 [Steam Machine]"}, /* pci.ids */
    {0x1002, 0x7483, "Navi 33 [Radeon RX 7600M/7600M XT]"}, /* pci.ids */
    {0x1002, 0x7487, "Navi 33 [Radeon Graphics]"}, /* pci.ids */
    {0x1002, 0x7489, "Navi 33 [Radeon Pro W7500]"}, /* pci.ids */
    {0x1002, 0x7499, "Navi 33 [Radeon RX 7400/7300/Pro W7400]"}, /* pci.ids */
    {0x1002, 0x749f, "Navi 33 [Radeon RX 7500]"}, /* pci.ids */
    {0x1002, 0x7550, "Navi 48 [Radeon RX 9070/9070 XT/9070 GRE]"}, /* pci.ids */
    {0x1002, 0x7551, "Navi 48 [Radeon AI PRO R9700]"}, /* pci.ids */
    {0x1002, 0x7590, "Navi 44 [Radeon RX 9050 / 9060 XT]"}, /* pci.ids */
    {0x1002, 0x791e, "RS690 [Radeon X1200]"}, /* pci.ids */
    {0x1002, 0x791f, "RS690M [Radeon Xpress 1200/1250/1270]"}, /* pci.ids */
    {0x1002, 0x793f, "RS690M [Radeon Xpress 1200/1250/1270] (Secondary)"}, /* pci.ids */
    {0x1002, 0x7941, "RS600 [Radeon Xpress 1250]"}, /* pci.ids */
    {0x1002, 0x7942, "RS600M [Radeon Xpress 1250]"}, /* pci.ids */
    {0x1002, 0x796e, "RS740 [Radeon 2100]"}, /* pci.ids */
    {0x1002, 0x9444, "RV770 GL [FirePro V8750]"}, /* pci.ids */
    {0x1002, 0x9446, "RV770 GL [FirePro V7760]"}, /* pci.ids */
    {0x1002, 0x944b, "RV770/M98 [Mobility Radeon HD 4850 X2]"}, /* pci.ids */
    {0x1002, 0x9456, "RV770 GL [FirePro V8700]"}, /* pci.ids */
    {0x1002, 0x945a, "RV770/M98-XT [Mobility Radeon HD 4870]"}, /* pci.ids */
    {0x1002, 0x9462, "RV790 [Radeon HD 4860]"}, /* pci.ids */
    {0x1002, 0x946a, "RV770 GL [FirePro M7750]"}, /* pci.ids */
    {0x1002, 0x9489, "RV730/M96 GL [Mobility FireGL V5725]"}, /* pci.ids */
    {0x1002, 0x9491, "RV730/M96-CSP [Radeon E4690]"}, /* pci.ids */
    {0x1002, 0x9495, "RV730 [Radeon HD 4600 AGP Series]"}, /* pci.ids */
    {0x1002, 0x949c, "RV730 GL [FirePro V7750]"}, /* pci.ids */
    {0x1002, 0x949e, "RV730 GL [FirePro V5700]"}, /* pci.ids */
    {0x1002, 0x949f, "RV730 GL [FirePro V3750]"}, /* pci.ids */
    {0x1002, 0x94a0, "RV740/M97 [Mobility Radeon HD 4830]"}, /* pci.ids */
    {0x1002, 0x94a3, "RV740/M97 GL [FirePro M7740]"}, /* pci.ids */
    {0x1002, 0x94c4, "RV610 LE [Radeon HD 2400 PRO AGP]"}, /* pci.ids */
    {0x1002, 0x94c5, "RV610 [Radeon HD 2400 LE]"}, /* pci.ids */
    {0x1002, 0x94c8, "RV610/M74 [Mobility Radeon HD 2400 XT]"}, /* pci.ids */
    {0x1002, 0x94cb, "RV610 [Radeon E2400]"}, /* pci.ids */
    {0x1002, 0x9500, "RV670 [Radeon HD 3850 X2]"}, /* pci.ids */
    {0x1002, 0x9504, "RV670/M88 [Mobility Radeon HD 3850]"}, /* pci.ids */
    {0x1002, 0x9506, "RV670/M88 [Mobility Radeon HD 3850 X2]"}, /* pci.ids */
    {0x1002, 0x9508, "RV670/M88-XT [Mobility Radeon HD 3870]"}, /* pci.ids */
    {0x1002, 0x9509, "RV670/M88 [Mobility Radeon HD 3870 X2]"}, /* pci.ids */
    {0x1002, 0x9511, "RV670 GL [FireGL V7700]"}, /* pci.ids */
    {0x1002, 0x9557, "RV711/M93 GL [FirePro RG220]"}, /* pci.ids */
    {0x1002, 0x955f, "RV710/M92 [Mobility Radeon HD 4330]"}, /* pci.ids */
    {0x1002, 0x9580, "RV630 [Radeon HD 2600 PRO]"}, /* pci.ids */
    {0x1002, 0x9587, "RV630 PRO [Radeon HD 2600 PRO AGP]"}, /* pci.ids */
    {0x1002, 0x958b, "RV630/M76 [Mobility Radeon HD 2600 XT]"}, /* pci.ids */
    {0x1002, 0x958c, "RV630 GL [FireGL V5600]"}, /* pci.ids */
    {0x1002, 0x958d, "RV630 GL [FireGL V3600]"}, /* pci.ids */
    {0x1002, 0x9593, "RV635/M86 [Mobility Radeon HD 3670]"}, /* pci.ids */
    {0x1002, 0x9595, "RV635/M86 GL [Mobility FireGL V5700]"}, /* pci.ids */
    {0x1002, 0x9596, "RV635 PRO [Radeon HD 3650 AGP]"}, /* pci.ids */
    {0x1002, 0x95cc, "RV620 GL [FirePro V3700]"}, /* pci.ids */
    {0x1002, 0x95cd, "RV620 GL [FirePro 2450]"}, /* pci.ids */
    {0x1002, 0x95cf, "RV620 GL [FirePro 2260]"}, /* pci.ids */
    {0x1002, 0x9647, "Sumo [Radeon HD 6520G]"}, /* pci.ids */
    {0x1002, 0x9648, "Sumo [Radeon HD 6480G]"}, /* pci.ids */
    {0x1002, 0x9649, "SuperSumo [Radeon HD 6480G]"}, /* pci.ids */
    {0x1002, 0x9713, "RS880M [Mobility Radeon HD 4100]"}, /* pci.ids */
    {0x1002, 0x9809, "Wrestler [Radeon HD 7310]"}, /* pci.ids */
    {0x1002, 0x980a, "Wrestler [Radeon HD 7290]"}, /* pci.ids */
    {0x1002, 0x9830, "Kabini [Radeon HD 8400 / R3 Series]"}, /* pci.ids */
    {0x1002, 0x9831, "Kabini [Radeon HD 8400E]"}, /* pci.ids */
    {0x1002, 0x9874, "Wani [Radeon R5/R6/R7 Graphics]"}, /* pci.ids */
    {0x1002, 0x98e4, "Stoney [Radeon R2/R3/R4/R5 Graphics]"}, /* pci.ids */
    {0x1002, 0x9993, "Trinity 2 [Radeon HD 7480D]"}, /* pci.ids */
    {0x1002, 0x9998, "Richland [Radeon HD 8370D]"}, /* pci.ids */
    {0x1002, 0x9999, "Richland [Radeon HD 8510G]"}, /* pci.ids */
    {0x1002, 0xac02, "TV Wonder HD 600 PCIe"}, /* pci.ids */
    {0x1022, 0x13ec, "Ariel Cryptographic Coprocessor"}, /* pci.ids */
    {0x1022, 0x1468, "Zeppelin Cryptographic Coprocessor NTBCCP"}, /* pci.ids */
    {0x1022, 0x1486, "Starship/Matisse Cryptographic Coprocessor PSPCPP"}, /* pci.ids */
};

struct gpu_registry_table {
    const char *family;
    const struct gpu_pci_id *ids;
    uint16_t count;
};

static const struct gpu_registry_table gpu_registry_table[] = {
    {"intel_extreme", gpu_registry_intel_extreme, 135u},
    {"nvidia", gpu_registry_nvidia, 804u},
    {"radeon_hd", gpu_registry_radeon_hd, 338u},
};

#define GPU_REGISTRY_FAMILIES 3u
#define GPU_REGISTRY_ID_TOTAL 1277u

#endif
