#!/usr/bin/env python3
"""The build stamp: which commit these bytes came from, and whether the tree was dirty.

A USB stick can carry an image that was never committed.  That is not hypothetical here: a
panel was once reported as "the features are missing" from a stick built out of a sandbox state
that no commit contains (its naming table held 1298 rows against the repository's 1296), so the
code under review and the machine being judged were two different builds.  Nothing in the OS used
to be able to say so.  Now the stamp is generated from the repository state, compiled into every
translation unit, printed by `graphics`, `version`, the About panel and the serial log, written to
the ESP as \\SCOS\\BUILD.TXT, and checked by tools/makedisk.py against the kernel it packs.

The timestamp only moves when the git state moves, so `make` on an unchanged tree stays a no-op.

  tools/buildinfo.py --header build/scosbuild.h    generate/refresh the compiled-in stamp
  tools/buildinfo.py --read build/scosbuild.h      print it as JSON (used by makedisk and tests)
"""
import json, os, re, subprocess, sys, time
from pathlib import Path

FIELDS = ("COMMIT", "BRANCH", "TREE", "DATE")


def git(root, *args):
    try:
        out = subprocess.run(("git",) + args, cwd=str(root), capture_output=True, text=True,
                             timeout=20)
        return out.stdout.strip() if out.returncode == 0 else ""
    except Exception:
        return ""


def state(root):
    """Repository state at build time.  No git (an extracted tree) still yields a usable stamp."""
    commit = git(root, "rev-parse", "--short=12", "HEAD") or "nogit"
    branch = git(root, "rev-parse", "--abbrev-ref", "HEAD") or "nogit"
    tree = "clean" if not git(root, "status", "--porcelain") else "modified"
    return {"COMMIT": commit, "BRANCH": branch, "TREE": tree,
            "DATE": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}


def read_header(path):
    text = Path(path).read_text()
    found = dict(re.findall(r'#define SCOS_BUILD_(\w+) "([^"]*)"', text))
    missing = [f for f in FIELDS if f not in found]
    if missing:
        raise SystemExit("%s lacks a stamp for %s" % (path, ", ".join(missing)))
    return found


def write_if_changed(path, text):
    p = Path(path)
    if p.exists() and p.read_text() == text:
        return False
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)
    return True


def render(values):
    lines = ["/* Generated by tools/buildinfo.py from the repository state at build time.",
             " * Not edited by hand and not authoritative until read by the kernel: the boot stub,",
             " * `graphics`, `version`, the About panel and the disk record all print these strings,",
             " * and tools/makedisk.py refuses to pack a kernel whose copy disagrees with the disk's.",
             " * TREE is `modified` when the build ran with uncommitted changes - treat such an image",
             " * as an experiment, and never as evidence about a committed feature. */",
             "#ifndef SCOS_BUILDINFO_H", "#define SCOS_BUILDINFO_H", ""]
    for field in FIELDS:
        lines.append('#define SCOS_BUILD_%s "%s"' % (field, values[field]))
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def main(argv):
    here = Path(__file__).resolve().parents[1]
    if argv and argv[0] == "--header":
        path = Path(argv[1])
        values = state(here)
        # Reuse the recorded build time while the tree identity is unchanged, so an unchanged
        # repository does not look like a source edit and rebuild the world.
        if path.exists():
            try:
                old = read_header(path)
                if all(old[f] == values[f] for f in ("COMMIT", "BRANCH", "TREE")):
                    values["DATE"] = old["DATE"]
            except SystemExit:
                pass
        print("stamp: %s" % write_if_changed(path, render(values)))
        return 0
    if argv and argv[0] == "--read":
        print(json.dumps(read_header(argv[1]), sort_keys=True))
        return 0
    if argv and argv[0] == "--stamp":
        v = read_header(argv[1]) if len(argv) > 1 else state(here)
        print("%s %s, %s" % (v["COMMIT"], v["TREE"], v["DATE"]))
        return 0
    raise SystemExit(__doc__.strip().splitlines()[-3])


if __name__ == "__main__":
    main(sys.argv[1:])
