#!/usr/bin/env python3
"""
SCos native - generate kernel/src/font_data.c

Renders the printable ASCII range of a monospace TTF into an 8x16 bitmap
font table (font8x16[256][16], row-major, MSB = leftmost pixel).

Glyphs are drawn with the font's own metrics (fixed baseline, no per-glyph
cropping or scaling) so that punctuation keeps its true size and position.
"""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

FONT_PATHS = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/dejavu/DejaVuSansMono.ttf",
]

CELL_W, CELL_H = 8, 16
BASELINE = 12          # rows 0..11 above baseline, 12..15 descender room


def pick_size(path):
    """Largest size whose advance width fits 8 px and ascender fits the cell."""
    best = 8
    for cand in range(8, 20):
        f = ImageFont.truetype(path, cand)
        adv = f.getlength("M")
        asc, desc = f.getmetrics()
        if adv <= CELL_W and asc <= BASELINE and asc + desc <= CELL_H + 2:
            best = cand
    return best


def render_glyph(font, ch):
    img = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, BASELINE), ch, font=font, fill=255, anchor="ls")
    px = img.load()
    rows = []
    for y in range(CELL_H):
        bits = 0
        for x in range(CELL_W):
            if px[x, y] > 100:
                bits |= 0x80 >> x
        rows.append(bits)
    return rows


def main(out_path):
    path = next((p for p in FONT_PATHS if os.path.exists(p)), None)
    if not path:
        print("no TTF font found", file=sys.stderr)
        return 1
    size = pick_size(path)
    font = ImageFont.truetype(path, size)

    table = [[0] * 16 for _ in range(256)]
    for code in range(32, 127):
        table[code] = render_glyph(font, chr(code))
    # a few extras used by the UI
    table[0xB0] = render_glyph(font, "*")   # degree-ish filler
    table[0xFE] = render_glyph(font, "#")

    with open(out_path, "w") as f:
        f.write("/* Generated by tools/fontgen.py - do not edit. */\n")
        f.write('#include "scos.h"\n\n')
        f.write("const u8 font8x16[256][16] = {\n")
        for i, rows in enumerate(table):
            f.write("    { " + ", ".join("0x%02x" % r for r in rows) + " },")
            if 32 <= i < 127:
                f.write("  /* %s */" % (repr(chr(i)) if i != 39 else "'\\''"))
            f.write("\n")
        f.write("};\n")
    print("wrote", out_path, "font size", size)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "kernel/src/font_data.c"))
